from . import const as const, messages as messages
from .connection import ActiveConnection as ActiveConnection
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.exceptions import Unauthorized as Unauthorized
from typing import Any, Awaitable, Callable

async def _handle_async_response(func: Any, hass: Any, connection: Any, msg: Any) -> None: ...
def async_response(func: Callable[[HomeAssistant, ActiveConnection, dict], Awaitable[None]]) -> const.WebSocketCommandHandler: ...
def require_admin(func: const.WebSocketCommandHandler) -> const.WebSocketCommandHandler: ...
def ws_require_user(only_owner: bool = ..., only_system_user: bool = ..., allow_system_user: bool = ..., only_active_user: bool = ..., only_inactive_user: bool = ...): ...
def websocket_command(schema: dict) -> Callable[[const.WebSocketCommandHandler], const.WebSocketCommandHandler]: ...
