from typing import Final

DOMAIN: str
POWERWALL_BASE_INFO: Final[str]
POWERWALL_COORDINATOR: Final[str]
POWERWALL_API: Final[str]
POWERWALL_API_CHANGED: Final[str]
UPDATE_INTERVAL: int
ATTR_FREQUENCY: str
ATTR_INSTANT_AVERAGE_VOLTAGE: str
ATTR_INSTANT_TOTAL_CURRENT: str
ATTR_IS_ACTIVE: str
MODEL: str
MANUFACTURER: str
CONFIG_ENTRY_COOKIE: str
AUTH_COOKIE_KEY: str
