from bleak.backends.service import BleakGATTServiceCollection as BleakGATTServiceCollection
from collections.abc import MutableMapping
from dataclasses import dataclass

MAX_CACHED_SERVICES: int

@dataclass(slots=True)
class ESPHomeBluetoothCache:
    _gatt_services_cache: MutableMapping[int, BleakGATTServiceCollection] = ...
    _gatt_mtu_cache: MutableMapping[int, int] = ...
    def get_gatt_services_cache(self, address: int) -> BleakGATTServiceCollection | None: ...
    def set_gatt_services_cache(self, address: int, services: BleakGATTServiceCollection) -> None: ...
    def clear_gatt_services_cache(self, address: int) -> None: ...
    def get_gatt_mtu_cache(self, address: int) -> int | None: ...
    def set_gatt_mtu_cache(self, address: int, mtu: int) -> None: ...
    def clear_gatt_mtu_cache(self, address: int) -> None: ...
    def __init__(self, _gatt_services_cache, _gatt_mtu_cache) -> None: ...
