from _typeshed import Incomplete

DOMAIN: str
DATA_SDM: str
DATA_SUBSCRIBER: str
DATA_DEVICE_MANAGER: str
DATA_NEST_CONFIG: str
WEB_AUTH_DOMAIN = DOMAIN
INSTALLED_AUTH_DOMAIN: Incomplete
CONF_PROJECT_ID: str
CONF_SUBSCRIBER_ID: str
CONF_SUBSCRIBER_ID_IMPORTED: str
CONF_CLOUD_PROJECT_ID: str
CONNECTIVITY_TRAIT_OFFLINE: str
SIGNAL_NEST_UPDATE: str
OAUTH2_AUTHORIZE: str
OAUTH2_TOKEN: str
SDM_SCOPES: Incomplete
API_URL: str
