from _typeshed import Incomplete

NEST_EVENT: str
EVENT_DOORBELL_CHIME: str
EVENT_CAMERA_MOTION: str
EVENT_CAMERA_PERSON: str
EVENT_CAMERA_SOUND: str
DEVICE_TRAIT_TRIGGER_MAP: Incomplete
EVENT_NAME_MAP: Incomplete
MEDIA_SOURCE_EVENT_TITLE_MAP: Incomplete
