from _typeshed import Incomplete
from homeassistant.const import Platform as Platform
from synology_dsm.api.surveillance_station.const import SNAPSHOT_PROFILE_BALANCED

DOMAIN: str
ATTRIBUTION: str
PLATFORMS: Incomplete
COORDINATOR_CAMERAS: str
COORDINATOR_CENTRAL: str
COORDINATOR_SWITCHES: str
SYSTEM_LOADED: str
EXCEPTION_DETAILS: str
EXCEPTION_UNKNOWN: str
SYNO_API: str
UNDO_UPDATE_LISTENER: str
CONF_SERIAL: str
CONF_VOLUMES: str
CONF_DEVICE_TOKEN: str
CONF_SNAPSHOT_QUALITY: str
DEFAULT_USE_SSL: bool
DEFAULT_VERIFY_SSL: bool
DEFAULT_PORT: int
DEFAULT_PORT_SSL: int
DEFAULT_SCAN_INTERVAL: int
DEFAULT_TIMEOUT: int
DEFAULT_SNAPSHOT_QUALITY = SNAPSHOT_PROFILE_BALANCED
ENTITY_UNIT_LOAD: str
SIGNAL_CAMERA_SOURCE_CHANGED: str
SERVICE_REBOOT: str
SERVICE_SHUTDOWN: str
SERVICES: Incomplete
