from typing import Final

CONF_RETURN_AVERAGE: Final[str]
CONF_CLIP_NEGATIVE: Final[str]
DOMAIN: Final[str]
MANUFACTURER: Final[str]
CONCENTRATION_GRAMS_PER_CUBIC_METER: Final[str]
ACTIVITY_BECQUEREL_PER_CUBIC_METER: Final[str]
UPDATE_INTERVAL: float
