import axis
from ..const import ATTR_MANUFACTURER as ATTR_MANUFACTURER
from .config import AxisConfig as AxisConfig
from .entity_loader import AxisEntityLoader as AxisEntityLoader
from _typeshed import Incomplete
from axis.stream_manager import Signal
from homeassistant.components import mqtt as mqtt
from homeassistant.components.mqtt.models import ReceiveMessage as ReceiveMessage
from homeassistant.config_entries import ConfigEntry as ConfigEntry
from homeassistant.core import Event as Event, HomeAssistant as HomeAssistant, callback as callback
from homeassistant.helpers.device_registry import CONNECTION_NETWORK_MAC as CONNECTION_NETWORK_MAC, format_mac as format_mac
from homeassistant.helpers.dispatcher import async_dispatcher_send as async_dispatcher_send
from homeassistant.setup import async_when_setup as async_when_setup

class AxisHub:
    hass: Incomplete
    config: Incomplete
    entity_loader: Incomplete
    api: Incomplete
    available: bool
    fw_version: Incomplete
    product_type: Incomplete
    unique_id: Incomplete
    additional_diagnostics: Incomplete
    def __init__(self, hass: HomeAssistant, config_entry: ConfigEntry, api: axis.AxisDevice) -> None: ...
    @staticmethod
    def get_hub(hass: HomeAssistant, config_entry: ConfigEntry) -> AxisHub: ...
    @property
    def signal_reachable(self) -> str: ...
    @property
    def signal_new_address(self) -> str: ...
    def connection_status_callback(self, status: Signal) -> None: ...
    @staticmethod
    async def async_new_address_callback(hass: HomeAssistant, config_entry: ConfigEntry) -> None: ...
    async def async_update_device_registry(self) -> None: ...
    async def async_use_mqtt(self, hass: HomeAssistant, component: str) -> None: ...
    def mqtt_message(self, message: ReceiveMessage) -> None: ...
    def setup(self) -> None: ...
    def disconnect_from_stream(self) -> None: ...
    async def shutdown(self, event: Event) -> None: ...
    def teardown(self) -> None: ...
