from collections.abc import Buffer, Callable as Callable
from homeassistant.core import Event as Event, callback as callback
from homeassistant.exceptions import ConfigEntryNotReady as ConfigEntryNotReady
from serialx import BaseSerial, BaseSerialTransport, ModemPins
from serialx.common import ConnectKwargs as ConnectKwargs
from typing import Unpack, override

_NOT_READY: str

class HassESPHomeSerialStub(BaseSerial):
    @override
    def _open(self) -> None: ...
    @override
    def _configure_port(self) -> None: ...
    @override
    def _close(self) -> None: ...
    @property
    @override
    def is_open(self) -> bool: ...
    @override
    def _get_modem_pins(self) -> ModemPins: ...
    @override
    def _set_modem_pins(self, modem_pins: ModemPins) -> None: ...
    @override
    def _readinto(self, b: Buffer, *, timeout: float | None) -> int: ...
    @override
    def _write(self, data: Buffer, *, timeout: float | None) -> int: ...
    @override
    def _flush(self) -> None: ...
    @override
    def _reset_read_buffer(self) -> None: ...
    @override
    def _reset_write_buffer(self) -> None: ...
    @override
    def num_unread_bytes(self) -> int: ...
    @override
    def num_unwritten_bytes(self) -> int: ...

class HassESPHomeSerialStubTransport(BaseSerialTransport):
    transport_name: str
    @override
    async def _connect(self, *, path: str | None = None, **kwargs: Unpack[ConnectKwargs]) -> None: ...
    _closing: bool
    @override
    def close(self) -> None: ...
    @override
    def abort(self) -> None: ...
    @override
    async def _flush(self) -> None: ...
    @override
    async def _get_modem_pins(self) -> ModemPins: ...
    @override
    async def _set_modem_pins(self, modem_pins: ModemPins) -> None: ...

def register_serialx_transport() -> Callable[[Event], None]: ...
