import voluptuous as vol
from .const import CONF_HMI_HARDWARE as CONF_HMI_HARDWARE, CONF_HMI_SERIAL as CONF_HMI_SERIAL, CONF_KEY_SOURCE as CONF_KEY_SOURCE, CONF_WRAPPED_KEY as CONF_WRAPPED_KEY, DOMAIN as DOMAIN, KEY_SOURCE_ACCOUNT as KEY_SOURCE_ACCOUNT, KEY_SOURCE_MANUAL as KEY_SOURCE_MANUAL
from collections.abc import Callable as Callable, Mapping
from homeassistant.components.bluetooth import BluetoothServiceInfoBleak as BluetoothServiceInfoBleak, async_ble_device_from_address as async_ble_device_from_address, async_discovered_service_info as async_discovered_service_info
from homeassistant.config_entries import ConfigFlow as ConfigFlow, ConfigFlowResult as ConfigFlowResult
from homeassistant.const import CONF_ADDRESS as CONF_ADDRESS, CONF_EMAIL as CONF_EMAIL, CONF_PASSWORD as CONF_PASSWORD
from homeassistant.helpers.device_registry import format_mac as format_mac
from homeassistant.helpers.httpx_client import get_async_client as get_async_client
from specialized_turbo import BikeAdvertisement, BikeInfo as BikeInfo
from typing import Any, override

class SpecializedTurboConfigFlow(ConfigFlow, domain=DOMAIN):
    VERSION: int
    _discovery_info: BluetoothServiceInfoBleak | None
    _discovered_devices: dict[str, BluetoothServiceInfoBleak]
    _address: str | None
    _title: str
    _advertisement: BikeAdvertisement | None
    _bike_info: BikeInfo | None
    _target_entry_id: str | None
    def __init__(self) -> None: ...
    async def _async_test_connection(self) -> bool: ...
    async def _async_validate_encrypted_connection(self, wrapped_key: str) -> bool: ...
    async def _async_validate_connection(self, wrapped_key: str | None = None) -> bool: ...
    @override
    async def async_step_bluetooth(self, discovery_info: BluetoothServiceInfoBleak) -> ConfigFlowResult: ...
    async def async_step_bluetooth_confirm(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    @override
    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def _async_device_form(self, step_id: str, user_input: dict[str, Any] | None, *, include_address: bool) -> ConfigFlowResult: ...
    async def async_step_key_source(self, _user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_account(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_manual_key(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_reauth(self, entry_data: Mapping[str, Any]) -> ConfigFlowResult: ...
    async def async_step_reconfigure(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def _async_fetch_account_key(self, email: str, password: str) -> str: ...
    def _set_device(self, info: BluetoothServiceInfoBleak) -> None: ...
    @property
    def _requires_encryption(self) -> bool: ...
    def _device_schema(self, *, include_address: bool) -> vol.Schema: ...
    def _create_or_update_entry(self, key_data: dict[str, Any]) -> ConfigFlowResult: ...

def _is_specialized_service_info(info: BluetoothServiceInfoBleak) -> bool: ...
