from aiopyarr import RadarrMovie as RadarrMovie, RadarrQueue as RadarrQueue
from typing import Any

def format_queue_item(item: Any, base_url: str | None = None) -> dict[str, Any]: ...
def format_queue(queue: RadarrQueue, base_url: str | None = None) -> dict[str, dict[str, Any]]: ...
def format_movie_item(movie: RadarrMovie, base_url: str | None = None) -> dict[str, Any]: ...
def format_movies(movies: list[RadarrMovie], base_url: str | None = None) -> dict[str, dict[str, Any]]: ...
