from homeassistant.const import EVENT_SHOPPING_LIST_UPDATED as EVENT_SHOPPING_LIST_UPDATED

DOMAIN: str
ATTR_REVERSE: str
DEFAULT_REVERSE: bool
SERVICE_ADD_ITEM: str
SERVICE_REMOVE_ITEM: str
SERVICE_COMPLETE_ITEM: str
SERVICE_INCOMPLETE_ITEM: str
SERVICE_COMPLETE_ALL: str
SERVICE_INCOMPLETE_ALL: str
SERVICE_CLEAR_COMPLETED_ITEMS: str
SERVICE_SORT: str
