from .const import DOMAIN as DOMAIN, SCAN_INTERVAL as SCAN_INTERVAL, STATUS_PUSH_INTERVAL as STATUS_PUSH_INTERVAL, _LOGGER as _LOGGER
from _typeshed import Incomplete
from datetime import datetime
from homeassistant.config_entries import ConfigEntry as ConfigEntry
from homeassistant.const import CONF_ACCESS_TOKEN as CONF_ACCESS_TOKEN
from homeassistant.core import HomeAssistant as HomeAssistant
from homeassistant.exceptions import ConfigEntryAuthFailed as ConfigEntryAuthFailed, ConfigEntryNotReady as ConfigEntryNotReady, OAuth2TokenRequestError as OAuth2TokenRequestError, OAuth2TokenRequestReauthError as OAuth2TokenRequestReauthError
from homeassistant.helpers.aiohttp_client import async_get_clientsession as async_get_clientsession
from homeassistant.helpers.config_entry_oauth2_flow import OAuth2Session as OAuth2Session
from homeassistant.helpers.event import async_track_time_interval as async_track_time_interval
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator as DataUpdateCoordinator, UpdateFailed as UpdateFailed
from typing import override
from yoto_api import YotoPlayer

type YotoConfigEntry = ConfigEntry[YotoDataUpdateCoordinator]
class YotoDataUpdateCoordinator(DataUpdateCoordinator[dict[str, YotoPlayer]]):
    config_entry: YotoConfigEntry
    _session: Incomplete
    client: Incomplete
    _subscribed_players: set[str]
    def __init__(self, hass: HomeAssistant, entry: YotoConfigEntry, session: OAuth2Session) -> None: ...
    def _sync_token(self) -> None: ...
    @override
    async def _async_setup(self) -> None: ...
    @override
    async def _async_update_data(self) -> dict[str, YotoPlayer]: ...
    async def _async_sync_subscriptions(self) -> None: ...
    def _remove_stale_devices(self) -> None: ...
    async def _async_load_library(self) -> None: ...
    async def _async_status_push_tick(self, _now: datetime) -> None: ...
    def _mqtt_event(self, _player: YotoPlayer) -> None: ...
    @override
    async def async_shutdown(self) -> None: ...
