from .const import DOMAIN as DOMAIN
from .coordinator import YotoConfigEntry as YotoConfigEntry, YotoDataUpdateCoordinator as YotoDataUpdateCoordinator
from .entity import YotoPlayerEntity as YotoPlayerEntity
from _typeshed import Incomplete
from collections.abc import Awaitable, Callable as Callable
from datetime import datetime
from homeassistant.components.media_player import BrowseError as BrowseError, BrowseMedia as BrowseMedia, MediaClass as MediaClass, MediaPlayerDeviceClass as MediaPlayerDeviceClass, MediaPlayerEntity as MediaPlayerEntity, MediaPlayerEntityFeature as MediaPlayerEntityFeature, MediaPlayerState as MediaPlayerState, MediaType as MediaType
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.exceptions import HomeAssistantError as HomeAssistantError, ServiceValidationError as ServiceValidationError
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback as AddConfigEntryEntitiesCallback
from typing import Any, override
from yoto_api import Card as Card, Chapter as Chapter, Group as Group, Track as Track, YotoPlayer as YotoPlayer

URI_SCHEME: str
URI_CARD: str
URI_GROUP: str
PARALLEL_UPDATES: int
VOLUME_STEP: Incomplete
PLAYBACK_STATE_MAP: Incomplete

async def async_setup_entry(hass: HomeAssistant, entry: YotoConfigEntry, async_add_entities: AddConfigEntryEntitiesCallback) -> None: ...

class YotoMediaPlayer(YotoPlayerEntity, MediaPlayerEntity):
    _attr_name: Incomplete
    _attr_device_class: Incomplete
    _attr_media_image_remotely_accessible: bool
    _attr_volume_step = VOLUME_STEP
    _attr_supported_features: Incomplete
    _attr_unique_id: Incomplete
    def __init__(self, coordinator: YotoDataUpdateCoordinator, player: YotoPlayer) -> None: ...
    @property
    @override
    def state(self) -> MediaPlayerState: ...
    @property
    @override
    def volume_level(self) -> float | None: ...
    @property
    @override
    def media_duration(self) -> int | None: ...
    @property
    @override
    def media_position(self) -> int | None: ...
    @property
    @override
    def media_position_updated_at(self) -> datetime | None: ...
    @property
    @override
    def media_title(self) -> str | None: ...
    @property
    @override
    def media_album_name(self) -> str | None: ...
    @property
    @override
    def media_artist(self) -> str | None: ...
    @property
    @override
    def media_image_url(self) -> str | None: ...
    def _current_card(self) -> Card | None: ...
    @override
    async def async_media_play(self) -> None: ...
    @override
    async def async_media_pause(self) -> None: ...
    @override
    async def async_media_stop(self) -> None: ...
    @override
    async def async_set_volume_level(self, volume: float) -> None: ...
    @override
    async def async_media_seek(self, position: float) -> None: ...
    @override
    async def async_media_next_track(self) -> None: ...
    @override
    async def async_media_previous_track(self) -> None: ...
    @override
    async def async_play_media(self, media_type: MediaType | str, media_id: str, **kwargs: Any) -> None: ...
    @override
    async def async_browse_media(self, media_content_type: MediaType | str | None = None, media_content_id: str | None = None) -> BrowseMedia: ...
    def _browse_root(self) -> BrowseMedia: ...
    def _browse_group(self, group: Group) -> BrowseMedia: ...
    def _browse_card(self, card: Card) -> BrowseMedia: ...
    def _browse_chapter(self, card_id: str, chapter_key: str, chapter: Chapter) -> BrowseMedia: ...
    def _card_node(self, card: Card) -> BrowseMedia: ...
    def _group_node(self, group: Group) -> BrowseMedia: ...
    def _chapter_node(self, card_id: str, chapter_key: str, chapter: Chapter) -> BrowseMedia: ...
    def _track_node(self, card_id: str, chapter_key: str, track_key: str, track: Track) -> BrowseMedia: ...
    async def _async_run(self, func: Callable[..., Awaitable[Any]], /, *args: Any) -> None: ...

def _build_uri(card_id: str, chapter_key: str | None = None, track_key: str | None = None) -> str: ...
def _build_group_uri(group_id: str) -> str: ...
def _parse_card_uri(media_id: str) -> tuple[str, str | None, str | None]: ...
def _parse_group_uri(media_id: str) -> str: ...
