from _typeshed import Incomplete

DOMAIN: str
LOGGER: Incomplete
CONF_REFRESH_TOKEN: str
CONF_USER_UUID: str
SENSOR_BATTERY: str
SENSOR_DOOR: str
SENSOR_GARAGE_DOOR: str
SENSOR_LEAK: str
SENSOR_MISSING: str
SENSOR_MOLD: str
SENSOR_SAFE: str
SENSOR_SLIDING: str
SENSOR_SMOKE_CO: str
SENSOR_TEMPERATURE: str
SENSOR_WINDOW_HINGED: str
