from .const import CLIENT_ID as CLIENT_ID, DOMAIN as DOMAIN, LOGGER as LOGGER
from .coordinator import TeslemetryEnergyHistoryCoordinator as TeslemetryEnergyHistoryCoordinator, TeslemetryEnergySiteInfoCoordinator as TeslemetryEnergySiteInfoCoordinator, TeslemetryEnergySiteLiveCoordinator as TeslemetryEnergySiteLiveCoordinator, TeslemetryMetadataCoordinator as TeslemetryMetadataCoordinator, TeslemetryVehicleDataCoordinator as TeslemetryVehicleDataCoordinator
from .helpers import async_update_device_sw_version as async_update_device_sw_version, flatten as flatten
from .models import TeslemetryData as TeslemetryData, TeslemetryEnergyData as TeslemetryEnergyData, TeslemetryVehicleData as TeslemetryVehicleData
from .services import async_setup_services as async_setup_services
from _typeshed import Incomplete
from collections.abc import Callable as Callable
from homeassistant.components.application_credentials import ClientCredential as ClientCredential, async_import_client_credential as async_import_client_credential
from homeassistant.config_entries import ConfigEntry as ConfigEntry
from homeassistant.const import CONF_ACCESS_TOKEN as CONF_ACCESS_TOKEN, Platform as Platform
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.exceptions import ConfigEntryAuthFailed as ConfigEntryAuthFailed, ConfigEntryNotReady as ConfigEntryNotReady
from homeassistant.helpers import device_registry as dr
from homeassistant.helpers.aiohttp_client import async_get_clientsession as async_get_clientsession
from homeassistant.helpers.config_entry_oauth2_flow import ImplementationUnavailableError as ImplementationUnavailableError, OAuth2Session as OAuth2Session, async_get_config_entry_implementation as async_get_config_entry_implementation
from homeassistant.helpers.device_registry import DeviceInfo as DeviceInfo
from homeassistant.helpers.typing import ConfigType as ConfigType
from typing import Any, Final

PLATFORMS: Final[Incomplete]
type TeslemetryConfigEntry = ConfigEntry[TeslemetryData]
CONFIG_SCHEMA: Incomplete

async def async_setup(hass: HomeAssistant, config: ConfigType) -> bool: ...
async def _get_access_token(oauth_session: OAuth2Session) -> str: ...
def _get_subscribed_ids_from_metadata(data: dict[str, Any]) -> tuple[set[str], set[str]]: ...
def _setup_dynamic_discovery(hass: HomeAssistant, entry: TeslemetryConfigEntry, metadata_coordinator: TeslemetryMetadataCoordinator, known_vins: set[str], known_site_ids: set[str]) -> None: ...
async def async_setup_entry(hass: HomeAssistant, entry: TeslemetryConfigEntry) -> bool: ...
async def async_unload_entry(hass: HomeAssistant, entry: TeslemetryConfigEntry) -> bool: ...
async def async_migrate_entry(hass: HomeAssistant, config_entry: TeslemetryConfigEntry) -> bool: ...
def create_handle_vehicle_stream(vin: str, coordinator: TeslemetryVehicleDataCoordinator) -> Callable[[dict[str, Any]], None]: ...
def async_setup_energy_device(hass: HomeAssistant, entry: TeslemetryConfigEntry, energysite: TeslemetryEnergyData, device_registry: dr.DeviceRegistry) -> None: ...
async def async_setup_stream(hass: HomeAssistant, entry: TeslemetryConfigEntry, vehicle: TeslemetryVehicleData) -> None: ...
def create_vehicle_streaming_listener(hass: HomeAssistant, vin: str) -> Callable[[str | None], None]: ...
def create_vehicle_polling_listener(hass: HomeAssistant, vin: str, coordinator: TeslemetryVehicleDataCoordinator) -> Callable[[], None]: ...
def create_energy_info_listener(hass: HomeAssistant, site_id: int, coordinator: TeslemetryEnergySiteInfoCoordinator) -> Callable[[], None]: ...
