from .const import BLE_DISCONNECT_TIMEOUT as BLE_DISCONNECT_TIMEOUT, CLIENT_ID as CLIENT_ID, CONF_VIN as CONF_VIN, DOMAIN as DOMAIN, ISSUE_GATEWAY_NOT_FOUND as ISSUE_GATEWAY_NOT_FOUND, LOGGER as LOGGER, POWERWALL_KEY_FILE as POWERWALL_KEY_FILE, RSA_PARENT_KEY as RSA_PARENT_KEY, SUBENTRY_TYPE_ENERGY_SITE as SUBENTRY_TYPE_ENERGY_SITE, SUBENTRY_TYPE_VEHICLE as SUBENTRY_TYPE_VEHICLE, VEHICLE_ISSUE_LEARN_MORE as VEHICLE_ISSUE_LEARN_MORE
from .coordinator import TeslemetryEnergyHistoryCoordinator as TeslemetryEnergyHistoryCoordinator, TeslemetryEnergySiteInfoCoordinator as TeslemetryEnergySiteInfoCoordinator, TeslemetryEnergySiteLiveCoordinator as TeslemetryEnergySiteLiveCoordinator, TeslemetryMetadataCoordinator as TeslemetryMetadataCoordinator, TeslemetryVehicleDataCoordinator as TeslemetryVehicleDataCoordinator
from .helpers import async_get_ble_parent as async_get_ble_parent, async_update_device_sw_version as async_update_device_sw_version, create_powerwall_client as create_powerwall_client, flatten as flatten
from .models import TeslemetryData as TeslemetryData, TeslemetryEnergyData as TeslemetryEnergyData, TeslemetryVehicleData as TeslemetryVehicleData
from .services import async_setup_services as async_setup_services
from _typeshed import Incomplete
from aiopowerwall import PowerwallClient as PowerwallClient, PowerwallError
from collections.abc import Callable as Callable
from homeassistant.components.application_credentials import ClientCredential as ClientCredential, async_import_client_credential as async_import_client_credential
from homeassistant.components.bluetooth import async_ble_device_from_address as async_ble_device_from_address
from homeassistant.config_entries import ConfigEntry as ConfigEntry, ConfigEntryState as ConfigEntryState, ConfigSubentry as ConfigSubentry
from homeassistant.const import CONF_ACCESS_TOKEN as CONF_ACCESS_TOKEN, CONF_ADDRESS as CONF_ADDRESS, CONF_HOST as CONF_HOST, CONF_PASSWORD as CONF_PASSWORD, Platform as Platform
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.exceptions import ConfigEntryAuthFailed as ConfigEntryAuthFailed, ConfigEntryNotReady as ConfigEntryNotReady, OAuth2TokenRequestError as OAuth2TokenRequestError, OAuth2TokenRequestReauthError as OAuth2TokenRequestReauthError
from homeassistant.helpers import device_registry as dr
from homeassistant.helpers.aiohttp_client import async_get_clientsession as async_get_clientsession
from homeassistant.helpers.config_entry_oauth2_flow import OAuth2Session as OAuth2Session, async_get_config_entry_implementation as async_get_config_entry_implementation
from homeassistant.helpers.device_registry import DeviceInfo as DeviceInfo
from homeassistant.helpers.typing import ConfigType as ConfigType
from homeassistant.helpers.update_coordinator import UpdateFailed as UpdateFailed
from tesla_fleet_api.const import Scope
from tesla_fleet_api.router import VehicleRouter
from tesla_fleet_api.tesla import EnergySiteRouter
from tesla_fleet_api.teslemetry import EnergySite as EnergySite, Vehicle as Vehicle
from tesla_fleet_api.teslemetry.energysite import TeslemetryEnergySite
from teslemetry_stream import TeslemetryStream
from typing import Any, Final

PLATFORMS: Final[Incomplete]
type TeslemetryConfigEntry = ConfigEntry[TeslemetryData]
CONFIG_SCHEMA: Incomplete
STREAM_TOPICS: Final[Incomplete]

async def async_setup(hass: HomeAssistant, config: ConfigType) -> bool: ...
async def _get_access_token(oauth_session: OAuth2Session) -> str: ...
def _get_subscribed_ids_from_metadata(data: dict[str, Any]) -> tuple[set[str], set[str]]: ...
def _setup_dynamic_discovery(hass: HomeAssistant, entry: TeslemetryConfigEntry, metadata_coordinator: TeslemetryMetadataCoordinator, known_vins: set[str], known_site_ids: set[str]) -> None: ...
def _async_update_vehicle_repairs(hass: HomeAssistant, entry: TeslemetryConfigEntry, vins: set[str], vehicle_metadata: dict[str, Any]) -> None: ...
def _setup_vehicle_repairs(hass: HomeAssistant, entry: TeslemetryConfigEntry, metadata_coordinator: TeslemetryMetadataCoordinator, vins: set[str], vehicle_metadata: dict[str, Any]) -> None: ...
def _ble_address_for_vin(entry: TeslemetryConfigEntry, vin: str) -> str | None: ...

_BLE_KEY_ERRORS: Final[Incomplete]

async def _async_resolve_vehicle_api(hass: HomeAssistant, entry: TeslemetryConfigEntry, vin: str, cloud_vehicle: Vehicle) -> Vehicle | VehicleRouter: ...
def _find_energy_subentry_id(entry: TeslemetryConfigEntry, site_id: int) -> str | None: ...
def _remove_stale_subentries(hass: HomeAssistant, entry: TeslemetryConfigEntry, subentry_type: str, current_subentry_ids: set[str]) -> None: ...
def _prune_energy_subentries(hass: HomeAssistant, entry: TeslemetryConfigEntry, scopes: list[Scope], products: list[dict[str, Any]]) -> None: ...
async def _async_get_rsa_key_pem(hass: HomeAssistant) -> bytes: ...

_LOCAL_CONTROL_ERRORS: Final[Incomplete]

async def _async_resolve_local_control(hass: HomeAssistant, entry: TeslemetryConfigEntry, battery: bool, site_id: int, cloud_energy_site: TeslemetryEnergySite) -> tuple[bool, str | None, EnergySite | EnergySiteRouter]: ...
def _gateway_issue_id(site_id: int) -> str: ...
async def _async_resolve_energy_site_api(hass: HomeAssistant, entry: TeslemetryConfigEntry, subentry_id: str, cloud_energy_site: TeslemetryEnergySite) -> EnergySite | EnergySiteRouter: ...
async def _async_rediscover_gateway(hass: HomeAssistant, entry: TeslemetryConfigEntry, subentry: ConfigSubentry, stale_client: PowerwallClient, cloud_energy_site: TeslemetryEnergySite, key_pem: bytes, error: PowerwallError) -> PowerwallClient: ...
async def async_setup_entry(hass: HomeAssistant, entry: TeslemetryConfigEntry) -> bool: ...
def _setup_subentry_change_reload(hass: HomeAssistant, entry: TeslemetryConfigEntry) -> None: ...
def create_handle_energy_stream_connection(energysites: list[TeslemetryEnergyData]) -> Callable[[bool], None]: ...
async def _async_setup_energy_site(hass: HomeAssistant, entry: TeslemetryConfigEntry, stream: TeslemetryStream, energy_site: EnergySite, product: dict[str, Any], site_id: int, powerwall: Any) -> tuple[TeslemetryEnergySiteLiveCoordinator | None, TeslemetryEnergySiteInfoCoordinator, TeslemetryEnergyHistoryCoordinator | None]: ...
async def _async_refresh_energy_site(energysite: TeslemetryEnergyData) -> None: ...
async def async_unload_entry(hass: HomeAssistant, entry: TeslemetryConfigEntry) -> bool: ...
async def async_migrate_entry(hass: HomeAssistant, config_entry: TeslemetryConfigEntry) -> bool: ...
def create_handle_vehicle_stream(vin: str, coordinator: TeslemetryVehicleDataCoordinator) -> Callable[[dict[str, Any]], None]: ...
def async_setup_energy_device(hass: HomeAssistant, entry: TeslemetryConfigEntry, energysite: TeslemetryEnergyData, device_registry: dr.DeviceRegistry) -> None: ...
async def async_setup_stream(hass: HomeAssistant, entry: TeslemetryConfigEntry, vehicle: TeslemetryVehicleData) -> None: ...
def create_vehicle_streaming_listener(hass: HomeAssistant, vin: str, config_entry_id: str) -> Callable[[str | None], None]: ...
def create_energy_info_listener(hass: HomeAssistant, site_id: int, config_entry_id: str, coordinator: TeslemetryEnergySiteInfoCoordinator) -> Callable[[], None]: ...
