from . import TeslemetryConfigEntry as TeslemetryConfigEntry
from .entity import TeslemetryEnergyInfoEntity as TeslemetryEnergyInfoEntity
from _typeshed import Incomplete
from datetime import datetime
from homeassistant.components.calendar import CalendarEntity as CalendarEntity, CalendarEvent as CalendarEvent
from homeassistant.core import HomeAssistant as HomeAssistant
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback as AddConfigEntryEntitiesCallback
from typing import Any

PARALLEL_UPDATES: int

async def async_setup_entry(hass: HomeAssistant, entry: TeslemetryConfigEntry, async_add_entities: AddConfigEntryEntitiesCallback) -> None: ...
def _is_day_in_range(day_of_week: int, from_day: int, to_day: int) -> bool: ...
def _parse_period_times(period_def: dict[str, Any], base_day: datetime) -> tuple[datetime, datetime] | None: ...
def _build_event(key_base: str, season_name: str, period_name: str, price: float | None, start_time: datetime, end_time: datetime) -> CalendarEvent: ...

class TeslemetryTariffSchedule(TeslemetryEnergyInfoEntity, CalendarEntity):
    key_base: str
    seasons: dict[str, dict[str, Any]]
    charges: dict[str, dict[str, Any]]
    def __init__(self, data: Any, key_base: str) -> None: ...
    @property
    def event(self) -> CalendarEvent | None: ...
    async def async_get_events(self, hass: HomeAssistant, start_date: datetime, end_date: datetime) -> list[CalendarEvent]: ...
    def _get_current_season(self, date_to_check: datetime) -> str | None: ...
    def _get_price_for_period(self, season_name: str, period_name: str) -> float | None: ...
    _attr_available: Incomplete
    def _async_update_attrs(self) -> None: ...
