repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: poetry run ruff format
        language: system
        types: [python]
        require_serial: true
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        require_serial: true
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        require_serial: true
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
        require_serial: true
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        require_serial: true
      - id: codespell
        name: codespell
        entry: poetry run codespell --write-changes
        language: system
        pass_filenames: false
        always_run: true
