from _typeshed import Incomplete
from typing import Final

DOMAIN: str
CONF_ADAPTER: str
CONF_DETAILS: str
CONF_PASSIVE: str
SOURCE_LOCAL: Final[str]
DATA_MANAGER: Final[str]
UNAVAILABLE_TRACK_SECONDS: Final[Incomplete]
START_TIMEOUT: int
FALLBACK_MAXIMUM_STALE_ADVERTISEMENT_SECONDS: Final[Incomplete]
CONNECTABLE_FALLBACK_MAXIMUM_STALE_ADVERTISEMENT_SECONDS: Final[int]
SCANNER_WATCHDOG_TIMEOUT: Final[int]
SCANNER_WATCHDOG_INTERVAL: Final[Incomplete]
LINUX_FIRMWARE_LOAD_FALLBACK_SECONDS: int
BLUETOOTH_DISCOVERY_COOLDOWN_SECONDS: int
