from homeassistant.const import ATTR_ATTRIBUTION as ATTR_ATTRIBUTION, ATTR_SUPPORTED_FEATURES as ATTR_SUPPORTED_FEATURES
from homeassistant.helpers.json import JSONEncoder as JSONEncoder
from typing import Any, Final

DATA_INSTANCE: str
SQLITE_URL_PREFIX: str
DOMAIN: str
CONF_DB_INTEGRITY_CHECK: str
MAX_QUEUE_BACKLOG: int
MAX_ROWS_TO_PURGE: int
DB_WORKER_PREFIX: str
JSON_DUMP: Final[Any]
ALL_DOMAIN_EXCLUDE_ATTRS: Any
