from . import SolarlogConfigEntry as SolarlogConfigEntry
from .const import CONF_HAS_PWD as CONF_HAS_PWD, DEFAULT_HOST as DEFAULT_HOST, DEFAULT_NAME as DEFAULT_NAME, DOMAIN as DOMAIN
from _typeshed import Incomplete
from collections.abc import Mapping
from homeassistant.config_entries import ConfigFlow as ConfigFlow, ConfigFlowResult as ConfigFlowResult
from homeassistant.const import CONF_HOST as CONF_HOST, CONF_NAME as CONF_NAME, CONF_PASSWORD as CONF_PASSWORD
from homeassistant.util import slugify as slugify
from typing import Any

_LOGGER: Incomplete

class SolarLogConfigFlow(ConfigFlow, domain=DOMAIN):
    _entry: SolarlogConfigEntry | None
    VERSION: int
    MINOR_VERSION: int
    _errors: Incomplete
    _user_input: Incomplete
    def __init__(self) -> None: ...
    def _parse_url(self, host: str) -> str: ...
    async def _test_connection(self, host: str) -> bool: ...
    async def _test_extended_data(self, host: str, pwd: str = '') -> bool: ...
    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_password(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_reconfigure(self, entry_data: Mapping[str, Any]) -> ConfigFlowResult: ...
    async def async_step_reconfigure_confirm(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_reauth(self, entry_data: Mapping[str, Any]) -> ConfigFlowResult: ...
    async def async_step_reauth_confirm(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
