from .base import BaseTemplateExtension as BaseTemplateExtension, TemplateFunction as TemplateFunction
from homeassistant.helpers.template import TemplateEnvironment as TemplateEnvironment

class CryptoExtension(BaseTemplateExtension):
    def __init__(self, environment: TemplateEnvironment) -> None: ...
    @staticmethod
    def md5(value: str) -> str: ...
    @staticmethod
    def sha1(value: str) -> str: ...
    @staticmethod
    def sha256(value: str) -> str: ...
    @staticmethod
    def sha512(value: str) -> str: ...
