from .base import BaseTemplateExtension as BaseTemplateExtension, TemplateFunction as TemplateFunction
from collections.abc import Iterable
from homeassistant.helpers.template import TemplateEnvironment as TemplateEnvironment
from typing import Any

class LabelExtension(BaseTemplateExtension):
    def __init__(self, environment: TemplateEnvironment) -> None: ...
    def labels(self, lookup_value: Any = None) -> Iterable[str | None]: ...
    def label_id(self, lookup_value: Any) -> str | None: ...
    def label_name(self, lookup_value: str) -> str | None: ...
    def label_description(self, lookup_value: str) -> str | None: ...
    def _label_id_or_name(self, label_id_or_name: str) -> str | None: ...
    def label_areas(self, label_id_or_name: str) -> Iterable[str]: ...
    def label_devices(self, label_id_or_name: str) -> Iterable[str]: ...
    def label_entities(self, label_id_or_name: str) -> Iterable[str]: ...
