from .const import CONF_DSMR_VERSION as CONF_DSMR_VERSION, DATA_TASK as DATA_TASK, DOMAIN as DOMAIN, PLATFORMS as PLATFORMS
from homeassistant.config_entries import ConfigEntry as ConfigEntry
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.helpers import entity_registry as er
from typing import Any

async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool: ...
async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool: ...
async def async_update_options(hass: HomeAssistant, entry: ConfigEntry) -> None: ...
def async_migrate_entity_entry(config_entry: ConfigEntry, entity_entry: er.RegistryEntry) -> dict[str, Any] | None: ...
