from homeassistant import runner as runner
from homeassistant.auth import auth_manager_from_config as auth_manager_from_config
from homeassistant.config import get_default_config_dir as get_default_config_dir
from homeassistant.core import HomeAssistant as HomeAssistant
from typing import Any

def run(args: Any) -> None: ...
async def run_command(args: Any) -> None: ...
async def list_users(hass: Any, provider: Any, args: Any) -> None: ...
async def add_user(hass: Any, provider: Any, args: Any) -> None: ...
async def validate_login(hass: Any, provider: Any, args: Any) -> None: ...
async def change_password(hass: Any, provider: Any, args: Any) -> None: ...
