from .const import LOGGER as LOGGER, SENSIBO_ERRORS as SENSIBO_ERRORS, TIMEOUT as TIMEOUT
from homeassistant.core import HomeAssistant as HomeAssistant
from homeassistant.helpers.aiohttp_client import async_get_clientsession as async_get_clientsession

async def async_validate_api(hass: HomeAssistant, api_key: str) -> str: ...

class NoDevicesError(Exception): ...
class NoUsernameError(Exception): ...
