from _typeshed import Incomplete
from enum import StrEnum

DOMAIN: str
LOGGER: Incomplete
DEFAULT_CONVERSATION_NAME: str
DEFAULT_AI_TASK_NAME: str
CONF_RECOMMENDED: str
CONF_PROMPT: str
CONF_CHAT_MODEL: str
CONF_CODE_EXECUTION: str
CONF_MAX_TOKENS: str
CONF_PROMPT_CACHING: str
CONF_THINKING_BUDGET: str
CONF_THINKING_EFFORT: str
CONF_TOOL_SEARCH: str
CONF_WEB_SEARCH: str
CONF_WEB_SEARCH_USER_LOCATION: str
CONF_WEB_SEARCH_MAX_USES: str
CONF_WEB_SEARCH_CITY: str
CONF_WEB_SEARCH_REGION: str
CONF_WEB_SEARCH_COUNTRY: str
CONF_WEB_SEARCH_TIMEZONE: str

class PromptCaching(StrEnum):
    OFF = 'off'
    PROMPT = 'prompt'
    AUTOMATIC = 'automatic'

MIN_THINKING_BUDGET: int
DEFAULT: Incomplete
TOOL_SEARCH_UNSUPPORTED_MODELS: Incomplete
