from _typeshed import Incomplete

DOMAIN: str
LOGGER: Incomplete
SENSOR_TYPE_NEXT_PICKUP: str
CONF_CALENDAR_TITLE: str
CALENDAR_TITLE_STATUS: str
CALENDAR_TITLE_ROTATING: str
CALENDAR_TITLE_NONE: str
CALENDAR_TITLE_OPTIONS: Incomplete
