from .const import DOMAIN as DOMAIN, LOGGER as LOGGER
from collections.abc import Callable as Callable
from homeassistant import config_entries as config_entries
from homeassistant.const import CONF_API_KEY as CONF_API_KEY
from homeassistant.data_entry_flow import AbortFlow as AbortFlow, FlowResult as FlowResult, FlowResultType as FlowResultType
from homeassistant.helpers.issue_registry import IssueSeverity as IssueSeverity, async_create_issue as async_create_issue
from typing import Any

class ConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
    VERSION: int
    async def _create_entry(self, api_key: str, *, on_failure: Callable[[str], FlowResult]) -> FlowResult: ...
    def _import_issue(self, error_type: str) -> FlowResult: ...
    def _deprecated_yaml_issue(self) -> None: ...
    async def async_step_user(self, user_input: dict[str, Any] | None = ...) -> FlowResult: ...
    def _show_form(self, error_type: str | None = ...) -> FlowResult: ...
    async def async_step_import(self, import_data: dict[str, Any]) -> FlowResult: ...
