from _typeshed import Incomplete

LOGGER: Incomplete
ALLOWED_WATERING_TIME: Incomplete
CONF_WATERING_TIME: str
DOMAIN: str
DEFAULT_WATERING_TIME: Incomplete
MANUFACTURER: str
SCAN_INTERVAL: Incomplete
SIGNAL_UPDATE_HYDRAWISE: str
