from .const import PLATFORMS as PLATFORMS
from .coordinator import PVOutputDataUpdateCoordinator as PVOutputDataUpdateCoordinator, PvOutputConfigEntry as PvOutputConfigEntry
from homeassistant.core import HomeAssistant as HomeAssistant

async def async_setup_entry(hass: HomeAssistant, entry: PvOutputConfigEntry) -> bool: ...
async def async_unload_entry(hass: HomeAssistant, entry: PvOutputConfigEntry) -> bool: ...
