from _typeshed import Incomplete
from collections.abc import Iterable
from homeassistant.const import ATTR_LATITUDE as ATTR_LATITUDE, ATTR_LONGITUDE as ATTR_LONGITUDE
from homeassistant.core import HomeAssistant as HomeAssistant, State as State

_LOGGER: Incomplete

def has_location(state: State) -> bool: ...
def closest(latitude: float, longitude: float, states: Iterable[State]) -> State | None: ...
def find_coordinates(hass: HomeAssistant, name: str, recursion_history: list | None = None) -> str | None: ...
def resolve_zone(hass: HomeAssistant, zone_name: str) -> str | None: ...
def _get_location_from_attributes(entity_state: State) -> str: ...
