from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback

def async_migration_in_progress(hass: HomeAssistant) -> bool: ...
def async_initialize_recorder(hass: HomeAssistant) -> None: ...
async def async_wait_recorder(hass: HomeAssistant) -> bool: ...
