from _typeshed import Incomplete

DOMAIN: str
TITLE: str
CONF_SERVICE_ACCOUNT_INFO: str
CONF_KEY_FILE: str
DEFAULT_LANG: str
CONF_GENDER: str
CONF_VOICE: str
CONF_ENCODING: str
CONF_SPEED: str
CONF_PITCH: str
CONF_GAIN: str
CONF_PROFILES: str
CONF_TEXT_TYPE: str
DEFAULT_SPEED: float
DEFAULT_PITCH: int
DEFAULT_GAIN: int
CONF_STT_MODEL: str
DEFAULT_STT_MODEL: str
SUPPORTED_STT_MODELS: Incomplete
STT_LANGUAGES: Incomplete
