from _typeshed import Incomplete

DOMAIN: str
LOGGER: Incomplete
CONF_DECLINATION: str
CONF_AZIMUTH: str
CONF_MODULES_POWER: str
CONF_DAMPING: str
CONF_DAMPING_MORNING: str
CONF_DAMPING_EVENING: str
CONF_INVERTER_SIZE: str
DEFAULT_DECLINATION: int
DEFAULT_AZIMUTH: int
DEFAULT_MODULES_POWER: int
DEFAULT_DAMPING: float
MAX_PLANES: int
SUBENTRY_TYPE_PLANE: str
