from .const import BINSENSOR_PORTS as BINSENSOR_PORTS, CONF_CLIMATES as CONF_CLIMATES, CONF_CONNECTIONS as CONF_CONNECTIONS, CONF_DIMMABLE as CONF_DIMMABLE, CONF_DIM_MODE as CONF_DIM_MODE, CONF_LOCKABLE as CONF_LOCKABLE, CONF_MAX_TEMP as CONF_MAX_TEMP, CONF_MIN_TEMP as CONF_MIN_TEMP, CONF_MOTOR as CONF_MOTOR, CONF_OUTPUT as CONF_OUTPUT, CONF_OUTPUTS as CONF_OUTPUTS, CONF_REGISTER as CONF_REGISTER, CONF_REVERSE_TIME as CONF_REVERSE_TIME, CONF_SCENES as CONF_SCENES, CONF_SETPOINT as CONF_SETPOINT, CONF_SK_NUM_TRIES as CONF_SK_NUM_TRIES, CONF_TRANSITION as CONF_TRANSITION, DIM_MODES as DIM_MODES, DOMAIN as DOMAIN, KEYS as KEYS, LED_PORTS as LED_PORTS, LOGICOP_PORTS as LOGICOP_PORTS, MOTOR_PORTS as MOTOR_PORTS, MOTOR_REVERSE_TIME as MOTOR_REVERSE_TIME, OUTPUT_PORTS as OUTPUT_PORTS, RELAY_PORTS as RELAY_PORTS, S0_INPUTS as S0_INPUTS, SETPOINTS as SETPOINTS, THRESHOLDS as THRESHOLDS, VARIABLES as VARIABLES, VAR_UNITS as VAR_UNITS
from .helpers import has_unique_host_names as has_unique_host_names, is_address as is_address
from _typeshed import Incomplete
from homeassistant.components.climate import DEFAULT_MAX_TEMP as DEFAULT_MAX_TEMP, DEFAULT_MIN_TEMP as DEFAULT_MIN_TEMP
from homeassistant.const import CONF_ADDRESS as CONF_ADDRESS, CONF_BINARY_SENSORS as CONF_BINARY_SENSORS, CONF_COVERS as CONF_COVERS, CONF_HOST as CONF_HOST, CONF_LIGHTS as CONF_LIGHTS, CONF_NAME as CONF_NAME, CONF_PASSWORD as CONF_PASSWORD, CONF_PORT as CONF_PORT, CONF_SCENE as CONF_SCENE, CONF_SENSORS as CONF_SENSORS, CONF_SOURCE as CONF_SOURCE, CONF_SWITCHES as CONF_SWITCHES, CONF_UNIT_OF_MEASUREMENT as CONF_UNIT_OF_MEASUREMENT, CONF_USERNAME as CONF_USERNAME, UnitOfTemperature as UnitOfTemperature

DOMAIN_DATA_BINARY_SENSOR: Incomplete
DOMAIN_DATA_CLIMATE: Incomplete
DOMAIN_DATA_COVER: Incomplete
DOMAIN_DATA_LIGHT: Incomplete
DOMAIN_DATA_SCENE: Incomplete
DOMAIN_DATA_SENSOR: Incomplete
DOMAIN_DATA_SWITCH: Incomplete
DOMAIN_DATA_BASE: Incomplete
BINARY_SENSORS_SCHEMA: Incomplete
CLIMATES_SCHEMA: Incomplete
COVERS_SCHEMA: Incomplete
LIGHTS_SCHEMA: Incomplete
SCENES_SCHEMA: Incomplete
SENSORS_SCHEMA: Incomplete
SWITCHES_SCHEMA: Incomplete
CONNECTION_SCHEMA: Incomplete
CONFIG_SCHEMA: Incomplete
