from _typeshed import Incomplete

ADDON_SLUG: str
CONF_INTEGRATION_CREATED_ADDON: str
CONF_USE_ADDON: str
DOMAIN: str
LOGGER: Incomplete
ID_TYPE_DEVICE_ID: str
ID_TYPE_SERIAL: str
FEATUREMAP_ATTRIBUTE_ID: int
ATTR_CREDENTIAL_RULE: str
ATTR_MAX_CREDENTIALS_PER_USER: str
ATTR_MAX_PIN_USERS: str
ATTR_MAX_RFID_USERS: str
ATTR_MAX_USERS: str
ATTR_SUPPORTS_USER_MGMT: str
ATTR_USER_INDEX: str
ATTR_USER_NAME: str
ATTR_USER_STATUS: str
ATTR_USER_TYPE: str
CLEAR_ALL_INDEX: int
LOCK_TIMED_REQUEST_TIMEOUT_MS: int
ATTR_CREDENTIAL_DATA: str
ATTR_CREDENTIAL_INDEX: str
ATTR_CREDENTIAL_TYPE: str
CRED_TYPE_FACE: str
CRED_TYPE_FINGERPRINT: str
CRED_TYPE_FINGER_VEIN: str
CRED_TYPE_PIN: str
CRED_TYPE_RFID: str
_UserStatus: Incomplete
USER_STATUS_MAP: dict[int, str]
USER_STATUS_REVERSE_MAP: dict[str, int]
_UserType: Incomplete
USER_TYPE_MAP: dict[int, str]
USER_TYPE_REVERSE_MAP: dict[str, int]
_CredentialType: Incomplete
CREDENTIAL_TYPE_MAP: dict[int, str]
_CredentialRule: Incomplete
CREDENTIAL_RULE_MAP: dict[int, str]
CREDENTIAL_RULE_REVERSE_MAP: dict[str, int]
CREDENTIAL_TYPE_REVERSE_MAP: dict[str, int]
SERVICE_CREDENTIAL_TYPES: Incomplete
