from .const import ATTR_CREDENTIAL_DATA as ATTR_CREDENTIAL_DATA, ATTR_CREDENTIAL_INDEX as ATTR_CREDENTIAL_INDEX, ATTR_CREDENTIAL_RULE as ATTR_CREDENTIAL_RULE, ATTR_CREDENTIAL_TYPE as ATTR_CREDENTIAL_TYPE, ATTR_USER_INDEX as ATTR_USER_INDEX, ATTR_USER_NAME as ATTR_USER_NAME, ATTR_USER_STATUS as ATTR_USER_STATUS, ATTR_USER_TYPE as ATTR_USER_TYPE, CLEAR_ALL_INDEX as CLEAR_ALL_INDEX, CREDENTIAL_RULE_REVERSE_MAP as CREDENTIAL_RULE_REVERSE_MAP, CREDENTIAL_TYPE_REVERSE_MAP as CREDENTIAL_TYPE_REVERSE_MAP, DOMAIN as DOMAIN, SERVICE_CREDENTIAL_TYPES as SERVICE_CREDENTIAL_TYPES, USER_TYPE_REVERSE_MAP as USER_TYPE_REVERSE_MAP
from homeassistant.core import HomeAssistant as HomeAssistant, SupportsResponse as SupportsResponse, callback as callback
from homeassistant.helpers import service as service

ATTR_DURATION: str
ATTR_EMERGENCY_BOOST: str
ATTR_TEMPORARY_SETPOINT: str
SERVICE_WATER_HEATER_BOOST: str

@callback
def async_setup_services(hass: HomeAssistant) -> None: ...
