name: "Common steps to install and cache dependencies"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        version: "0.4.22"

    - name: Set up Python
      shell: bash
      run: |
        uv python install
        echo "PYTHON_VERSION=$(uv run python -c 'import platform; print(platform.python_version())')" >> "$GITHUB_ENV"

    - name: Install dependencies with uv
      shell: bash
      run: uv sync
