import psutil_home_assistant as ha_psutil
from .const import CPU_SENSOR_PREFIXES as CPU_SENSOR_PREFIXES
from _typeshed import Incomplete
from homeassistant.core import HomeAssistant as HomeAssistant
from psutil._ntuples import sfan as sfan, shwtemp as shwtemp
from typing import Any

_LOGGER: Incomplete
SKIP_DISK_TYPES: Incomplete

def get_all_disk_mounts(hass: HomeAssistant, psutil_wrapper: ha_psutil.PsutilWrapper) -> set[str]: ...
def get_all_network_interfaces(hass: HomeAssistant, psutil_wrapper: ha_psutil.PsutilWrapper) -> set[str]: ...
def get_all_running_processes(hass: HomeAssistant) -> set[str]: ...
def read_cpu_temperature(temps: dict[str, list[shwtemp]]) -> float | None: ...
def read_fan_speed(fans: dict[str, list[sfan]]) -> dict[str, int]: ...
def parse_pressure_file(file_path: str) -> dict[str, dict[str, float | int]] | None: ...
def get_all_pressure_info() -> dict[str, Any]: ...
