from .const import CPU_SENSOR_PREFIXES as CPU_SENSOR_PREFIXES
from _typeshed import Incomplete
from psutil._common import shwtemp as shwtemp

_LOGGER: Incomplete
SKIP_DISK_TYPES: Incomplete

def get_all_disk_mounts() -> set[str]: ...
def get_all_network_interfaces() -> set[str]: ...
def get_all_running_processes() -> set[str]: ...
def read_cpu_temperature(temps: dict[str, list[shwtemp]] | None = None) -> float | None: ...
