from _typeshed import Incomplete
from enum import IntEnum
from pymiele import MieleEnum

DOMAIN: str
MANUFACTURER: str
ACTIONS: str
POWER_ON: str
POWER_OFF: str
PROCESS_ACTION: str
PROGRAM_ID: str
VENTILATION_STEP: str
TARGET_TEMPERATURE: str
AMBIENT_LIGHT: str
LIGHT: str
LIGHT_ON: int
LIGHT_OFF: int
DISABLED_TEMP_ENTITIES: Incomplete

class MieleAppliance(IntEnum):
    WASHING_MACHINE = 1
    TUMBLE_DRYER = 2
    WASHING_MACHINE_SEMI_PROFESSIONAL = 3
    TUMBLE_DRYER_SEMI_PROFESSIONAL = 4
    WASHING_MACHINE_PROFESSIONAL = 5
    DRYER_PROFESSIONAL = 6
    DISHWASHER = 7
    DISHWASHER_SEMI_PROFESSIONAL = 8
    DISHWASHER_PROFESSIONAL = 9
    OVEN = 12
    OVEN_MICROWAVE = 13
    HOB_HIGHLIGHT = 14
    STEAM_OVEN = 15
    MICROWAVE = 16
    COFFEE_SYSTEM = 17
    HOOD = 18
    FRIDGE = 19
    FREEZER = 20
    FRIDGE_FREEZER = 21
    ROBOT_VACUUM_CLEANER = 23
    WASHER_DRYER = 24
    DISH_WARMER = 25
    HOB_INDUCTION = 27
    STEAM_OVEN_COMBI = 31
    WINE_CABINET = 32
    WINE_CONDITIONING_UNIT = 33
    WINE_STORAGE_CONDITIONING_UNIT = 34
    STEAM_OVEN_MICRO = 45
    DIALOG_OVEN = 67
    WINE_CABINET_FREEZER = 68
    STEAM_OVEN_MK2 = 73
    HOB_INDUCT_EXTR = 74

DEVICE_TYPE_TAGS: Incomplete

class StateStatus(MieleEnum, missing_to_none=True):
    reserved: int
    off: int
    on: int
    programmed: int
    waiting_to_start: int
    in_use: int
    pause: int
    program_ended: int
    failure: int
    program_interrupted: int
    idle: int
    rinse_hold: int
    service: int
    superfreezing: int
    supercooling: int
    superheating: int
    supercooling_superfreezing: int
    autocleaning: int
    not_connected: int

class MieleActions(IntEnum):
    START = 1
    STOP = 2
    PAUSE = 3
    START_SUPERFREEZE = 4
    STOP_SUPERFREEZE = 5
    START_SUPERCOOL = 6
    STOP_SUPERCOOL = 7

PROCESS_ACTIONS: Incomplete

class ProgramPhaseWashingMachine(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    pre_wash: Incomplete
    soak: int
    main_wash: Incomplete
    rinse: Incomplete
    rinse_hold: int
    cleaning: int
    cooling_down: int
    drain: int
    spin: Incomplete
    anti_crease: Incomplete
    finished: Incomplete
    venting: int
    starch_stop: int
    freshen_up_and_moisten: int
    steam_smoothing: Incomplete
    hygiene: int
    drying: int
    disinfecting: int
    flex_load_active: int
    automatic_start: int

class ProgramPhaseTumbleDryer(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    program_running: int
    drying: int
    machine_iron: int
    hand_iron_2: int
    normal: int
    normal_plus: int
    cooling_down: int
    hand_iron_1: int
    anti_crease: int
    finished: int
    extra_dry: int
    hand_iron: int
    moisten: int
    thermo_spin: int
    timed_drying: int
    warm_air: int
    steam_smoothing: int
    comfort_cooling: int
    rinse_out_lint: int
    rinses: int
    smoothing: int
    slightly_dry: int
    safety_cooling: int

class ProgramPhaseWasherDryer(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    pre_wash: Incomplete
    soak: int
    main_wash: int
    rinse: int
    rinse_hold: int
    cleaning: int
    cooling_down: Incomplete
    drain: int
    spin: int
    anti_crease: Incomplete
    finished: Incomplete
    venting: int
    starch_stop: int
    freshen_up_and_moisten: int
    steam_smoothing: Incomplete
    hygiene: int
    drying: Incomplete
    disinfecting: int
    program_running: int
    machine_iron: int
    hand_iron_2: int
    normal: int
    normal_plus: int
    hand_iron_1: int
    extra_dry: int
    hand_iron: int
    moisten: int
    thermo_spin: int
    timed_drying: int
    warm_air: int
    comfort_cooling: int
    rinse_out_lint: int
    rinses: int
    smoothing: int
    slightly_dry: int
    safety_cooling: int

class ProgramPhaseDishwasher(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    reactivating: int
    pre_dishwash: Incomplete
    main_dishwash: int
    rinse: int
    interim_rinse: int
    final_rinse: int
    drying: int
    finished: int

class ProgramPhaseOven(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    heating_up: int
    process_running: int
    process_finished: int
    energy_save: int
    pre_heating: int

class ProgramPhaseWarmingDrawer(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    heating_up: int
    door_open: int
    keeping_warm: int
    cooling_down: int

class ProgramPhaseMicrowave(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    heating: int
    process_running: int
    process_finished: int
    energy_save: int

class ProgramPhaseCoffeeSystem(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    heating_up: int
    espresso: int
    hot_milk: int
    milk_foam: int
    dispensing: Incomplete
    pre_brewing: int
    grinding: int
    second_espresso: int
    second_pre_brewing: int
    second_grinding: int
    rinse: int

class ProgramPhaseRobotVacuumCleaner(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    vacuum_cleaning: int
    returning: int
    vacuum_cleaning_paused: int
    going_to_target_area: int
    wheel_lifted: int
    dirty_sensors: int
    dust_box_missing: int
    blocked_drive_wheels: int
    blocked_brushes: int
    motor_overload: int
    internal_fault: int
    blocked_front_wheel: int
    docked: Incomplete
    remote_controlled: int

class ProgramPhaseMicrowaveOvenCombo(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    steam_reduction: int
    process_running: int
    waiting_for_start: int
    heating_up_phase: int
    process_finished: int

class ProgramPhaseSteamOven(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    steam_reduction: int
    process_running: int
    waiting_for_start: int
    heating_up_phase: int
    process_finished: int

class ProgramPhaseSteamOvenCombi(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    heating_up: int
    process_running: Incomplete
    process_finished: Incomplete
    energy_save: int
    pre_heating: int
    steam_reduction: int
    waiting_for_start: int
    heating_up_phase: int

class ProgramPhaseSteamOvenMicro(MieleEnum, missing_to_none=True):
    not_running: Incomplete
    heating: int
    process_running: Incomplete
    process_finished: int
    energy_save: int
    steam_reduction: int
    waiting_for_start: int
    heating_up_phase: int

PROGRAM_PHASE: dict[int, type[MieleEnum]]

class StateProgramType(MieleEnum, missing_to_none=True):
    normal_operation_mode: int
    own_program: int
    automatic_program: int
    cleaning_care_program: int
    maintenance_program: int

class StateDryingStep(MieleEnum, missing_to_none=True):
    extra_dry: int
    normal_plus: int
    normal: int
    slightly_dry: int
    hand_iron_1: int
    hand_iron_2: int
    machine_iron: int
    smoothing: int

class WashingMachineProgramId(MieleEnum, missing_to_none=True):
    no_program: Incomplete
    cottons: Incomplete
    minimum_iron: int
    delicates: Incomplete
    woollens: Incomplete
    silks: Incomplete
    starch: int
    rinse: Incomplete
    drain_spin: Incomplete
    curtains: Incomplete
    shirts: Incomplete
    denim: Incomplete
    proofing: Incomplete
    sportswear: Incomplete
    automatic_plus: int
    outerwear: int
    pillows: int
    cool_air: int
    warm_air: int
    rinse_out_lint: int
    dark_garments: int
    separate_rinse_starch: int
    first_wash: Incomplete
    cottons_hygiene: int
    steam_care: int
    freshen_up: int
    trainers: Incomplete
    clean_machine: Incomplete
    down_duvets: Incomplete
    express_20: Incomplete
    down_filled_items: int
    cottons_eco: int
    quick_power_wash: Incomplete
    eco_40_60: Incomplete
    bed_linen: int
    easy_care: int
    dark_jeans: int
    outdoor_garments: int
    game_pieces: int
    stuffed_toys: int
    pre_ironing: int
    trainers_refresh: int
    smartmatic: int
    cottonrepair: int
    powerfresh: int

class DishWasherProgramId(MieleEnum, missing_to_none=True):
    no_program: Incomplete
    intensive: Incomplete
    maintenance: Incomplete
    eco: Incomplete
    automatic: Incomplete
    solar_save: Incomplete
    gentle: Incomplete
    extra_quiet: Incomplete
    hygiene: Incomplete
    quick_power_wash: Incomplete
    pasta_paela: int
    tall_items: Incomplete
    glasses_warm: int
    normal: int
    power_wash: Incomplete
    comfort_wash: int
    comfort_wash_plus: int
    rinse_salt: int

class TumbleDryerProgramId(MieleEnum, missing_to_none=True):
    no_program: Incomplete
    automatic_plus: int
    cottons: Incomplete
    minimum_iron: Incomplete
    woollens_handcare: Incomplete
    delicates: Incomplete
    warm_air: Incomplete
    cool_air: Incomplete
    express: Incomplete
    cottons_eco: Incomplete
    proofing: Incomplete
    denim: Incomplete
    shirts: Incomplete
    sportswear: Incomplete
    outerwear: Incomplete
    silks_handcare: Incomplete
    standard_pillows: Incomplete
    basket_program: Incomplete
    cottons_hygiene: int
    smoothing: Incomplete
    bed_linen: Incomplete
    eco: int
    gentle_smoothing: Incomplete
    gentle_denim: int
    steam_smoothing: int
    large_pillows: int

class OvenProgramId(MieleEnum, missing_to_none=True):
    no_program: Incomplete
    defrost: Incomplete
    eco_fan_heat: int
    auto_roast: int
    full_grill: int
    economy_grill: int
    fan_plus: int
    intensive_bake: int
    microwave: int
    conventional_heat: int
    top_heat: int
    fan_grill: int
    bottom_heat: int
    moisture_plus_auto_roast: Incomplete
    moisture_plus_fan_plus: Incomplete
    moisture_plus_intensive_bake: Incomplete
    moisture_plus_conventional_heat: Incomplete
    custom_program_1: int
    custom_program_2: int
    custom_program_3: int
    custom_program_4: int
    custom_program_5: int
    custom_program_6: int
    custom_program_7: int
    custom_program_8: int
    custom_program_9: int
    custom_program_10: int
    custom_program_11: int
    custom_program_12: int
    custom_program_13: int
    custom_program_14: int
    custom_program_15: int
    custom_program_16: int
    custom_program_17: int
    custom_program_18: int
    custom_program_19: int
    custom_program_20: int
    pyrolytic: int
    descale: int
    evaporate_water: int
    shabbat_program: int
    yom_tov: int
    drying: int
    heat_crockery: int
    low_temperature_cooking: int
    steam_cooking: int
    keeping_warm: int
    apple_sponge: int
    apple_pie: int
    sponge_base: int
    swiss_roll: int
    butter_cake: int
    marble_cake: int
    fruit_streusel_cake: int
    madeira_cake: int
    blueberry_muffins: int
    walnut_muffins: int
    baguettes: int
    flat_bread: int
    plaited_loaf: int
    seeded_loaf: int
    white_bread_baking_tin: int
    white_bread_on_tray: int
    duck: int
    chicken_whole: int
    chicken_thighs: int
    turkey_whole: int
    turkey_drumsticks: int
    veal_fillet_roast: int
    veal_fillet_low_temperature_cooking: int
    veal_knuckle: int
    saddle_of_veal_roast: int
    saddle_of_veal_low_temperature_cooking: int
    braised_veal: int
    leg_of_lamb: int
    saddle_of_lamb_roast: int
    saddle_of_lamb_low_temperature_cooking: int
    beef_fillet_roast: int
    beef_fillet_low_temperature_cooking: int
    braised_beef: int
    roast_beef_roast: int
    roast_beef_low_temperature_cooking: int
    pork_smoked_ribs_roast: int
    pork_smoked_ribs_low_temperature_cooking: int
    ham_roast: int
    pork_fillet_roast: int
    pork_fillet_low_temperature_cooking: int
    saddle_of_venison: int
    rabbit: int
    saddle_of_roebuck: int
    salmon_fillet: int
    potato_cheese_gratin: int
    trout: int
    carp: int
    salmon_trout: int
    springform_tin_15cm: int
    springform_tin_20cm: int
    springform_tin_25cm: int
    fruit_flan_puff_pastry: int
    fruit_flan_short_crust_pastry: int
    sachertorte: int
    chocolate_hazlenut_cake_one_large: int
    chocolate_hazlenut_cake_several_small: int
    stollen: int
    drop_cookies_1_tray: int
    drop_cookies_2_trays: int
    linzer_augen_1_tray: int
    linzer_augen_2_trays: int
    almond_macaroons_1_tray: int
    almond_macaroons_2_trays: int
    biscuits_short_crust_pastry_1_tray: int
    biscuits_short_crust_pastry_2_trays: int
    vanilla_biscuits_1_tray: int
    vanilla_biscuits_2_trays: int
    choux_buns: int
    spelt_bread: int
    walnut_bread: int
    mixed_rye_bread: int
    dark_mixed_grain_bread: int
    multigrain_rolls: int
    rye_rolls: int
    white_rolls: int
    tart_flambe: int
    pizza_yeast_dough_baking_tray: int
    pizza_yeast_dough_round_baking_tine: int
    pizza_oil_cheese_dough_baking_tray: int
    pizza_oil_cheese_dough_round_baking_tine: int
    quiche_lorraine: int
    savoury_flan_puff_pastry: int
    savoury_flan_short_crust_pastry: int
    osso_buco: int
    beef_hash: int
    pork_with_crackling: int
    potato_gratin: int
    cheese_souffle: int
    baiser_one_large: int
    baiser_several_small: int
    lemon_meringue_pie: int
    viennese_apple_strudel: int
    prove_15_min: int
    prove_30_min: int
    prove_45_min: int
    belgian_sponge_cake: int
    goose_unstuffed: int
    rack_of_lamb_with_vegetables: int
    yorkshire_pudding: int
    meat_loaf: int
    swiss_farmhouse_bread: int
    plaited_swiss_loaf: int
    tiger_bread: int
    ginger_loaf: int
    goose_stuffed: int
    beef_wellington: int
    pork_belly: int
    pikeperch_fillet_with_vegetables: int
    steam_bake: int

class DishWarmerProgramId(MieleEnum, missing_to_none=True):
    no_program: Incomplete
    warm_cups_glasses: int
    warm_dishes_plates: int
    keep_warm: int
    slow_roasting: int

class RobotVacuumCleanerProgramId(MieleEnum, missing_to_none=True):
    no_program: Incomplete
    auto: int
    spot: int
    turbo: int
    silent: int

class CoffeeSystemProgramId(MieleEnum, missing_to_none=True):
    no_program: Incomplete
    check_appliance: int
    ristretto: Incomplete
    espresso: Incomplete
    coffee: Incomplete
    long_coffee: Incomplete
    cappuccino: Incomplete
    cappuccino_italiano: Incomplete
    latte_macchiato: Incomplete
    espresso_macchiato: Incomplete
    cafe_au_lait: Incomplete
    caffe_latte: Incomplete
    flat_white: Incomplete
    very_hot_water: Incomplete
    hot_water: Incomplete
    hot_milk: Incomplete
    milk_foam: Incomplete
    black_tea: Incomplete
    herbal_tea: Incomplete
    fruit_tea: Incomplete
    green_tea: Incomplete
    white_tea: Incomplete
    japanese_tea: Incomplete
    coffee_pot: int
    barista_assistant: int
    appliance_settings: Incomplete
    appliance_rinse: Incomplete
    descaling: int
    brewing_unit_degrease: int
    milk_pipework_rinse: int
    milk_pipework_clean: int

class SteamOvenMicroProgramId(MieleEnum, missing_to_none=True):
    no_program: Incomplete
    steam_cooking: int
    microwave: int
    popcorn: int
    quick_mw: int
    sous_vide: int
    eco_steam_cooking: int
    rapid_steam_cooking: int
    descale: int
    menu_cooking: int
    reheating_with_steam: int
    defrosting_with_steam: int
    blanching: int
    bottling: int
    sterilize_crockery: int
    prove_dough: int
    soak: int
    reheating_with_microwave: int
    defrosting_with_microwave: int
    artichokes_small: int
    artichokes_medium: int
    artichokes_large: int
    eggplant_sliced: int
    eggplant_diced: int
    cauliflower_whole_small: int
    cauliflower_whole_medium: int
    cauliflower_whole_large: int
    cauliflower_florets_small: int
    cauliflower_florets_medium: int
    cauliflower_florets_large: int
    green_beans_whole: int
    green_beans_cut: int
    yellow_beans_whole: int
    yellow_beans_cut: int
    broad_beans: int
    common_beans: int
    runner_beans_whole: int
    runner_beans_pieces: int
    runner_beans_sliced: int
    broccoli_whole_small: int
    broccoli_whole_medium: int
    broccoli_whole_large: int
    broccoli_florets_small: int
    broccoli_florets_medium: int
    broccoli_florets_large: int
    endive_halved: int
    endive_quartered: int
    endive_strips: int
    chinese_cabbage_cut: int
    peas: int
    fennel_halved: int
    fennel_quartered: int
    fennel_strips: int
    kale_cut: int
    potatoes_in_the_skin_waxy_small_steam_cooking: int
    potatoes_in_the_skin_waxy_small_rapid_steam_cooking: int
    potatoes_in_the_skin_waxy_medium_steam_cooking: int
    potatoes_in_the_skin_waxy_medium_rapid_steam_cooking: int
    potatoes_in_the_skin_waxy_large_steam_cooking: int
    potatoes_in_the_skin_waxy_large_rapid_steam_cooking: int
    potatoes_in_the_skin_floury_small: int
    potatoes_in_the_skin_floury_medium: int
    potatoes_in_the_skin_floury_large: int
    potatoes_in_the_skin_mainly_waxy_small: int
    potatoes_in_the_skin_mainly_waxy_medium: int
    potatoes_in_the_skin_mainly_waxy_large: int
    potatoes_waxy_whole_small: int
    potatoes_waxy_whole_medium: int
    potatoes_waxy_whole_large: int
    potatoes_waxy_halved: int
    potatoes_waxy_quartered: int
    potatoes_waxy_diced: int
    potatoes_mainly_waxy_small: int
    potatoes_mainly_waxy_medium: int
    potatoes_mainly_waxy_large: int
    potatoes_mainly_waxy_halved: int
    potatoes_mainly_waxy_quartered: int
    potatoes_mainly_waxy_diced: int
    potatoes_floury_whole_small: int
    potatoes_floury_whole_medium: int
    potatoes_floury_whole_large: int
    potatoes_floury_halved: int
    potatoes_floury_quartered: int
    potatoes_floury_diced: int
    german_turnip_sliced: int
    german_turnip_cut_into_batons: int
    german_turnip_diced: int
    pumpkin_diced: int
    corn_on_the_cob: int
    mangel_cut: int
    bunched_carrots_whole_small: int
    bunched_carrots_whole_medium: int
    bunched_carrots_whole_large: int
    bunched_carrots_halved: int
    bunched_carrots_quartered: int
    bunched_carrots_diced: int
    bunched_carrots_cut_into_batons: int
    bunched_carrots_sliced: int
    parisian_carrots_small: int
    parisian_carrots_medium: int
    parisian_carrots_large: int
    carrots_whole_small: int
    carrots_whole_medium: int
    carrots_whole_large: int
    carrots_halved: int
    carrots_quartered: int
    carrots_diced: int
    carrots_cut_into_batons: int
    carrots_sliced: int
    pepper_halved: int
    pepper_quartered: int
    pepper_strips: int
    pepper_diced: int
    parsnip_sliced: int
    parsnip_diced: int
    parsnip_cut_into_batons: int
    parsley_root_sliced: int
    parsley_root_diced: int
    parsley_root_cut_into_batons: int
    leek_pieces: int
    leek_rings: int
    romanesco_whole_small: int
    romanesco_whole_medium: int
    romanesco_whole_large: int
    romanesco_florets_small: int
    romanesco_florets_medium: int
    romanesco_florets_large: int
    brussels_sprout: int
    beetroot_whole_small: int
    beetroot_whole_medium: int
    beetroot_whole_large: int
    red_cabbage_cut: int
    black_salsify_thin: int
    black_salsify_medium: int
    black_salsify_thick: int
    celery_pieces: int
    celery_sliced: int
    celeriac_sliced: int
    celeriac_cut_into_batons: int
    celeriac_diced: int
    white_asparagus_thin: int
    white_asparagus_medium: int
    white_asparagus_thick: int
    green_asparagus_thin: int
    green_asparagus_medium: int
    green_asparagus_thick: int
    spinach: int
    pointed_cabbage_cut: int
    yam_halved: int
    yam_quartered: int
    yam_strips: int
    swede_diced: int
    swede_cut_into_batons: int
    teltow_turnip_sliced: int
    teltow_turnip_diced: int
    jerusalem_artichoke_sliced: int
    jerusalem_artichoke_diced: int
    green_cabbage_cut: int
    savoy_cabbage_cut: int
    courgette_sliced: int
    courgette_diced: int
    snow_pea: int
    perch_whole: int
    perch_fillet_2_cm: int
    perch_fillet_3_cm: int
    gilt_head_bream_whole: int
    gilt_head_bream_fillet: int
    codfish_piece: Incomplete
    codfish_fillet: Incomplete
    trout: int
    pike_fillet: int
    pike_piece: int
    halibut_fillet_2_cm: int
    halibut_fillet_3_cm: int
    carp: int
    salmon_fillet_2_cm: int
    salmon_fillet_3_cm: int
    salmon_steak_2_cm: int
    salmon_steak_3_cm: int
    salmon_piece: int
    salmon_trout: int
    iridescent_shark_fillet: int
    red_snapper_fillet_2_cm: int
    red_snapper_fillet_3_cm: int
    redfish_fillet_2_cm: int
    redfish_fillet_3_cm: int
    redfish_piece: int
    char: int
    plaice_whole_2_cm: int
    plaice_whole_3_cm: int
    plaice_whole_4_cm: int
    plaice_fillet_1_cm: int
    plaice_fillet_2_cm: int
    coalfish_fillet_2_cm: int
    coalfish_fillet_3_cm: int
    coalfish_piece: int
    sea_devil_fillet_3_cm: int
    sea_devil_fillet_4_cm: int
    common_sole_fillet_1_cm: int
    common_sole_fillet_2_cm: int
    atlantic_catfish_fillet_1_cm: int
    atlantic_catfish_fillet_2_cm: int
    turbot_fillet_2_cm: int
    turbot_fillet_3_cm: int
    tuna_steak: int
    tuna_fillet_2_cm: int
    tuna_fillet_3_cm: int
    tilapia_fillet_1_cm: int
    tilapia_fillet_2_cm: int
    nile_perch_fillet_2_cm: int
    nile_perch_fillet_3_cm: int
    zander_fillet: int
    soup_hen: int
    poularde_whole: int
    poularde_breast: int
    turkey_breast: int
    chicken_tikka_masala_with_rice: int
    veal_fillet_whole: int
    veal_fillet_medaillons_1_cm: int
    veal_fillet_medaillons_2_cm: int
    veal_fillet_medaillons_3_cm: int
    goulash_soup: int
    dutch_hash: int
    stuffed_cabbage: int
    beef_tenderloin: int
    beef_tenderloin_medaillons_1_cm_steam_cooking: int
    beef_tenderloin_medaillons_2_cm_steam_cooking: int
    beef_tenderloin_medaillons_3_cm_steam_cooking: int
    silverside_5_cm: int
    silverside_7_5_cm: int
    silverside_10_cm: int
    meat_for_soup_back_or_top_rib: int
    meat_for_soup_leg_steak: int
    meat_for_soup_brisket: int
    viennese_silverside: int
    whole_ham_steam_cooking: int
    whole_ham_reheating: int
    kasseler_piece: int
    kasseler_slice: int
    knuckle_of_pork_fresh: int
    knuckle_of_pork_cured: int
    pork_tenderloin_medaillons_3_cm: int
    pork_tenderloin_medaillons_4_cm: int
    pork_tenderloin_medaillons_5_cm: int
    pumpkin_soup: int
    meat_with_rice: int
    beef_casserole: int
    pumpkin_risotto: int
    risotto: int
    rice_pudding_steam_cooking: int
    rice_pudding_rapid_steam_cooking: int
    amaranth: int
    bulgur: int
    spelt_whole: int
    spelt_cracked: int
    green_spelt_whole: int
    green_spelt_cracked: int
    oats_whole: int
    oats_cracked: int
    millet: int
    quinoa: int
    polenta_swiss_style_fine_polenta: int
    polenta_swiss_style_medium_polenta: int
    polenta_swiss_style_coarse_polenta: int
    polenta: int
    rye_whole: int
    rye_cracked: int
    wheat_whole: int
    wheat_cracked: int
    gnocchi_fresh: int
    yeast_dumplings_fresh: int
    potato_dumplings_raw_boil_in_bag: int
    potato_dumplings_raw_deep_frozen: int
    potato_dumplings_half_half_boil_in_bag: int
    potato_dumplings_half_half_deep_frozen: int
    bread_dumplings_boil_in_the_bag: int
    bread_dumplings_fresh: int
    ravioli_fresh: int
    spaetzle_fresh: int
    tagliatelli_fresh: int
    schupfnudeln_potato_noodels: int
    tortellini_fresh: int
    red_lentils: int
    brown_lentils: int
    beluga_lentils: int
    green_split_peas: int
    yellow_split_peas: int
    chick_peas: int
    white_beans: int
    pinto_beans: int
    red_beans: int
    black_beans: int
    hens_eggs_size_s_soft: int
    hens_eggs_size_s_medium: int
    hens_eggs_size_s_hard: int
    hens_eggs_size_m_soft: int
    hens_eggs_size_m_medium: int
    hens_eggs_size_m_hard: int
    hens_eggs_size_l_soft: int
    hens_eggs_size_l_medium: int
    hens_eggs_size_l_hard: int
    hens_eggs_size_xl_soft: int
    hens_eggs_size_xl_medium: int
    hens_eggs_size_xl_hard: int
    swiss_toffee_cream_100_ml: int
    swiss_toffee_cream_150_ml: int
    toffee_date_dessert_several_small: int
    cheesecake_several_small: int
    cheesecake_one_large: int
    christmas_pudding_cooking: int
    christmas_pudding_heating: int
    treacle_sponge_pudding_several_small: int
    treacle_sponge_pudding_one_large: int
    sweet_cheese_dumplings: int
    apples_whole: int
    apples_halved: int
    apples_quartered: int
    apples_sliced: int
    apples_diced: int
    apricots_halved_steam_cooking: int
    apricots_halved_skinning: int
    apricots_quartered: int
    apricots_wedges: int
    pears_halved: int
    pears_quartered: int
    pears_wedges: int
    sweet_cherries: int
    sour_cherries: int
    pears_to_cook_small_whole: int
    pears_to_cook_small_halved: int
    pears_to_cook_small_quartered: int
    pears_to_cook_medium_whole: int
    pears_to_cook_medium_halved: int
    pears_to_cook_medium_quartered: int
    pears_to_cook_large_whole: int
    pears_to_cook_large_halved: int
    pears_to_cook_large_quartered: int
    mirabelles: int
    nectarines_peaches_halved_steam_cooking: int
    nectarines_peaches_halved_skinning: int
    nectarines_peaches_quartered: int
    nectarines_peaches_wedges: int
    plums_whole: int
    plums_halved: int
    cranberries: int
    quinces_diced: int
    greenage_plums: int
    rhubarb_chunks: int
    gooseberries: int
    mushrooms_whole: int
    mushrooms_halved: int
    mushrooms_sliced: int
    mushrooms_quartered: int
    mushrooms_diced: int
    cep: int
    chanterelle: int
    oyster_mushroom_whole: int
    oyster_mushroom_strips: int
    oyster_mushroom_diced: int
    saucisson: int
    bruehwurst_sausages: int
    bologna_sausage: int
    veal_sausages: int
    crevettes: int
    prawns: int
    king_prawns: int
    small_shrimps: int
    large_shrimps: int
    mussels: int
    scallops: int
    venus_clams: int
    goose_barnacles: int
    cockles: int
    razor_clams_small: int
    razor_clams_medium: int
    razor_clams_large: int
    mussels_in_sauce: int
    bottling_soft: int
    bottling_medium: int
    bottling_hard: int
    melt_chocolate: int
    dissolve_gelatine: int
    sweat_onions: int
    cook_bacon: int
    heating_damp_flannels: int
    decrystallise_honey: int
    make_yoghurt: int
    toffee_date_dessert_one_large: int
    beef_tenderloin_medaillons_1_cm_low_temperature_cooking: int
    beef_tenderloin_medaillons_2_cm_low_temperature_cooking: int
    beef_tenderloin_medaillons_3_cm_low_temperature_cooking: int
    wild_rice: int
    wholegrain_rice: int
    parboiled_rice_steam_cooking: int
    parboiled_rice_rapid_steam_cooking: int
    basmati_rice_steam_cooking: int
    basmati_rice_rapid_steam_cooking: int
    jasmine_rice_steam_cooking: int
    jasmine_rice_rapid_steam_cooking: int
    huanghuanian_steam_cooking: int
    huanghuanian_rapid_steam_cooking: int
    simiao_steam_cooking: int
    simiao_rapid_steam_cooking: int
    long_grain_rice_general_steam_cooking: int
    long_grain_rice_general_rapid_steam_cooking: int
    chongming_steam_cooking: int
    chongming_rapid_steam_cooking: int
    wuchang_steam_cooking: int
    wuchang_rapid_steam_cooking: int
    uonumma_koshihikari_steam_cooking: int
    uonumma_koshihikari_rapid_steam_cooking: int
    sheyang_steam_cooking: int
    sheyang_rapid_steam_cooking: int
    round_grain_rice_general_steam_cooking: int
    round_grain_rice_general_rapid_steam_cooking: int

PROGRAM_IDS: dict[int, type[MieleEnum]]
COFFEE_SYSTEM_PROFILE: dict[range, str]

class PlatePowerStep(MieleEnum, missing_to_none=True):
    plate_step_0: int
    plate_step_warming: Incomplete
    plate_step_1: int
    plate_step_2: int
    plate_step_3: int
    plate_step_4: int
    plate_step_5: int
    plate_step_6: int
    plate_step_7: int
    plate_step_8: int
    plate_step_9: int
    plate_step_10: int
    plate_step_11: int
    plate_step_12: int
    plate_step_13: int
    plate_step_14: int
    plate_step_15: int
    plate_step_16: int
    plate_step_17: int
    plate_step_18: int
    plate_step_boost: Incomplete
    plate_step_boost_2: int
