from _typeshed import Incomplete
from homeassistant.components.automation import EVENT_AUTOMATION_TRIGGERED as EVENT_AUTOMATION_TRIGGERED
from homeassistant.components.script import EVENT_SCRIPT_STARTED as EVENT_SCRIPT_STARTED
from homeassistant.const import EVENT_CALL_SERVICE as EVENT_CALL_SERVICE, EVENT_LOGBOOK_ENTRY as EVENT_LOGBOOK_ENTRY

ALWAYS_CONTINUOUS_DOMAINS: Incomplete
CONDITIONALLY_CONTINUOUS_DOMAINS: Incomplete
ATTR_MESSAGE: str
DOMAIN: str
CONTEXT_USER_ID: str
CONTEXT_ENTITY_ID: str
CONTEXT_ENTITY_ID_NAME: str
CONTEXT_EVENT_TYPE: str
CONTEXT_DOMAIN: str
CONTEXT_STATE: str
CONTEXT_SOURCE: str
CONTEXT_SERVICE: str
CONTEXT_NAME: str
CONTEXT_MESSAGE: str
LOGBOOK_ENTRY_CONTEXT_ID: str
LOGBOOK_ENTRY_DOMAIN: str
LOGBOOK_ENTRY_ENTITY_ID: str
LOGBOOK_ENTRY_ICON: str
LOGBOOK_ENTRY_SOURCE: str
LOGBOOK_ENTRY_MESSAGE: str
LOGBOOK_ENTRY_NAME: str
LOGBOOK_ENTRY_STATE: str
LOGBOOK_ENTRY_WHEN: str
AUTOMATION_EVENTS: Incomplete
BUILT_IN_EVENTS: Incomplete
LOGBOOK_FILTERS: str
LOGBOOK_ENTITIES_FILTER: str
