from typing import Any

DOMAIN: str
CONF_ROUND_DIGITS: str
CONF_SOURCE_SENSOR: str
CONF_UNIT_OF_MEASUREMENT: str
CONF_UNIT_PREFIX: str
CONF_UNIT_TIME: str
METHOD_TRAPEZOIDAL: str
METHOD_LEFT: str
METHOD_RIGHT: str
INTEGRATION_METHODS: Any
