import argparse
from collections.abc import Sequence
from homeassistant import runner as runner
from homeassistant.auth import auth_manager_from_config as auth_manager_from_config
from homeassistant.auth.providers import homeassistant as hass_auth
from homeassistant.config import get_default_config_dir as get_default_config_dir
from homeassistant.core import HomeAssistant as HomeAssistant

def run(args: Sequence[str] | None) -> None: ...
async def run_command(args: argparse.Namespace) -> None: ...
async def list_users(hass: HomeAssistant, provider: hass_auth.HassAuthProvider, args: argparse.Namespace) -> None: ...
async def add_user(hass: HomeAssistant, provider: hass_auth.HassAuthProvider, args: argparse.Namespace) -> None: ...
async def validate_login(hass: HomeAssistant, provider: hass_auth.HassAuthProvider, args: argparse.Namespace) -> None: ...
async def change_password(hass: HomeAssistant, provider: hass_auth.HassAuthProvider, args: argparse.Namespace) -> None: ...
