from .const import PLATFORMS as PLATFORMS
from .coordinator import NeoPoolConfigEntry as NeoPoolConfigEntry, NeoPoolCoordinator as NeoPoolCoordinator
from homeassistant.core import HomeAssistant as HomeAssistant

async def async_setup_entry(hass: HomeAssistant, entry: NeoPoolConfigEntry) -> bool: ...
async def async_unload_entry(hass: HomeAssistant, entry: NeoPoolConfigEntry) -> bool: ...
