from .const import CONF_USE_AUX1 as CONF_USE_AUX1, CONF_USE_AUX2 as CONF_USE_AUX2, CONF_USE_AUX3 as CONF_USE_AUX3, CONF_USE_AUX4 as CONF_USE_AUX4, CONF_USE_COVER_SENSOR as CONF_USE_COVER_SENSOR, DOMAIN as DOMAIN
from .coordinator import NeoPoolConfigEntry as NeoPoolConfigEntry, NeoPoolCoordinator as NeoPoolCoordinator
from .entity import NeoPoolEntity as NeoPoolEntity
from _typeshed import Incomplete
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from homeassistant.components.switch import SwitchEntity as SwitchEntity, SwitchEntityDescription as SwitchEntityDescription
from homeassistant.const import EntityCategory as EntityCategory
from homeassistant.core import HomeAssistant as HomeAssistant
from homeassistant.exceptions import HomeAssistantError as HomeAssistantError, ServiceValidationError as ServiceValidationError
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback as AddConfigEntryEntitiesCallback
from neopool_modbus import InvalidStateReason, NeoPoolModbusClient
from neopool_modbus.registers import BinaryConfigFlag, BitmaskConfigFlag, RelayKind
from typing import Any, override

PARALLEL_UPDATES: int
type _WriteFn = Callable[['NeoPoolSwitch', NeoPoolModbusClient, bool], Awaitable[dict[str, Any]]]
type _IsOnFn = Callable[[dict[str, Any]], bool]

@dataclass(frozen=True, kw_only=True)
class NeoPoolSwitchEntityDescription(SwitchEntityDescription):
    supported_fn: Callable[[dict[str, Any]], bool] | None = ...
    write_fn: _WriteFn | None = ...
    is_on_fn: _IsOnFn | None = ...
    translation_placeholders: dict[str, str] | None = ...

async def _write_manual_filtration(entity: NeoPoolSwitch, client: NeoPoolModbusClient, state: bool) -> dict[str, Any]: ...
async def _write_backwash(entity: NeoPoolSwitch, client: NeoPoolModbusClient, state: bool) -> dict[str, Any]: ...

_RELAY_TIMER_ENABLE_KEY: dict[RelayKind, str]

def _make_write_relay_state(relay: RelayKind) -> _WriteFn: ...
def _make_write_binary_flag(flag: BinaryConfigFlag) -> _WriteFn: ...
def _make_write_bitmask_flag(flag: BitmaskConfigFlag) -> _WriteFn: ...
def _make_is_on_from_key(data_key: str) -> _IsOnFn: ...
def _make_is_on_int_flag(data_key: str) -> _IsOnFn: ...
def _make_is_on_bitmask(data_key: str, mask: int) -> _IsOnFn: ...

SWITCH_DESCRIPTIONS: dict[str, NeoPoolSwitchEntityDescription]
_ENTITY_OPTION_KEY: dict[str, str]

async def async_setup_entry(hass: HomeAssistant, entry: NeoPoolConfigEntry, async_add_entities: AddConfigEntryEntitiesCallback) -> None: ...

_INVALID_STATE_TRANSLATION_KEY: dict[InvalidStateReason, str]

class NeoPoolSwitch(NeoPoolEntity, SwitchEntity):
    entity_description: NeoPoolSwitchEntityDescription
    _attr_translation_placeholders: Incomplete
    _attr_unique_id: Incomplete
    def __init__(self, coordinator: NeoPoolCoordinator, description: NeoPoolSwitchEntityDescription) -> None: ...
    @override
    async def async_turn_on(self, **kwargs: Any) -> None: ...
    @override
    async def async_turn_off(self, **kwargs: Any) -> None: ...
    async def _async_set_state(self, state: bool) -> None: ...
    @property
    @override
    def is_on(self) -> bool: ...
