from .util import get_min_max as get_min_max, temperature_to_homekit as temperature_to_homekit
from _typeshed import Incomplete
from collections.abc import Iterable
from homeassistant.components.climate import ClimateEntityCapabilityAttribute as ClimateEntityCapabilityAttribute, FAN_HIGH as FAN_HIGH, FAN_LOW as FAN_LOW, FAN_MEDIUM as FAN_MEDIUM, FAN_MIDDLE as FAN_MIDDLE, SWING_BOTH as SWING_BOTH, SWING_HORIZONTAL as SWING_HORIZONTAL, SWING_OFF as SWING_OFF, SWING_ON as SWING_ON, SWING_VERTICAL as SWING_VERTICAL
from homeassistant.core import State as State
from homeassistant.util.percentage import ordered_list_item_to_percentage as ordered_list_item_to_percentage, percentage_to_ordered_list_item as percentage_to_ordered_list_item
from typing import Any

ORDERED_FAN_SPEEDS: Incomplete
PRE_DEFINED_FAN_MODES: Incomplete
SWING_MODE_PREFERRED_ORDER: Incomplete
PRE_DEFINED_SWING_MODES: Incomplete
HEAT_COOL_DEADBAND: int

def _lower_to_original(modes: Iterable[Any]) -> dict[str, str]: ...
def get_fan_modes_and_speeds(attributes: dict[str, Any]) -> tuple[dict[str, str], list[str]]: ...
def get_swing_on_mode(attributes: dict[str, Any]) -> str | None: ...
def get_swing_off_mode(attributes: dict[str, Any]) -> str: ...
def has_swing_off_mode(attributes: dict[str, Any]) -> bool: ...
def fan_speed_to_mode(ordered_fan_speeds: list[str], fan_modes: dict[str, str], speed: int) -> str: ...
def fan_mode_to_speed(ordered_fan_speeds: list[str], fan_mode: Any) -> int | None: ...
def is_swing_on(swing_mode: Any) -> bool: ...
def get_temperature_range_from_state(state: State, unit: str, default_min: float, default_max: float) -> tuple[float, float]: ...
def temperature_attribute_to_homekit(state: State, key: str, unit: str) -> float | None: ...
def resolve_target_temp_range(current_high: float, current_low: float, new_high: float | None, new_low: float | None, min_temp: float, max_temp: float) -> tuple[float, float]: ...
