from .accessories import HomeAccessory as HomeAccessory
from .climate_util import fan_mode_to_speed as fan_mode_to_speed, fan_speed_to_mode as fan_speed_to_mode, get_fan_modes_and_speeds as get_fan_modes_and_speeds, get_swing_off_mode as get_swing_off_mode, get_swing_on_mode as get_swing_on_mode, get_temperature_range_from_state as get_temperature_range_from_state, has_swing_off_mode as has_swing_off_mode, is_swing_on as is_swing_on, resolve_target_temp_range as resolve_target_temp_range, temperature_attribute_to_homekit as temperature_attribute_to_homekit
from .const import CHAR_ACTIVE as CHAR_ACTIVE, CHAR_CURRENT_FAN_STATE as CHAR_CURRENT_FAN_STATE, CHAR_CURRENT_TEMPERATURE as CHAR_CURRENT_TEMPERATURE, CHAR_ROTATION_SPEED as CHAR_ROTATION_SPEED, CHAR_SWING_MODE as CHAR_SWING_MODE, CHAR_TARGET_FAN_STATE as CHAR_TARGET_FAN_STATE, PROP_MAX_VALUE as PROP_MAX_VALUE, PROP_MIN_STEP as PROP_MIN_STEP, PROP_MIN_VALUE as PROP_MIN_VALUE, SERV_FANV2 as SERV_FANV2
from .util import temperature_to_homekit as temperature_to_homekit, temperature_to_states as temperature_to_states
from _typeshed import Incomplete
from collections.abc import Mapping
from homeassistant.components.climate import ATTR_FAN_MODE as ATTR_FAN_MODE, ATTR_SWING_MODE as ATTR_SWING_MODE, ATTR_TARGET_TEMP_HIGH as ATTR_TARGET_TEMP_HIGH, ATTR_TARGET_TEMP_LOW as ATTR_TARGET_TEMP_LOW, ClimateEntityCapabilityAttribute as ClimateEntityCapabilityAttribute, ClimateEntityFeature as ClimateEntityFeature, ClimateEntityStateAttribute as ClimateEntityStateAttribute, DEFAULT_MAX_TEMP as DEFAULT_MAX_TEMP, DEFAULT_MIN_TEMP as DEFAULT_MIN_TEMP, FAN_AUTO as FAN_AUTO, FAN_OFF as FAN_OFF, FAN_ON as FAN_ON, HVACAction as HVACAction, HVACMode as HVACMode, SERVICE_SET_FAN_MODE as SERVICE_SET_FAN_MODE, SERVICE_SET_SWING_MODE as SERVICE_SET_SWING_MODE, SWING_OFF as SWING_OFF
from homeassistant.const import ATTR_ENTITY_ID as ATTR_ENTITY_ID, EntityStateAttribute as EntityStateAttribute, STATE_UNAVAILABLE as STATE_UNAVAILABLE, STATE_UNKNOWN as STATE_UNKNOWN
from homeassistant.core import State as State, callback as callback
from homeassistant.util.percentage import percentage_to_ordered_list_item as percentage_to_ordered_list_item
from pyhap.characteristic import Characteristic as Characteristic
from pyhap.service import Service as Service
from typing import Any

_LOGGER: Incomplete
FAN_STATE_INACTIVE: int
FAN_STATE_IDLE: int
FAN_STATE_ACTIVE: int
CLIMATE_INACTIVE_STATES: Incomplete
HC_HASS_TO_HOMEKIT_FAN_STATE: Incomplete

class HomeKitClimateAccessory(HomeAccessory):
    char_speed: Characteristic
    char_swing: Characteristic
    char_current_temp: Characteristic
    char_fan_active: Characteristic
    char_target_fan_state: Characteristic
    char_current_fan_state: Characteristic
    _unit: Incomplete
    fan_modes: dict[str, str]
    ordered_fan_speeds: list[str]
    swing_on_mode: str | None
    swing_off_mode: str
    fan_chars: list[str]
    def __init__(self, *args: Any) -> None: ...
    def get_temperature_range(self, state: State) -> tuple[float, float]: ...
    def _configure_current_temperature_char(self, serv: Service) -> None: ...
    def _configure_target_mode_char(self, serv: Service, char_name: str, value: int, valid_values: dict[HVACMode, int]) -> Characteristic: ...
    def _reject_char_write(self, char: Characteristic, value: Any) -> None: ...
    def _dispatch_climate_write(self, service: str, params: dict[str, Any]) -> None: ...
    def _update_temperature_char(self, char: Characteristic, state: State, attr: str) -> None: ...
    def _update_current_temperature_char(self, state: State) -> None: ...
    def _dual_setpoint_params(self, cool_char: Characteristic, heat_char: Characteristic, new_high: float | None, new_low: float | None) -> dict[str, float]: ...
    def _temperature_to_homekit(self, temp: float) -> float: ...
    def _temperature_to_states(self, temp: float) -> float: ...
    def _fan_speed_params(self, speed: int) -> dict[str, Any] | None: ...
    def _set_fan_speed(self, speed: int) -> None: ...
    def _swing_mode_params(self, swing_on: int) -> dict[str, Any] | None: ...
    def _set_swing_mode(self, swing_on: int) -> None: ...
    def _update_fan_speed_char(self, attributes: Mapping[str, Any]) -> None: ...
    def _update_swing_char(self, attributes: Mapping[str, Any]) -> None: ...
    def _configure_fan_service(self, primary_serv: Service) -> None: ...
    def _get_on_mode(self) -> str: ...
    def _set_fan_active(self, active: int) -> None: ...
    def _set_fan_auto(self, auto: int) -> None: ...
    @callback
    def _async_update_fan_service(self, new_state: State) -> None: ...
