from _typeshed import Incomplete

DOMAIN: str
CONF_BASE_PATH: str
CONF_DAYS: str
CONF_INCLUDED: str
CONF_UNIT: str
CONF_UPCOMING_DAYS: str
CONF_WANTED_MAX_ITEMS: str
DEFAULT_NAME: str
DEFAULT_UPCOMING_DAYS: int
DEFAULT_VERIFY_SSL: bool
DEFAULT_WANTED_MAX_ITEMS: int
LOGGER: Incomplete
