from ..helpers.frame import MissingIntegrationFrame as MissingIntegrationFrame, get_integration_frame as get_integration_frame
from typing import Any, Callable, Dict, Optional

def deprecated_substitute(substitute_name: str) -> Callable[..., Callable]: ...
def get_deprecated(config: Dict[str, Any], new_name: str, old_name: str, default: Optional[Any]=...) -> Optional[Any]: ...
def deprecated_function(replacement: str) -> Callable[..., Callable]: ...
