from homeassistant.exceptions import HomeAssistantError as HomeAssistantError

class AxisException(HomeAssistantError): ...
class AlreadyConfigured(AxisException): ...
class AuthenticationRequired(AxisException): ...
class CannotConnect(AxisException): ...
class UserLevel(AxisException): ...
