from _typeshed import Incomplete
from aiohttp import web as web
from aiohttp.typedefs import JSONDecoder as JSONDecoder
from homeassistant.helpers.json import json_loads as json_loads
from multidict import MultiDict
from typing import Any

class MockStreamReader:
    _content: Incomplete
    def __init__(self, content: bytes) -> None: ...
    async def read(self, byte_count: int = ...) -> bytes: ...

class MockRequest:
    mock_source: Union[str, None]
    method: Incomplete
    url: Incomplete
    status: Incomplete
    headers: Incomplete
    query_string: Incomplete
    _content: Incomplete
    def __init__(self, content: bytes, mock_source: str, method: str = ..., status: int = ..., headers: Union[dict[str, str], None] = ..., query_string: Union[str, None] = ..., url: str = ...) -> None: ...
    @property
    def query(self) -> MultiDict[str]: ...
    @property
    def _text(self) -> str: ...
    @property
    def content(self) -> MockStreamReader: ...
    async def json(self, loads: JSONDecoder = ...) -> Any: ...
    async def post(self) -> MultiDict[str]: ...
    async def text(self) -> str: ...

def serialize_response(response: web.Response) -> dict[str, Any]: ...
