from _typeshed import Incomplete

_LOGGER: Incomplete

def is_virtual_env() -> bool: ...
def is_docker_env() -> bool: ...
def get_installed_versions(specifiers: set[str]) -> set[str]: ...
def is_installed(requirement_str: str) -> bool: ...

_UV_ENV_PYTHON_VARS: Incomplete

def install_package(package: str, upgrade: bool = True, target: str | None = None, constraints: str | None = None, timeout: int | None = None) -> bool: ...
async def async_get_user_site(deps_dir: str) -> str: ...
