from homeassistant.const import SPEED as SPEED, SPEED_INCHES_PER_DAY as SPEED_INCHES_PER_DAY, SPEED_INCHES_PER_HOUR as SPEED_INCHES_PER_HOUR, SPEED_KILOMETERS_PER_HOUR as SPEED_KILOMETERS_PER_HOUR, SPEED_METERS_PER_SECOND as SPEED_METERS_PER_SECOND, SPEED_MILES_PER_HOUR as SPEED_MILES_PER_HOUR, SPEED_MILLIMETERS_PER_DAY as SPEED_MILLIMETERS_PER_DAY, UNIT_NOT_RECOGNIZED_TEMPLATE as UNIT_NOT_RECOGNIZED_TEMPLATE
from typing import Any

VALID_UNITS: tuple[str, ...]
HRS_TO_SECS: Any
KM_TO_M: int
KM_TO_MILE: float
M_TO_IN: float
UNIT_CONVERSION: dict[str, float]

def convert(value: float, unit_1: str, unit_2: str) -> float: ...
