from _typeshed import Incomplete
from homeassistant.const import SPEED as SPEED, SPEED_FEET_PER_SECOND as SPEED_FEET_PER_SECOND, SPEED_INCHES_PER_DAY as SPEED_INCHES_PER_DAY, SPEED_INCHES_PER_HOUR as SPEED_INCHES_PER_HOUR, SPEED_KILOMETERS_PER_HOUR as SPEED_KILOMETERS_PER_HOUR, SPEED_KNOTS as SPEED_KNOTS, SPEED_METERS_PER_SECOND as SPEED_METERS_PER_SECOND, SPEED_MILES_PER_HOUR as SPEED_MILES_PER_HOUR, SPEED_MILLIMETERS_PER_DAY as SPEED_MILLIMETERS_PER_DAY, UNIT_NOT_RECOGNIZED_TEMPLATE as UNIT_NOT_RECOGNIZED_TEMPLATE

VALID_UNITS: tuple[str, ...]
FOOT_TO_M: float
HRS_TO_SECS: Incomplete
IN_TO_M: float
KM_TO_M: int
MILE_TO_M: float
NAUTICAL_MILE_TO_M: int
UNIT_CONVERSION: dict[str, float]

def convert(value: float, unit_1: str, unit_2: str) -> float: ...
