from homeassistant.const import UNIT_NOT_RECOGNIZED_TEMPLATE as UNIT_NOT_RECOGNIZED_TEMPLATE, VOLUME as VOLUME, VOLUME_CUBIC_FEET as VOLUME_CUBIC_FEET, VOLUME_CUBIC_METERS as VOLUME_CUBIC_METERS, VOLUME_FLUID_OUNCE as VOLUME_FLUID_OUNCE, VOLUME_GALLONS as VOLUME_GALLONS, VOLUME_LITERS as VOLUME_LITERS, VOLUME_MILLILITERS as VOLUME_MILLILITERS

VALID_UNITS: tuple[str, ...]

def liter_to_gallon(liter: float) -> float: ...
def gallon_to_liter(gallon: float) -> float: ...
def cubic_meter_to_cubic_feet(cubic_meter: float) -> float: ...
def cubic_feet_to_cubic_meter(cubic_feet: float) -> float: ...
def convert(volume: float, from_unit: str, to_unit: str) -> float: ...
