from .const import ATTR_DATA as ATTR_DATA, CONF_CLOUDHOOK_URL as CONF_CLOUDHOOK_URL, CONF_WEBHOOK_URL as CONF_WEBHOOK_URL, DOMAIN as DOMAIN, EVENT_TRANSACTION_CREATED as EVENT_TRANSACTION_CREATED, MONZO_WEBHOOK_TRANSACTION_CREATED as MONZO_WEBHOOK_TRANSACTION_CREATED
from .coordinator import MonzoConfigEntry as MonzoConfigEntry, MonzoCoordinator as MonzoCoordinator
from _typeshed import Incomplete
from aiohttp.web import Request as Request
from collections.abc import Iterable
from datetime import datetime
from homeassistant.components import cloud as cloud, webhook as webhook
from homeassistant.const import CONF_WEBHOOK_ID as CONF_WEBHOOK_ID, EVENT_CORE_CONFIG_UPDATE as EVENT_CORE_CONFIG_UPDATE
from homeassistant.core import CALLBACK_TYPE as CALLBACK_TYPE, Event as Event, HomeAssistant as HomeAssistant, callback as callback
from homeassistant.exceptions import OAuth2TokenRequestReauthError as OAuth2TokenRequestReauthError
from homeassistant.helpers.dispatcher import async_dispatcher_send as async_dispatcher_send
from homeassistant.helpers.event import async_call_later as async_call_later
from homeassistant.helpers.network import NoURLAvailableError as NoURLAvailableError
from monzopy import AbstractMonzoApi as AbstractMonzoApi
from typing import Any

_LOGGER: Incomplete
WEBHOOK_RETRY_DELAY: int

def webhook_signal(account_id: str) -> str: ...
async def async_delete_remote_webhooks(api: AbstractMonzoApi, account_ids: Iterable[str], webhook_url: str) -> None: ...

class MonzoWebhookManager:
    hass: Incomplete
    entry: Incomplete
    coordinator: Incomplete
    _active: bool
    _register_lock: Incomplete
    _retry_cancel: CALLBACK_TYPE | None
    _retrying: bool
    _webhook_url: str | None
    _known_account_ids: set[str]
    def __init__(self, hass: HomeAssistant, entry: MonzoConfigEntry, coordinator: MonzoCoordinator) -> None: ...
    @property
    def diagnostics_data(self) -> dict[str, bool | int]: ...
    async def async_setup(self) -> None: ...
    async def async_register_remote_webhooks(self, _now: datetime | None = None) -> None: ...
    async def _async_reconcile_remote_webhooks(self, webhook_url: str, registered_webhook_ids: list[str]) -> None: ...
    async def _async_rollback_remote_webhooks(self, webhook_ids: list[str]) -> None: ...
    async def _async_remove_previous_remote_webhooks(self) -> None: ...
    async def async_unload(self) -> None: ...
    async def async_handle_webhook(self, hass: HomeAssistant, webhook_id: str, request: Request) -> None: ...
    @callback
    def _async_cloud_connection_changed(self, state: cloud.CloudConnectionState) -> None: ...
    @callback
    def _async_cloudhook_changed(self, cloudhook: dict[str, Any] | None) -> None: ...
    @callback
    def _async_core_config_updated(self, event: Event[dict[str, Any]]) -> None: ...
    @callback
    def _async_accounts_updated(self) -> None: ...
    @callback
    def _async_schedule_registration(self, name: str) -> None: ...
    def _schedule_retry(self, message: str, err: Exception | None = None) -> None: ...
    def _log_retry_success(self) -> None: ...
    async def _async_retry(self, now: datetime) -> None: ...
    def _cancel_retry(self) -> None: ...
    @callback
    def _async_unregister_local_webhook(self) -> None: ...
