from ..const import CONF_RESPOND_TO_READ as CONF_RESPOND_TO_READ
from homeassistant.const import Platform as Platform
from typing import Any

def migrate_1_to_2(data: dict[str, Any]) -> None: ...
def _migrate_light_schema_1_to_2(light_knx_data: dict[str, Any]) -> None: ...
def migrate_2_1_to_2_2(data: dict[str, Any]) -> None: ...
