from _typeshed import Incomplete

DOMAIN: str
KNOWN_DEVICES: Incomplete
CONTROLLER: Incomplete
ENTITY_MAP: Incomplete
TRIGGERS: Incomplete
HOMEKIT_DIR: str
PAIRING_FILE: str
IDENTIFIER_SERIAL_NUMBER: str
IDENTIFIER_ACCESSORY_ID: str
IDENTIFIER_LEGACY_SERIAL_NUMBER: str
IDENTIFIER_LEGACY_ACCESSORY_ID: str
HOMEKIT_ACCESSORY_DISPATCH: Incomplete
CHARACTERISTIC_PLATFORMS: Incomplete
STARTUP_EXCEPTIONS: Incomplete
DEBOUNCE_COOLDOWN: int
SUBSCRIBE_COOLDOWN: float
