from _typeshed import Incomplete

DEFAULT_HOST: str
DEFAULT_PORT: int
DOMAIN: str
DEVICE_KEYS_0_3: Incomplete
DEVICE_KEYS_0_7: Incomplete
DEVICE_KEYS_A_B: Incomplete
DEVICE_KEYS_A_D: Incomplete
DEVICE_SUPPORT: Incomplete
DEVICE_SUPPORT_OPTIONS: Incomplete
PRECISION_MAPPING_FAMILY_28: Incomplete
OPTION_ENTRY_DEVICE_OPTIONS: str
OPTION_ENTRY_SENSOR_PRECISION: str
INPUT_ENTRY_CLEAR_OPTIONS: str
INPUT_ENTRY_DEVICE_SELECTION: str
MANUFACTURER_MAXIM: str
MANUFACTURER_HOBBYBOARDS: str
MANUFACTURER_EDS: str
READ_MODE_BOOL: str
READ_MODE_FLOAT: str
READ_MODE_INT: str
