from .const import DOMAIN as DOMAIN
from .coordinator import IndevoltCoordinator as IndevoltCoordinator
from _typeshed import Incomplete
from homeassistant.core import HomeAssistant as HomeAssistant, ServiceCall as ServiceCall
from homeassistant.exceptions import HomeAssistantError as HomeAssistantError, ServiceValidationError as ServiceValidationError
from homeassistant.helpers.service import async_extract_config_entry_ids as async_extract_config_entry_ids
from indevolt_api import IndevoltRealtimeAction
from typing import Final, Never

RT_ACTION_SERVICE_SCHEMA: Final[Incomplete]

async def async_setup_services(hass: HomeAssistant) -> None: ...
async def _async_handle_realtime_action(hass: HomeAssistant, call: ServiceCall, action: IndevoltRealtimeAction) -> None: ...
async def _async_get_coordinators_from_call(hass: HomeAssistant, call: ServiceCall) -> list[IndevoltCoordinator]: ...
def _validate_realtime_action(coordinators: list[IndevoltCoordinator], action: IndevoltRealtimeAction, power: int, target_soc: int) -> None: ...
async def _execute_realtime_action(coordinators: list[IndevoltCoordinator], action: IndevoltRealtimeAction, power: int, target_soc: int) -> None: ...
def _raise_power_exceeds_max(power: int, max_power: int, generation: int) -> Never: ...
def _raise_soc_below_minimum(target_soc: int, minimum_soc: int) -> Never: ...
def _raise_soc_below_emergency(target: int, emergency_soc: int) -> Never: ...
def _raise_no_target_entries() -> Never: ...
