from .bot import BaseTelegramBot as BaseTelegramBot, TelegramBotConfigEntry as TelegramBotConfigEntry
from _typeshed import Incomplete
from homeassistant.core import HomeAssistant as HomeAssistant
from telegram import Bot as Bot
from telegram.ext import CallbackContext as CallbackContext

_LOGGER: Incomplete

async def async_setup_platform(hass: HomeAssistant, bot: Bot, config: TelegramBotConfigEntry) -> BaseTelegramBot | None: ...
async def process_error(update: object, context: CallbackContext) -> None: ...
def error_callback(error: Exception, update: object | None = None) -> None: ...

class PollBot(BaseTelegramBot):
    bot: Incomplete
    application: Incomplete
    def __init__(self, hass: HomeAssistant, bot: Bot, config: TelegramBotConfigEntry) -> None: ...
    async def shutdown(self) -> None: ...
    async def start_polling(self) -> None: ...
    async def stop_polling(self) -> None: ...
