from _typeshed import Incomplete

DOMAIN: str
API_LAST_DATA: str
API_STATION_COORDS: str
API_STATION_INDOOR: str
API_STATION_INFO: str
API_STATION_LOCATION: str
API_STATION_NAME: str
API_STATION_MAC_ADDRESS: str
API_STATION_TYPE: str
LOGGER: Incomplete
