import probatio
from .const import ATTR_ADDRESS as ATTR_ADDRESS, ATTR_HUB as ATTR_HUB, ATTR_SLAVE as ATTR_SLAVE, ATTR_UNIT as ATTR_UNIT, ATTR_VALUE as ATTR_VALUE, CALL_TYPE_WRITE_COIL as CALL_TYPE_WRITE_COIL, CALL_TYPE_WRITE_COILS as CALL_TYPE_WRITE_COILS, CALL_TYPE_WRITE_REGISTER as CALL_TYPE_WRITE_REGISTER, CALL_TYPE_WRITE_REGISTERS as CALL_TYPE_WRITE_REGISTERS, DATA_MODBUS_HUBS as DATA_MODBUS_HUBS, DEFAULT_HUB as DEFAULT_HUB, DOMAIN as DOMAIN, LOGGER as LOGGER, SERVICE_STOP as SERVICE_STOP, SERVICE_WRITE_COIL as SERVICE_WRITE_COIL, SERVICE_WRITE_REGISTER as SERVICE_WRITE_REGISTER, SIGNAL_STOP_ENTITY as SIGNAL_STOP_ENTITY
from .modbus import ModbusHub as ModbusHub, async_modbus_setup as async_modbus_setup
from collections.abc import Callable as Callable
from homeassistant.const import ATTR_STATE as ATTR_STATE, SERVICE_RELOAD as SERVICE_RELOAD
from homeassistant.core import HomeAssistant as HomeAssistant, ServiceCall as ServiceCall, callback as callback
from homeassistant.exceptions import ServiceValidationError as ServiceValidationError
from homeassistant.helpers.dispatcher import async_dispatcher_send as async_dispatcher_send
from homeassistant.helpers.entity_platform import async_get_platforms as async_get_platforms
from homeassistant.helpers.reload import async_integration_yaml_config as async_integration_yaml_config
from homeassistant.helpers.service import async_register_admin_service as async_register_admin_service
from typing import Any

def _write_service_schema(attr: str, validator: Callable[[Any], Any]) -> probatio.Schema: ...
def _get_hubs(hass: HomeAssistant) -> dict[str, ModbusHub]: ...
def _get_service_call_details(service: ServiceCall) -> tuple[ModbusHub, int, int]: ...
async def _async_write_register(service: ServiceCall) -> None: ...
async def _async_write_coil(service: ServiceCall) -> None: ...
async def _async_stop_hub(service: ServiceCall) -> None: ...
async def _async_reload_config(call: ServiceCall) -> None: ...
@callback
def async_setup_services(hass: HomeAssistant) -> None: ...
