from typing import Any
from zeroconf import DNSRecord as DNSRecord, ServiceBrowser, Zeroconf
from zeroconf.asyncio import AsyncZeroconf

class HaZeroconf(Zeroconf):
    def close(self) -> None: ...
    ha_close: Any = ...

class HaAsyncZeroconf(AsyncZeroconf):
    zeroconf: Any = ...
    loop: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def async_close(self) -> None: ...

class HaServiceBrowser(ServiceBrowser):
    def update_record(self, zc: Zeroconf, now: float, record: DNSRecord) -> None: ...
