import voluptuous as vol
from . import DATA_APPS as DATA_APPS
from .const import CONF_APPS as CONF_APPS, CONF_APPS_TO_INCLUDE_OR_EXCLUDE as CONF_APPS_TO_INCLUDE_OR_EXCLUDE, CONF_INCLUDE_OR_EXCLUDE as CONF_INCLUDE_OR_EXCLUDE, CONF_VOLUME_STEP as CONF_VOLUME_STEP, DEFAULT_NAME as DEFAULT_NAME, DEFAULT_VOLUME_STEP as DEFAULT_VOLUME_STEP, DEVICE_ID as DEVICE_ID, DOMAIN as DOMAIN, VIZIO_DEVICE_CLASSES as VIZIO_DEVICE_CLASSES
from .coordinator import VizioConfigEntry as VizioConfigEntry
from _typeshed import Incomplete
from collections.abc import Mapping
from homeassistant.components.media_player import MediaPlayerDeviceClass as MediaPlayerDeviceClass
from homeassistant.config_entries import ConfigFlow as ConfigFlow, ConfigFlowResult as ConfigFlowResult, OptionsFlow as OptionsFlow, SOURCE_REAUTH as SOURCE_REAUTH, SOURCE_RECONFIGURE as SOURCE_RECONFIGURE, SOURCE_ZEROCONF as SOURCE_ZEROCONF
from homeassistant.const import CONF_ACCESS_TOKEN as CONF_ACCESS_TOKEN, CONF_DEVICE_CLASS as CONF_DEVICE_CLASS, CONF_EXCLUDE as CONF_EXCLUDE, CONF_HOST as CONF_HOST, CONF_INCLUDE as CONF_INCLUDE, CONF_NAME as CONF_NAME, CONF_PIN as CONF_PIN
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.helpers.aiohttp_client import async_get_clientsession as async_get_clientsession
from homeassistant.helpers.service_info.zeroconf import ZeroconfServiceInfo as ZeroconfServiceInfo
from typing import Any, override
from vizaio import AppRecord as AppRecord, PairChallenge as PairChallenge, Vizio

_LOGGER: Incomplete

def _get_config_schema(input_dict: dict[str, Any] | None = None) -> vol.Schema: ...
def _get_pairing_schema(input_dict: dict[str, Any] | None = None) -> vol.Schema: ...
def _get_device(hass: HomeAssistant, host: str, device_class: str, auth_token: str | None = None) -> Vizio: ...
async def _async_detect_device_class(hass: HomeAssistant, host: str) -> MediaPlayerDeviceClass: ...
async def _async_get_unique_id(hass: HomeAssistant, host: str, device_class: str) -> str | None: ...
async def _async_validate_config(hass: HomeAssistant, host: str, auth_token: str | None, device_class: str) -> bool: ...

class VizioOptionsConfigFlow(OptionsFlow):
    def _get_app_list(self) -> tuple[AppRecord, ...]: ...
    async def async_step_init(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...

class VizioConfigFlow(ConfigFlow, domain=DOMAIN):
    VERSION: int
    MINOR_VERSION: int
    @staticmethod
    @callback
    @override
    def async_get_options_flow(config_entry: VizioConfigEntry) -> VizioOptionsConfigFlow: ...
    _user_schema: vol.Schema | None
    _must_show_form: bool | None
    _pair_challenge: PairChallenge | None
    _data: dict[str, Any] | None
    def __init__(self) -> None: ...
    def _async_show_source_form(self, errors: dict[str, str] | None = None) -> ConfigFlowResult: ...
    def _async_finish_flow(self) -> ConfigFlowResult: ...
    async def _async_validate_and_continue(self) -> ConfigFlowResult: ...
    @override
    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    @override
    async def async_step_zeroconf(self, discovery_info: ZeroconfServiceInfo) -> ConfigFlowResult: ...
    async def async_step_reauth(self, entry_data: Mapping[str, Any]) -> ConfigFlowResult: ...
    async def async_step_reauth_confirm(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_reconfigure(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_pair_tv(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_pairing_complete(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
