from _typeshed import Incomplete

DOMAIN: str
ATTR_LAST_ACTION: str
ATTR_LAST_TRIGGERED: str
ATTR_VARIABLES: str
CONF_ADVANCED: str
CONF_EXAMPLE: str
CONF_FIELDS: str
CONF_REQUIRED: str
CONF_TRACE: str
ENTITY_ID_FORMAT: Incomplete
EVENT_SCRIPT_STARTED: str
LOGGER: Incomplete
