from .const import CONF_DAILY_EVENTS as CONF_DAILY_EVENTS, CONF_LEARNING_SCHEDULE as CONF_LEARNING_SCHEDULE, CONF_YEARLY_EVENTS as CONF_YEARLY_EVENTS, DEFAULT_CALENDAR_EVENTS as DEFAULT_CALENDAR_EVENTS, DailyCalendarEventType as DailyCalendarEventType, LearningScheduleEventType as LearningScheduleEventType, YearlyCalendarEventType as YearlyCalendarEventType
from .entity import JewishCalendarConfigEntry as JewishCalendarConfigEntry, JewishCalendarEntity as JewishCalendarEntity
from _typeshed import Incomplete
from collections.abc import Callable as Callable
from dataclasses import dataclass
from datetime import date, datetime, time
from hdate import HDateInfo, Zmanim as Zmanim
from homeassistant.components.calendar import CalendarEntity as CalendarEntity, CalendarEntityDescription as CalendarEntityDescription, CalendarEvent as CalendarEvent
from homeassistant.core import HomeAssistant as HomeAssistant
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback as AddConfigEntryEntitiesCallback

_LOGGER: Incomplete
PARALLEL_UPDATES: int
_SATURDAY: int
_SIMCHAT_TORAH: str
type JewishCalendarEventType = DailyCalendarEventType | LearningScheduleEventType | YearlyCalendarEventType

@dataclass(frozen=True, kw_only=True)
class JewishCalendarCalendarEntityDescription(CalendarEntityDescription):
    value_fn: Callable[[JewishCalendarEventType, date, HDateInfo, Zmanim], list[CalendarEvent] | CalendarEvent | None]

def _create_daily_event(event_type: JewishCalendarEventType, target_date: date, info: HDateInfo, zmanim: Zmanim) -> CalendarEvent | None: ...
def _create_yearly_event(event_type: JewishCalendarEventType, target_date: date, info: HDateInfo, zmanim: Zmanim) -> list[CalendarEvent] | CalendarEvent | None: ...
def _create_learning_event(event_type: JewishCalendarEventType, target_date: date, info: HDateInfo, zmanim: Zmanim) -> CalendarEvent | None: ...

CALENDARS: Incomplete

async def async_setup_entry(hass: HomeAssistant, config_entry: JewishCalendarConfigEntry, async_add_entities: AddConfigEntryEntitiesCallback) -> None: ...

class JewishCalendar(JewishCalendarEntity, CalendarEntity):
    entity_description: JewishCalendarCalendarEntityDescription
    _events_config: Incomplete
    def __init__(self, config_entry: JewishCalendarConfigEntry, description: JewishCalendarCalendarEntityDescription) -> None: ...
    @property
    def event(self) -> CalendarEvent | None: ...
    async def async_get_events(self, hass: HomeAssistant, start_date: datetime, end_date: datetime) -> list[CalendarEvent]: ...
    def _get_next_event(self, _date: date | datetime) -> CalendarEvent | None: ...
    def _filter_start_end(self, events: list[CalendarEvent], start: datetime, end: datetime | None = None) -> list[CalendarEvent]: ...
    def _event_sort_key(self, event: CalendarEvent) -> datetime: ...
    def _date_to_dt(self, val: date | datetime, _time: time) -> datetime: ...
    def _get_events_for_date(self, target_date: date) -> list[CalendarEvent]: ...
    def _update_times(self, zmanim: Zmanim) -> list[datetime | None]: ...
