from homeassistant.components.light import SUPPORT_BRIGHTNESS as SUPPORT_BRIGHTNESS, SUPPORT_TRANSITION as SUPPORT_TRANSITION
from homeassistant.const import CONF_HOST as CONF_HOST
from typing import Any

ATTR_AUTO: str
ATTR_DIMMER: str
ATTR_HUE: str
ATTR_SAT: str
ATTR_TRADFRI_GATEWAY: str
ATTR_TRADFRI_GATEWAY_MODEL: str
ATTR_TRADFRI_MANUFACTURER: str
ATTR_TRANSITION_TIME: str
ATTR_MODEL: str
CONF_ALLOW_TRADFRI_GROUPS: str
CONF_IDENTITY: str
CONF_IMPORT_GROUPS: str
CONF_GATEWAY_ID: str
CONF_KEY: str
DEFAULT_ALLOW_TRADFRI_GROUPS: bool
DOMAIN: str
KEY_API: str
DEVICES: str
GROUPS: str
SIGNAL_GW: str
KEY_SECURITY_CODE: str
SUPPORTED_GROUP_FEATURES: Any
SUPPORTED_LIGHT_FEATURES = SUPPORT_TRANSITION
PLATFORMS: Any
TIMEOUT_API: int
