from _typeshed import Incomplete

DOMAIN: str
LOGGER: Incomplete
DEFAULT_CONVERSATION_NAME: str
CONF_CHAT_MODEL: str
CONF_MAX_TOKENS: str
CONF_TEMPERATURE: str
CONF_TOP_P: str
CONF_BASE_URL: str
CONF_RECOMMENDED: str
CONF_STREAMING: str
DEFAULT_MODEL: str
RECOMMENDED_CHAT_MODELS: Incomplete
RECOMMENDED_MAX_TOKENS: int
RECOMMENDED_TEMPERATURE: float
RECOMMENDED_TOP_P: float
DEFAULT_BASE_URL: str
DEFAULT_API_KEY: str
