from _typeshed import Incomplete
from homeassistant.const import Platform as Platform

LOGGER: Incomplete
DOMAIN: str
HASSIO_CONFIGURATION_URL: str
CONF_BRIDGE_ID: str
CONF_GROUP_ID_BASE: str
DEFAULT_PORT: int
DEFAULT_ALLOW_CLIP_SENSOR: bool
DEFAULT_ALLOW_DECONZ_GROUPS: bool
DEFAULT_ALLOW_NEW_DEVICES: bool
CONF_ALLOW_CLIP_SENSOR: str
CONF_ALLOW_DECONZ_GROUPS: str
CONF_ALLOW_NEW_DEVICES: str
CONF_MASTER_GATEWAY: str
PLATFORMS: Incomplete
ATTR_DARK: str
ATTR_LOCKED: str
ATTR_OFFSET: str
ATTR_ON: str
ATTR_VALVE: str
POWER_PLUGS: Incomplete
CONF_ANGLE: str
CONF_GESTURE: str
ATTR_DURATION: str
ATTR_ROTATION: str
