from homeassistant.const import Platform as Platform
from typing import Any

LOGGER: Any
DOMAIN: str
HASSIO_CONFIGURATION_URL: str
CONF_BRIDGE_ID: str
CONF_GROUP_ID_BASE: str
DEFAULT_PORT: int
DEFAULT_ALLOW_CLIP_SENSOR: bool
DEFAULT_ALLOW_DECONZ_GROUPS: bool
DEFAULT_ALLOW_NEW_DEVICES: bool
CONF_ALLOW_CLIP_SENSOR: str
CONF_ALLOW_DECONZ_GROUPS: str
CONF_ALLOW_NEW_DEVICES: str
CONF_MASTER_GATEWAY: str
PLATFORMS: Any
ATTR_DARK: str
ATTR_LOCKED: str
ATTR_OFFSET: str
ATTR_ON: str
ATTR_VALVE: str
POWER_PLUGS: Any
CONF_ANGLE: str
CONF_GESTURE: str
