from .context import template_cv as template_cv
from _typeshed import Incomplete
from homeassistant.core import HomeAssistant as HomeAssistant
from typing import Any, NoReturn, overload

_SENTINEL: Incomplete

def raise_no_default(function: str, value: Any) -> NoReturn: ...
def resolve_area_id(hass: HomeAssistant, lookup_value: Any) -> str | None: ...
@overload
def forgiving_boolean(value: Any) -> bool | object: ...
@overload
def forgiving_boolean[_T](value: Any, default: _T) -> bool | _T: ...
def result_as_boolean(template_result: Any | None) -> bool: ...
