from .const import DATA_MANAGER as DATA_MANAGER, DOMAIN as DOMAIN
from homeassistant.core import HomeAssistant as HomeAssistant, ServiceCall as ServiceCall
from homeassistant.helpers.hassio import is_hassio as is_hassio

async def _async_handle_create_service(call: ServiceCall) -> None: ...
async def _async_handle_create_automatic_service(call: ServiceCall) -> None: ...
def async_setup_services(hass: HomeAssistant) -> None: ...
