from . import UpdateEntity as UpdateEntity
from .const import ATTR_BACKUP as ATTR_BACKUP, ATTR_VERSION as ATTR_VERSION, DATA_COMPONENT as DATA_COMPONENT, DOMAIN as DOMAIN, SERVICE_INSTALL as SERVICE_INSTALL, SERVICE_SKIP as SERVICE_SKIP, UpdateEntityFeature as UpdateEntityFeature
from homeassistant.core import HomeAssistant as HomeAssistant, ServiceCall as ServiceCall, callback as callback
from homeassistant.exceptions import HomeAssistantError as HomeAssistantError

async def _async_install(entity: UpdateEntity, service_call: ServiceCall) -> None: ...
async def _async_skip(entity: UpdateEntity, service_call: ServiceCall) -> None: ...
async def _async_clear_skipped(entity: UpdateEntity, service_call: ServiceCall) -> None: ...
@callback
def async_setup_services(hass: HomeAssistant) -> None: ...
