import logging
from _typeshed import Incomplete
from homeassistant.const import CONF_LLM_HASS_API as CONF_LLM_HASS_API
from homeassistant.helpers import llm as llm

DOMAIN: str
LOGGER: logging.Logger
DEFAULT_CONVERSATION_NAME: str
DEFAULT_AI_TASK_NAME: str
DEFAULT_NAME: str
CONF_CHAT_MODEL: str
CONF_IMAGE_MODEL: str
CONF_CODE_INTERPRETER: str
CONF_FILENAMES: str
CONF_MAX_TOKENS: str
CONF_PROMPT: str
CONF_REASONING_EFFORT: str
CONF_RECOMMENDED: str
CONF_TEMPERATURE: str
CONF_TOP_P: str
CONF_VERBOSITY: str
CONF_WEB_SEARCH: str
CONF_WEB_SEARCH_USER_LOCATION: str
CONF_WEB_SEARCH_CONTEXT_SIZE: str
CONF_WEB_SEARCH_CITY: str
CONF_WEB_SEARCH_REGION: str
CONF_WEB_SEARCH_COUNTRY: str
CONF_WEB_SEARCH_TIMEZONE: str
CONF_WEB_SEARCH_INLINE_CITATIONS: str
RECOMMENDED_CODE_INTERPRETER: bool
RECOMMENDED_CHAT_MODEL: str
RECOMMENDED_IMAGE_MODEL: str
RECOMMENDED_MAX_TOKENS: int
RECOMMENDED_REASONING_EFFORT: str
RECOMMENDED_TEMPERATURE: float
RECOMMENDED_TOP_P: float
RECOMMENDED_VERBOSITY: str
RECOMMENDED_WEB_SEARCH: bool
RECOMMENDED_WEB_SEARCH_CONTEXT_SIZE: str
RECOMMENDED_WEB_SEARCH_USER_LOCATION: bool
RECOMMENDED_WEB_SEARCH_INLINE_CITATIONS: bool
UNSUPPORTED_MODELS: list[str]
UNSUPPORTED_WEB_SEARCH_MODELS: list[str]
UNSUPPORTED_IMAGE_MODELS: list[str]
UNSUPPORTED_CODE_INTERPRETER_MODELS: list[str]
UNSUPPORTED_EXTENDED_CACHE_RETENTION_MODELS: list[str]
RECOMMENDED_CONVERSATION_OPTIONS: Incomplete
RECOMMENDED_AI_TASK_OPTIONS: Incomplete
