from _typeshed import Incomplete

DOMAIN: str
LOGGER: Incomplete
CONF_RECOMMENDED: str
CONF_PROMPT: str
CONF_CHAT_MODEL: str
RECOMMENDED_CHAT_MODEL: str
CONF_MAX_TOKENS: str
RECOMMENDED_MAX_TOKENS: int
CONF_TOP_P: str
RECOMMENDED_TOP_P: float
CONF_TEMPERATURE: str
RECOMMENDED_TEMPERATURE: float
