from _typeshed import Incomplete
from collections.abc import Iterator
from homeassistant.exceptions import HomeAssistantError as HomeAssistantError
from typing import Any

_LOGGER: Incomplete
_ANNOTATIONS: Incomplete
_UNSUPPORTED_KEYWORDS: Incomplete
_SELECTOR_FORMATS: Incomplete
_SCHEMA_MAPS: Incomplete
_SCHEMA_LISTS: Incomplete
_SCHEMA_VALUES: Incomplete

def adjust_schema(schema: dict[str, Any]) -> None: ...
def _walk_schemas(schema: dict[str, Any]) -> Iterator[dict[str, Any]]: ...
def _stabilize_references(schema: dict[str, Any]) -> None: ...
def _reference_parts(reference: str) -> list[str]: ...
def _resolve_reference(reference: str, root: dict[str, Any]) -> dict[str, Any]: ...
def _array_index(value: str) -> int: ...
def _flatten_all_of(schema: dict[str, Any], path: str) -> None: ...
def _adjust_reference(schema: dict[str, Any], path: str, *, nullable: bool) -> None: ...
def _adjust_schema(schema: dict[str, Any] | bool, path: str, *, nullable: bool = False) -> None: ...
def _make_nullable(schema: dict[str, Any]) -> None: ...
