from _typeshed import Incomplete
from homeassistant.const import Platform as Platform, STATE_ALARM_ARMED_AWAY as STATE_ALARM_ARMED_AWAY, STATE_ALARM_ARMED_HOME as STATE_ALARM_ARMED_HOME, STATE_ALARM_DISARMED as STATE_ALARM_DISARMED

CONF_AREA_ID: str
CONF_LOCK_CODE_DIGITS: str
DEFAULT_NAME: str
DEFAULT_AREA_ID: str
DEFAULT_LOCK_CODE_DIGITS: int
MANUFACTURER: str
MODEL: str
DOMAIN: str
DEFAULT_SCAN_INTERVAL: int
LOGGER: Incomplete
ATTR_ONLINE: str
ATTR_STATUS: str
PLATFORMS: Incomplete
STATE_MAP: Incomplete
YALE_BASE_ERRORS: Incomplete
YALE_ALL_ERRORS: Incomplete
