from .const import DEFAULT_PORT as DEFAULT_PORT, DOMAIN as DOMAIN, LOGGER as LOGGER
from homeassistant.config_entries import ConfigFlow as ConfigFlow, ConfigFlowResult as ConfigFlowResult
from homeassistant.const import CONF_HOST as CONF_HOST, CONF_MAC as CONF_MAC, CONF_PASSWORD as CONF_PASSWORD, CONF_SSL as CONF_SSL, CONF_VERIFY_SSL as CONF_VERIFY_SSL
from homeassistant.core import HomeAssistant as HomeAssistant
from homeassistant.exceptions import HomeAssistantError as HomeAssistantError
from homeassistant.helpers.aiohttp_client import async_get_clientsession as async_get_clientsession
from homeassistant.helpers.device_registry import format_mac as format_mac
from homeassistant.helpers.service_info.dhcp import DhcpServiceInfo as DhcpServiceInfo
from homeassistant.helpers.service_info.mqtt import MqttServiceInfo as MqttServiceInfo
from typing import Any

async def _validate_input(hass: HomeAssistant, data: dict[str, Any]) -> Any: ...

class FullyKioskConfigFlow(ConfigFlow, domain=DOMAIN):
    VERSION: int
    host: str
    _discovered_device_info: dict[str, Any]
    def __init__(self) -> None: ...
    async def _create_entry(self, host: str, user_input: dict[str, Any], errors: dict[str, str]) -> ConfigFlowResult | None: ...
    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_dhcp(self, discovery_info: DhcpServiceInfo) -> ConfigFlowResult: ...
    async def async_step_discovery_confirm(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_mqtt(self, discovery_info: MqttServiceInfo) -> ConfigFlowResult: ...
    async def async_step_reconfigure(self, user_input: dict[str, Any]) -> ConfigFlowResult: ...

class CannotConnect(HomeAssistantError): ...
class UnknownError(HomeAssistantError): ...
