import voluptuous as vol
from .const import CONF_API_SECRET as CONF_API_SECRET, CONF_TRACKER_INTERFACES as CONF_TRACKER_INTERFACES, DOMAIN as DOMAIN
from _typeshed import Incomplete
from homeassistant.config_entries import ConfigFlow as ConfigFlow, ConfigFlowResult as ConfigFlowResult
from homeassistant.const import CONF_API_KEY as CONF_API_KEY, CONF_URL as CONF_URL, CONF_VERIFY_SSL as CONF_VERIFY_SSL
from homeassistant.helpers.aiohttp_client import async_get_clientsession as async_get_clientsession
from homeassistant.helpers.issue_registry import IssueSeverity as IssueSeverity, async_create_issue as async_create_issue, async_delete_issue as async_delete_issue
from homeassistant.helpers.selector import SelectSelector as SelectSelector, SelectSelectorConfig as SelectSelectorConfig, SelectSelectorMode as SelectSelectorMode
from typing import Any, override

_LOGGER: Incomplete
STEP_USER_DATA_SCHEMA: Incomplete

def tracker_interfaces_schema(interfaces: list[str], selected: list[str] | None = None) -> vol.Schema: ...

class OPNsenseConfigFlow(ConfigFlow, domain=DOMAIN):
    available_interfaces: list[str] | None
    _entry_data: dict[str, Any]
    def __init__(self) -> None: ...
    async def _show_setup_form(self, user_input: dict[Any, Any] | None = None, errors: dict[Any, Any] | None = None) -> ConfigFlowResult: ...
    async def _show_interfaces_form(self, user_input: dict[Any, Any], errors: dict[Any, Any] | None = None) -> ConfigFlowResult: ...
    @override
    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_interfaces(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_import(self, import_data: dict[str, Any]) -> ConfigFlowResult: ...
    def _abort_import(self, reason: str) -> ConfigFlowResult: ...
