from . import Adapter as Adapter, async_get_adapters as async_get_adapters, async_get_announce_addresses as async_get_announce_addresses
from .models import IPv4ConfiguredAddress as IPv4ConfiguredAddress, IPv6ConfiguredAddress as IPv6ConfiguredAddress
from homeassistant.components import system_health as system_health
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from typing import Any

@callback
def async_register(hass: HomeAssistant, register: system_health.SystemHealthRegistration) -> None: ...
def _format_ips(ips: list[IPv4ConfiguredAddress] | list[IPv6ConfiguredAddress]) -> str: ...
def _get_adapter_info(adapter: Adapter) -> str: ...
async def system_health_info(hass: HomeAssistant) -> dict[str, Any]: ...
