from _typeshed import Incomplete

DOMAIN: str
CONF_ALLOW_SERVICE_CALLS: str
CONF_SUBSCRIBE_LOGS: str
CONF_DEVICE_NAME: str
CONF_NOISE_PSK: str
CONF_BLUETOOTH_MAC_ADDRESS: str
DEFAULT_ALLOW_SERVICE_CALLS: bool
DEFAULT_NEW_CONFIG_ALLOW_ALLOW_SERVICE_CALLS: bool
STABLE_BLE_VERSION_STR: str
STABLE_BLE_VERSION: Incomplete
PROJECT_URLS: Incomplete
STABLE_BLE_URL_VERSION: Incomplete
DEFAULT_URL: Incomplete
DATA_FFMPEG_PROXY: Incomplete
