from _typeshed import Incomplete

DOMAIN: str
CONF_ALLOW_SERVICE_CALLS: str
CONF_DEVICE_NAME: str
CONF_NOISE_PSK: str
DEFAULT_ALLOW_SERVICE_CALLS: bool
DEFAULT_NEW_CONFIG_ALLOW_ALLOW_SERVICE_CALLS: bool
STABLE_BLE_VERSION_STR: str
STABLE_BLE_VERSION: Incomplete
PROJECT_URLS: Incomplete
DEFAULT_URL: Incomplete
DATA_FFMPEG_PROXY: Incomplete
