from .const import DEFAULT_NAME as DEFAULT_NAME, DEFAULT_PORT as DEFAULT_PORT, DISCOVERY_TIMEOUT as DISCOVERY_TIMEOUT, DOMAIN as DOMAIN
from .coordinator import async_get_listener_registry as async_get_listener_registry
from _typeshed import Incomplete
from bitvis_protobuf.parse import PayloadDiagnostic as PayloadDiagnostic, PayloadSample as PayloadSample
from homeassistant.config_entries import ConfigFlow as ConfigFlow, ConfigFlowResult as ConfigFlowResult
from homeassistant.const import CONF_HOST as CONF_HOST, CONF_PORT as CONF_PORT
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.data_entry_flow import AbortFlow as AbortFlow
from homeassistant.helpers.device_registry import format_mac as format_mac
from homeassistant.helpers.service_info.zeroconf import ZeroconfServiceInfo as ZeroconfServiceInfo
from typing import Any, Self, override

_LOGGER: Incomplete
STEP_USER_DATA_SCHEMA: Incomplete

def _get_friendly_name(name: str | None) -> str: ...
async def _async_test_port(hass: HomeAssistant, port: int) -> None: ...
async def _async_discover_mac_address(hass: HomeAssistant, host: str, port: int) -> str: ...

class BitvisConfigFlow(ConfigFlow, domain=DOMAIN):
    _discovery_info: ZeroconfServiceInfo | None
    _validated_host: str | None
    _host: str | None
    def __init__(self) -> None: ...
    @override
    def is_matching(self, other_flow: Self) -> bool: ...
    async def _async_validate_host(self, host: str) -> str: ...
    async def _async_create_entry_from_host(self, host: str, title: str) -> ConfigFlowResult: ...
    @override
    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    @override
    async def async_step_zeroconf(self, discovery_info: ZeroconfServiceInfo) -> ConfigFlowResult: ...
    async def async_step_zeroconf_confirm(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
