from typing import Any

class Diagnostics:
    _counter: Any
    _values: Any
    def __init__(self) -> None: ...
    def increment(self, key: str) -> None: ...
    def set_value(self, key: str, value: Any) -> None: ...
    def as_dict(self) -> dict[str, Any]: ...
