from collections import Counter
from typing import Any

class Diagnostics:
    _counter: Counter
    _values: dict[str, Any]
    def __init__(self) -> None: ...
    def increment(self, key: str) -> None: ...
    def set_value(self, key: str, value: Any) -> None: ...
    def as_dict(self) -> dict[str, Any]: ...
