from _typeshed import Incomplete
from homeassistant.const import Platform as Platform

LOGGER: Incomplete
DOMAIN: str
PLATFORMS: Incomplete
CONF_SITE_ID: str
UNIFI_WIRELESS_CLIENTS: str
CONF_ALLOW_BANDWIDTH_SENSORS: str
CONF_ALLOW_UPTIME_SENSORS: str
CONF_BLOCK_CLIENT: str
CONF_DETECTION_TIME: str
CONF_DPI_RESTRICTIONS: str
CONF_IGNORE_WIRED_BUG: str
CONF_TRACK_CLIENTS: str
CONF_TRACK_DEVICES: str
CONF_TRACK_WIRED_CLIENTS: str
CONF_SSID_FILTER: str
DEFAULT_ALLOW_BANDWIDTH_SENSORS: bool
DEFAULT_ALLOW_UPTIME_SENSORS: bool
DEFAULT_DPI_RESTRICTIONS: bool
DEFAULT_IGNORE_WIRED_BUG: bool
DEFAULT_TRACK_CLIENTS: bool
DEFAULT_TRACK_DEVICES: bool
DEFAULT_TRACK_WIRED_CLIENTS: bool
DEFAULT_DETECTION_TIME: int
ATTR_MANUFACTURER: str
BLOCK_SWITCH: str
DPI_SWITCH: str
OUTLET_SWITCH: str
