from ..db_schema import RecorderRuns as RecorderRuns
from _typeshed import Incomplete
from datetime import datetime
from sqlalchemy.orm.session import Session as Session

class RecorderRunsManager:
    _recording_start: Incomplete
    _current_run_info: RecorderRuns | None
    _first_run: RecorderRuns | None
    def __init__(self) -> None: ...
    @property
    def recording_start(self) -> datetime: ...
    @property
    def first(self) -> RecorderRuns: ...
    @property
    def current(self) -> RecorderRuns: ...
    @property
    def active(self) -> bool: ...
    def start(self, session: Session) -> None: ...
    def reset(self) -> None: ...
    def end(self, session: Session) -> None: ...
    def load_from_db(self, session: Session) -> None: ...
    def clear(self) -> None: ...
