from .const import CONF_PORT_IPV6 as CONF_PORT_IPV6, DEFAULT_PORT as DEFAULT_PORT, PLATFORMS as PLATFORMS
from homeassistant.config_entries import ConfigEntry as ConfigEntry
from homeassistant.const import CONF_PORT as CONF_PORT
from homeassistant.core import HomeAssistant as HomeAssistant, _LOGGER as _LOGGER

async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool: ...
async def update_listener(hass: HomeAssistant, entry: ConfigEntry) -> None: ...
async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool: ...
async def async_migrate_entry(hass: HomeAssistant, config_entry: ConfigEntry) -> bool: ...
