from typing import Final

DOMAIN: str
ATTR_SENDER: Final[str]
ATTR_ITEM_NAME: Final[str]
ATTR_NOTIFICATION_TYPE: Final[str]
ATTR_REACTION: Final[str]
ATTR_ACTIVITY: Final[str]
ATTR_RECEIVER: Final[str]
SERVICE_PUSH_NOTIFICATION: str
SERVICE_ACTIVITY_STREAM_REACTION: str
