from aiorussound import RussoundClient as RussoundClient, Zone as Zone
from homeassistant.components.media_player import BrowseMedia as BrowseMedia, MediaClass as MediaClass
from homeassistant.core import HomeAssistant as HomeAssistant

async def async_browse_media(hass: HomeAssistant, client: RussoundClient, media_content_id: str | None, media_content_type: str | None, zone: Zone) -> BrowseMedia: ...
async def _root_payload(hass: HomeAssistant, presets_by_zone: dict[int, dict[int, str]]) -> BrowseMedia: ...
async def _presets_payload(presets_by_zone: dict[int, dict[int, str]]) -> BrowseMedia: ...
def _find_presets_by_zone(client: RussoundClient, zone: Zone) -> dict[int, dict[int, str]]: ...
