from .const import DOMAIN as DOMAIN
from .coordinator import NetatmoConfigEntry as NetatmoConfigEntry, async_get_loaded_entry as async_get_loaded_entry
from .webhook import async_register_webhook as async_register_webhook, async_unregister_webhook as async_unregister_webhook
from homeassistant.core import HomeAssistant as HomeAssistant, ServiceCall as ServiceCall, callback as callback
from homeassistant.exceptions import ServiceValidationError as ServiceValidationError

SERVICE_REGISTER_WEBHOOK: str
SERVICE_UNREGISTER_WEBHOOK: str

def _get_loaded_entry(hass: HomeAssistant) -> NetatmoConfigEntry: ...
def _deprecate(hass: HomeAssistant, service: str) -> None: ...
async def _register_webhook(call: ServiceCall) -> None: ...
async def _unregister_webhook(call: ServiceCall) -> None: ...
@callback
def async_setup_services(hass: HomeAssistant) -> None: ...
