from _typeshed import Incomplete
from homeassistant.helpers.deprecation import DeprecatedAlias as DeprecatedAlias, all_with_deprecated_constants as all_with_deprecated_constants, check_if_deprecated_constant as check_if_deprecated_constant, dir_with_deprecated_constants as dir_with_deprecated_constants

_DEPRECATED_StrEnum: Incomplete
__getattr__: Incomplete
__dir__: Incomplete
__all__: Incomplete
