from .const import CONF_DIMMER as CONF_DIMMER, CONF_LIGHT as CONF_LIGHT, CONF_STRIP as CONF_STRIP, CONF_SWITCH as CONF_SWITCH, DOMAIN as DOMAIN
from homeassistant import config_entries as config_entries
from homeassistant.config_entries import ConfigEntry as ConfigEntry
from homeassistant.const import CONF_HOST as CONF_HOST, CONF_MAC as CONF_MAC, CONF_NAME as CONF_NAME, EVENT_HOMEASSISTANT_STARTED as EVENT_HOMEASSISTANT_STARTED
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.helpers.typing import ConfigType as ConfigType
from types import MappingProxyType
from typing import Any

async def async_cleanup_legacy_entry(hass: HomeAssistant, legacy_entry_id: str) -> None: ...
def async_migrate_legacy_entries(hass: HomeAssistant, hosts_by_mac: dict[str, str], config_entries_by_mac: dict[str, ConfigEntry], legacy_entry: ConfigEntry) -> None: ...
def async_migrate_yaml_entries(hass: HomeAssistant, conf: Union[ConfigType, MappingProxyType[str, Any]]) -> None: ...
async def async_migrate_entities_devices(hass: HomeAssistant, legacy_entry_id: str, new_entry: ConfigEntry) -> None: ...
