from _typeshed import Incomplete
from homeassistant.const import Platform as Platform

DOMAIN: str
ATTR_EVENT_SCORE: str
ATTR_EVENT_ID: str
ATTR_WIDTH: str
ATTR_HEIGHT: str
ATTR_FPS: str
ATTR_BITRATE: str
ATTR_CHANNEL_ID: str
ATTR_MESSAGE: str
ATTR_DURATION: str
ATTR_ANONYMIZE: str
CONF_DISABLE_RTSP: str
CONF_ALL_UPDATES: str
CONF_OVERRIDE_CHOST: str
CONF_MAX_MEDIA: str
CONF_ALLOW_EA: str
CONFIG_OPTIONS: Incomplete
DEFAULT_PORT: int
DEFAULT_ATTRIBUTION: str
DEFAULT_BRAND: str
DEFAULT_SCAN_INTERVAL: int
DEFAULT_VERIFY_SSL: bool
DEFAULT_MAX_MEDIA: int
DEVICES_THAT_ADOPT: Incomplete
DEVICES_WITH_ENTITIES: Incomplete
DEVICES_FOR_SUBSCRIBE: Incomplete
MIN_REQUIRED_PROTECT_V: Incomplete
OUTDATED_LOG_MESSAGE: str
TYPE_EMPTY_VALUE: str
PLATFORMS: Incomplete
DISPATCH_ADD: str
DISPATCH_ADOPT: str
DISPATCH_CHANNELS: str
