from .const import DOMAIN as DOMAIN
from .coordinator import LockData as LockData, SchlageConfigEntry as SchlageConfigEntry, SchlageDataUpdateCoordinator as SchlageDataUpdateCoordinator
from .entity import SchlageEntity as SchlageEntity
from _typeshed import Incomplete
from homeassistant.components.lock import LockEntity as LockEntity
from homeassistant.core import HomeAssistant as HomeAssistant, ServiceResponse as ServiceResponse, callback as callback
from homeassistant.exceptions import HomeAssistantError as HomeAssistantError, ServiceValidationError as ServiceValidationError
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback as AddConfigEntryEntitiesCallback
from pyschlage.code import AccessCode
from typing import Any

async def async_setup_entry(hass: HomeAssistant, config_entry: SchlageConfigEntry, async_add_entities: AddConfigEntryEntitiesCallback) -> None: ...

class SchlageLockEntity(SchlageEntity, LockEntity):
    _attr_name: Incomplete
    def __init__(self, coordinator: SchlageDataUpdateCoordinator, device_id: str) -> None: ...
    @callback
    def _handle_coordinator_update(self) -> None: ...
    _attr_is_locked: Incomplete
    _attr_is_jammed: Incomplete
    _attr_changed_by: Incomplete
    def _update_attrs(self) -> None: ...
    async def async_lock(self, **kwargs: Any) -> None: ...
    async def async_unlock(self, **kwargs: Any) -> None: ...
    @staticmethod
    def _normalize_code_name(name: str) -> str: ...
    def _validate_code_name(self, codes: dict[str, AccessCode] | None, name: str) -> None: ...
    def _validate_code_value(self, codes: dict[str, AccessCode] | None, code: str) -> None: ...
    async def _async_fetch_access_codes(self) -> dict[str, AccessCode] | None: ...
    async def add_code(self, name: str, code: str, notify_on_use: bool = True) -> None: ...
    async def delete_code(self, name: str) -> None: ...
    async def get_codes(self) -> ServiceResponse: ...
