from _typeshed import Incomplete

DOMAIN: str
CONF_DNSMASQ: str
CONF_INTERFACE: str
CONF_REQUIRE_IP: str
CONF_SSH_KEY: str
CONF_TRACK_UNKNOWN: str
DEFAULT_DNSMASQ: str
DEFAULT_INTERFACE: str
DEFAULT_TRACK_UNKNOWN: bool
KEY_COORDINATOR: str
KEY_METHOD: str
KEY_SENSORS: str
MODE_AP: str
MODE_ROUTER: str
PROTOCOL_HTTP: str
PROTOCOL_HTTPS: str
PROTOCOL_SSH: str
PROTOCOL_TELNET: str
SENSORS_BYTES: Incomplete
SENSORS_CONNECTED_DEVICE: Incomplete
SENSORS_LOAD_AVG: Incomplete
SENSORS_RATES: Incomplete
SENSORS_TEMPERATURES_LEGACY: Incomplete
SENSORS_TEMPERATURES: Incomplete
