from typing import Any

DOMAIN: str
CONF_DNSMASQ: str
CONF_INTERFACE: str
CONF_REQUIRE_IP: str
CONF_SSH_KEY: str
CONF_TRACK_UNKNOWN: str
DATA_ASUSWRT = DOMAIN
DEFAULT_DNSMASQ: str
DEFAULT_INTERFACE: str
DEFAULT_TRACK_UNKNOWN: bool
MODE_AP: str
MODE_ROUTER: str
PROTOCOL_SSH: str
PROTOCOL_TELNET: str
SENSORS_BYTES: Any
SENSORS_CONNECTED_DEVICE: Any
SENSORS_LOAD_AVG: Any
SENSORS_RATES: Any
SENSORS_TEMPERATURES: Any
