from .const import DOMAIN as DOMAIN
from .error import MediaSourceError as MediaSourceError, Unresolvable as Unresolvable
from .models import BrowseMediaSource as BrowseMediaSource, MediaSourceItem as MediaSourceItem, PlayMedia as PlayMedia
from collections.abc import Callable
from homeassistant.components.media_player import BrowseMedia
from homeassistant.core import HomeAssistant

def is_media_source_id(media_content_id: str) -> bool: ...
def generate_media_source_id(domain: str, identifier: str) -> str: ...
async def async_browse_media(hass: HomeAssistant, media_content_id: Union[str, None], *, content_filter: Union[Callable[[BrowseMedia], bool], None] = ...) -> BrowseMediaSource: ...
async def async_resolve_media(hass: HomeAssistant, media_content_id: str) -> PlayMedia: ...
