from homeassistant.exceptions import HomeAssistantError as HomeAssistantError

class MediaSourceError(HomeAssistantError): ...
class Unresolvable(MediaSourceError): ...
class UnknownMediaSource(MediaSourceError, ValueError): ...
