from .const import DOMAIN as DOMAIN, MAP_FILENAME_SUFFIX as MAP_FILENAME_SUFFIX
from _typeshed import Incomplete
from homeassistant.core import HomeAssistant as HomeAssistant
from pathlib import Path

_LOGGER: Incomplete
STORAGE_PATH: Incomplete
MAPS_PATH: str

def _storage_path_prefix(hass: HomeAssistant, entry_id: str) -> Path: ...

class RoborockMapStorage:
    _hass: Incomplete
    _path_prefix: Incomplete
    _write_queue: dict[int, bytes]
    def __init__(self, hass: HomeAssistant, entry_id: str, device_id_slug: str) -> None: ...
    async def async_load_map(self, map_flag: int) -> bytes | None: ...
    def _load_map(self, filename: Path) -> bytes | None: ...
    async def async_save_map(self, map_flag: int, content: bytes) -> None: ...
    async def flush(self) -> None: ...
    def _save_map(self, filename: Path, content: bytes) -> None: ...

async def async_remove_map_storage(hass: HomeAssistant, entry_id: str) -> None: ...
