from .const import DOMAIN as DOMAIN
from _typeshed import Incomplete
from homeassistant.core import HomeAssistant as HomeAssistant
from homeassistant.helpers.storage import Store as Store
from pathlib import Path
from roborock.devices.cache import Cache, CacheData

_LOGGER: Incomplete
STORAGE_PATH: Incomplete
MAPS_PATH: str
CACHE_VERSION: int

def _storage_path_prefix(hass: HomeAssistant, entry_id: str) -> Path: ...
async def async_cleanup_map_storage(hass: HomeAssistant, entry_id: str) -> None: ...

class CacheStore(Cache):
    _cache_store: Incomplete
    _cache_data: CacheData | None
    def __init__(self, hass: HomeAssistant, entry_id: str) -> None: ...
    async def get(self) -> CacheData: ...
    async def set(self, value: CacheData) -> None: ...
    async def flush(self) -> None: ...
    async def async_remove(self) -> None: ...
