from _typeshed import Incomplete
from datetime import datetime
from homeassistant.components.valve import ValveEntity as ValveEntity, ValveEntityFeature as ValveEntityFeature, ValveState as ValveState
from homeassistant.config_entries import ConfigEntry as ConfigEntry
from homeassistant.core import CALLBACK_TYPE as CALLBACK_TYPE, HomeAssistant as HomeAssistant, callback as callback
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback as AddConfigEntryEntitiesCallback
from homeassistant.helpers.event import async_track_utc_time_change as async_track_utc_time_change
from typing import Any

OPEN_CLOSE_DELAY: int

async def async_setup_entry(hass: HomeAssistant, config_entry: ConfigEntry, async_add_entities: AddConfigEntryEntitiesCallback) -> None: ...

class DemoValve(ValveEntity):
    _attr_should_poll: bool
    _attr_name: Incomplete
    _attr_supported_features: Incomplete
    _state: Incomplete
    _moveable: Incomplete
    _attr_reports_position: bool
    _unsub_listener_valve: CALLBACK_TYPE | None
    _set_position: int
    _position: int
    def __init__(self, name: str, state: str, moveable: bool = True, position: int | None = None) -> None: ...
    @property
    def current_valve_position(self) -> int: ...
    @property
    def is_opening(self) -> bool: ...
    @property
    def is_closing(self) -> bool: ...
    @property
    def is_closed(self) -> bool: ...
    async def async_open_valve(self, **kwargs: Any) -> None: ...
    async def async_close_valve(self, **kwargs: Any) -> None: ...
    async def async_stop_valve(self) -> None: ...
    async def async_set_valve_position(self, position: int) -> None: ...
    @callback
    def _listen_valve(self) -> None: ...
    async def _time_changed_valve(self, now: datetime) -> None: ...
