import asyncio
import voluptuous as vol
from .addon import get_addon_manager as get_addon_manager
from .client import MqttClientSetup as MqttClientSetup
from .const import ALARM_CONTROL_PANEL_SUPPORTED_FEATURES as ALARM_CONTROL_PANEL_SUPPORTED_FEATURES, ATTR_PAYLOAD as ATTR_PAYLOAD, ATTR_QOS as ATTR_QOS, ATTR_RETAIN as ATTR_RETAIN, ATTR_TOPIC as ATTR_TOPIC, CONFIG_ENTRY_MINOR_VERSION as CONFIG_ENTRY_MINOR_VERSION, CONFIG_ENTRY_VERSION as CONFIG_ENTRY_VERSION, CONF_ACTION_TEMPLATE as CONF_ACTION_TEMPLATE, CONF_ACTION_TOPIC as CONF_ACTION_TOPIC, CONF_AVAILABILITY_TEMPLATE as CONF_AVAILABILITY_TEMPLATE, CONF_AVAILABILITY_TOPIC as CONF_AVAILABILITY_TOPIC, CONF_AVAILABLE_TONES as CONF_AVAILABLE_TONES, CONF_BIRTH_MESSAGE as CONF_BIRTH_MESSAGE, CONF_BLUE_TEMPLATE as CONF_BLUE_TEMPLATE, CONF_BRIGHTNESS_COMMAND_TEMPLATE as CONF_BRIGHTNESS_COMMAND_TEMPLATE, CONF_BRIGHTNESS_COMMAND_TOPIC as CONF_BRIGHTNESS_COMMAND_TOPIC, CONF_BRIGHTNESS_SCALE as CONF_BRIGHTNESS_SCALE, CONF_BRIGHTNESS_STATE_TOPIC as CONF_BRIGHTNESS_STATE_TOPIC, CONF_BRIGHTNESS_TEMPLATE as CONF_BRIGHTNESS_TEMPLATE, CONF_BRIGHTNESS_VALUE_TEMPLATE as CONF_BRIGHTNESS_VALUE_TEMPLATE, CONF_BROKER as CONF_BROKER, CONF_CERTIFICATE as CONF_CERTIFICATE, CONF_CLIENT_CERT as CONF_CLIENT_CERT, CONF_CLIENT_KEY as CONF_CLIENT_KEY, CONF_CODE_ARM_REQUIRED as CONF_CODE_ARM_REQUIRED, CONF_CODE_DISARM_REQUIRED as CONF_CODE_DISARM_REQUIRED, CONF_CODE_FORMAT as CONF_CODE_FORMAT, CONF_CODE_TRIGGER_REQUIRED as CONF_CODE_TRIGGER_REQUIRED, CONF_COLOR_MODE_STATE_TOPIC as CONF_COLOR_MODE_STATE_TOPIC, CONF_COLOR_MODE_VALUE_TEMPLATE as CONF_COLOR_MODE_VALUE_TEMPLATE, CONF_COLOR_TEMP_COMMAND_TEMPLATE as CONF_COLOR_TEMP_COMMAND_TEMPLATE, CONF_COLOR_TEMP_COMMAND_TOPIC as CONF_COLOR_TEMP_COMMAND_TOPIC, CONF_COLOR_TEMP_KELVIN as CONF_COLOR_TEMP_KELVIN, CONF_COLOR_TEMP_STATE_TOPIC as CONF_COLOR_TEMP_STATE_TOPIC, CONF_COLOR_TEMP_TEMPLATE as CONF_COLOR_TEMP_TEMPLATE, CONF_COLOR_TEMP_VALUE_TEMPLATE as CONF_COLOR_TEMP_VALUE_TEMPLATE, CONF_COMMAND_OFF_TEMPLATE as CONF_COMMAND_OFF_TEMPLATE, CONF_COMMAND_ON_TEMPLATE as CONF_COMMAND_ON_TEMPLATE, CONF_COMMAND_TEMPLATE as CONF_COMMAND_TEMPLATE, CONF_COMMAND_TOPIC as CONF_COMMAND_TOPIC, CONF_CONTENT_TYPE as CONF_CONTENT_TYPE, CONF_CURRENT_HUMIDITY_TEMPLATE as CONF_CURRENT_HUMIDITY_TEMPLATE, CONF_CURRENT_HUMIDITY_TOPIC as CONF_CURRENT_HUMIDITY_TOPIC, CONF_CURRENT_TEMP_TEMPLATE as CONF_CURRENT_TEMP_TEMPLATE, CONF_CURRENT_TEMP_TOPIC as CONF_CURRENT_TEMP_TOPIC, CONF_DIRECTION_COMMAND_TEMPLATE as CONF_DIRECTION_COMMAND_TEMPLATE, CONF_DIRECTION_COMMAND_TOPIC as CONF_DIRECTION_COMMAND_TOPIC, CONF_DIRECTION_STATE_TOPIC as CONF_DIRECTION_STATE_TOPIC, CONF_DIRECTION_VALUE_TEMPLATE as CONF_DIRECTION_VALUE_TEMPLATE, CONF_DISCOVERY_PREFIX as CONF_DISCOVERY_PREFIX, CONF_EFFECT_COMMAND_TEMPLATE as CONF_EFFECT_COMMAND_TEMPLATE, CONF_EFFECT_COMMAND_TOPIC as CONF_EFFECT_COMMAND_TOPIC, CONF_EFFECT_LIST as CONF_EFFECT_LIST, CONF_EFFECT_STATE_TOPIC as CONF_EFFECT_STATE_TOPIC, CONF_EFFECT_TEMPLATE as CONF_EFFECT_TEMPLATE, CONF_EFFECT_VALUE_TEMPLATE as CONF_EFFECT_VALUE_TEMPLATE, CONF_ENTITY_PICTURE as CONF_ENTITY_PICTURE, CONF_EXPIRE_AFTER as CONF_EXPIRE_AFTER, CONF_FAN_MODE_COMMAND_TEMPLATE as CONF_FAN_MODE_COMMAND_TEMPLATE, CONF_FAN_MODE_COMMAND_TOPIC as CONF_FAN_MODE_COMMAND_TOPIC, CONF_FAN_MODE_LIST as CONF_FAN_MODE_LIST, CONF_FAN_MODE_STATE_TEMPLATE as CONF_FAN_MODE_STATE_TEMPLATE, CONF_FAN_MODE_STATE_TOPIC as CONF_FAN_MODE_STATE_TOPIC, CONF_FLASH as CONF_FLASH, CONF_FLASH_TIME_LONG as CONF_FLASH_TIME_LONG, CONF_FLASH_TIME_SHORT as CONF_FLASH_TIME_SHORT, CONF_GET_POSITION_TEMPLATE as CONF_GET_POSITION_TEMPLATE, CONF_GET_POSITION_TOPIC as CONF_GET_POSITION_TOPIC, CONF_GREEN_TEMPLATE as CONF_GREEN_TEMPLATE, CONF_HS_COMMAND_TEMPLATE as CONF_HS_COMMAND_TEMPLATE, CONF_HS_COMMAND_TOPIC as CONF_HS_COMMAND_TOPIC, CONF_HS_STATE_TOPIC as CONF_HS_STATE_TOPIC, CONF_HS_VALUE_TEMPLATE as CONF_HS_VALUE_TEMPLATE, CONF_HUMIDITY_COMMAND_TEMPLATE as CONF_HUMIDITY_COMMAND_TEMPLATE, CONF_HUMIDITY_COMMAND_TOPIC as CONF_HUMIDITY_COMMAND_TOPIC, CONF_HUMIDITY_MAX as CONF_HUMIDITY_MAX, CONF_HUMIDITY_MIN as CONF_HUMIDITY_MIN, CONF_HUMIDITY_STATE_TEMPLATE as CONF_HUMIDITY_STATE_TEMPLATE, CONF_HUMIDITY_STATE_TOPIC as CONF_HUMIDITY_STATE_TOPIC, CONF_IMAGE_ENCODING as CONF_IMAGE_ENCODING, CONF_IMAGE_TOPIC as CONF_IMAGE_TOPIC, CONF_KEEPALIVE as CONF_KEEPALIVE, CONF_LAST_RESET_VALUE_TEMPLATE as CONF_LAST_RESET_VALUE_TEMPLATE, CONF_MAX as CONF_MAX, CONF_MAX_KELVIN as CONF_MAX_KELVIN, CONF_MIN as CONF_MIN, CONF_MIN_KELVIN as CONF_MIN_KELVIN, CONF_MODE_COMMAND_TEMPLATE as CONF_MODE_COMMAND_TEMPLATE, CONF_MODE_COMMAND_TOPIC as CONF_MODE_COMMAND_TOPIC, CONF_MODE_LIST as CONF_MODE_LIST, CONF_MODE_STATE_TEMPLATE as CONF_MODE_STATE_TEMPLATE, CONF_MODE_STATE_TOPIC as CONF_MODE_STATE_TOPIC, CONF_OFF_DELAY as CONF_OFF_DELAY, CONF_ON_COMMAND_TYPE as CONF_ON_COMMAND_TYPE, CONF_OPTIONS as CONF_OPTIONS, CONF_OSCILLATION_COMMAND_TEMPLATE as CONF_OSCILLATION_COMMAND_TEMPLATE, CONF_OSCILLATION_COMMAND_TOPIC as CONF_OSCILLATION_COMMAND_TOPIC, CONF_OSCILLATION_STATE_TOPIC as CONF_OSCILLATION_STATE_TOPIC, CONF_OSCILLATION_VALUE_TEMPLATE as CONF_OSCILLATION_VALUE_TEMPLATE, CONF_PATTERN as CONF_PATTERN, CONF_PAYLOAD_ARM_AWAY as CONF_PAYLOAD_ARM_AWAY, CONF_PAYLOAD_ARM_CUSTOM_BYPASS as CONF_PAYLOAD_ARM_CUSTOM_BYPASS, CONF_PAYLOAD_ARM_HOME as CONF_PAYLOAD_ARM_HOME, CONF_PAYLOAD_ARM_NIGHT as CONF_PAYLOAD_ARM_NIGHT, CONF_PAYLOAD_ARM_VACATION as CONF_PAYLOAD_ARM_VACATION, CONF_PAYLOAD_AVAILABLE as CONF_PAYLOAD_AVAILABLE, CONF_PAYLOAD_CLOSE as CONF_PAYLOAD_CLOSE, CONF_PAYLOAD_LOCK as CONF_PAYLOAD_LOCK, CONF_PAYLOAD_NOT_AVAILABLE as CONF_PAYLOAD_NOT_AVAILABLE, CONF_PAYLOAD_OPEN as CONF_PAYLOAD_OPEN, CONF_PAYLOAD_OSCILLATION_OFF as CONF_PAYLOAD_OSCILLATION_OFF, CONF_PAYLOAD_OSCILLATION_ON as CONF_PAYLOAD_OSCILLATION_ON, CONF_PAYLOAD_PRESS as CONF_PAYLOAD_PRESS, CONF_PAYLOAD_RESET as CONF_PAYLOAD_RESET, CONF_PAYLOAD_RESET_PERCENTAGE as CONF_PAYLOAD_RESET_PERCENTAGE, CONF_PAYLOAD_RESET_PRESET_MODE as CONF_PAYLOAD_RESET_PRESET_MODE, CONF_PAYLOAD_STOP as CONF_PAYLOAD_STOP, CONF_PAYLOAD_STOP_TILT as CONF_PAYLOAD_STOP_TILT, CONF_PAYLOAD_TRIGGER as CONF_PAYLOAD_TRIGGER, CONF_PAYLOAD_UNLOCK as CONF_PAYLOAD_UNLOCK, CONF_PERCENTAGE_COMMAND_TEMPLATE as CONF_PERCENTAGE_COMMAND_TEMPLATE, CONF_PERCENTAGE_COMMAND_TOPIC as CONF_PERCENTAGE_COMMAND_TOPIC, CONF_PERCENTAGE_STATE_TOPIC as CONF_PERCENTAGE_STATE_TOPIC, CONF_PERCENTAGE_VALUE_TEMPLATE as CONF_PERCENTAGE_VALUE_TEMPLATE, CONF_POSITION_CLOSED as CONF_POSITION_CLOSED, CONF_POSITION_OPEN as CONF_POSITION_OPEN, CONF_POWER_COMMAND_TEMPLATE as CONF_POWER_COMMAND_TEMPLATE, CONF_POWER_COMMAND_TOPIC as CONF_POWER_COMMAND_TOPIC, CONF_PRECISION as CONF_PRECISION, CONF_PRESET_MODES_LIST as CONF_PRESET_MODES_LIST, CONF_PRESET_MODE_COMMAND_TEMPLATE as CONF_PRESET_MODE_COMMAND_TEMPLATE, CONF_PRESET_MODE_COMMAND_TOPIC as CONF_PRESET_MODE_COMMAND_TOPIC, CONF_PRESET_MODE_STATE_TOPIC as CONF_PRESET_MODE_STATE_TOPIC, CONF_PRESET_MODE_VALUE_TEMPLATE as CONF_PRESET_MODE_VALUE_TEMPLATE, CONF_QOS as CONF_QOS, CONF_RED_TEMPLATE as CONF_RED_TEMPLATE, CONF_REPORTS_POSITION as CONF_REPORTS_POSITION, CONF_RETAIN as CONF_RETAIN, CONF_RGBWW_COMMAND_TEMPLATE as CONF_RGBWW_COMMAND_TEMPLATE, CONF_RGBWW_COMMAND_TOPIC as CONF_RGBWW_COMMAND_TOPIC, CONF_RGBWW_STATE_TOPIC as CONF_RGBWW_STATE_TOPIC, CONF_RGBWW_VALUE_TEMPLATE as CONF_RGBWW_VALUE_TEMPLATE, CONF_RGBW_COMMAND_TEMPLATE as CONF_RGBW_COMMAND_TEMPLATE, CONF_RGBW_COMMAND_TOPIC as CONF_RGBW_COMMAND_TOPIC, CONF_RGBW_STATE_TOPIC as CONF_RGBW_STATE_TOPIC, CONF_RGBW_VALUE_TEMPLATE as CONF_RGBW_VALUE_TEMPLATE, CONF_RGB_COMMAND_TEMPLATE as CONF_RGB_COMMAND_TEMPLATE, CONF_RGB_COMMAND_TOPIC as CONF_RGB_COMMAND_TOPIC, CONF_RGB_STATE_TOPIC as CONF_RGB_STATE_TOPIC, CONF_RGB_VALUE_TEMPLATE as CONF_RGB_VALUE_TEMPLATE, CONF_SCHEMA as CONF_SCHEMA, CONF_SET_POSITION_TEMPLATE as CONF_SET_POSITION_TEMPLATE, CONF_SET_POSITION_TOPIC as CONF_SET_POSITION_TOPIC, CONF_SPEED_RANGE_MAX as CONF_SPEED_RANGE_MAX, CONF_SPEED_RANGE_MIN as CONF_SPEED_RANGE_MIN, CONF_STATE_CLOSED as CONF_STATE_CLOSED, CONF_STATE_CLOSING as CONF_STATE_CLOSING, CONF_STATE_JAMMED as CONF_STATE_JAMMED, CONF_STATE_LOCKED as CONF_STATE_LOCKED, CONF_STATE_LOCKING as CONF_STATE_LOCKING, CONF_STATE_OFF as CONF_STATE_OFF, CONF_STATE_ON as CONF_STATE_ON, CONF_STATE_OPEN as CONF_STATE_OPEN, CONF_STATE_OPENING as CONF_STATE_OPENING, CONF_STATE_STOPPED as CONF_STATE_STOPPED, CONF_STATE_TOPIC as CONF_STATE_TOPIC, CONF_STATE_UNLOCKED as CONF_STATE_UNLOCKED, CONF_STATE_UNLOCKING as CONF_STATE_UNLOCKING, CONF_STATE_VALUE_TEMPLATE as CONF_STATE_VALUE_TEMPLATE, CONF_STEP as CONF_STEP, CONF_SUGGESTED_DISPLAY_PRECISION as CONF_SUGGESTED_DISPLAY_PRECISION, CONF_SUPPORTED_COLOR_MODES as CONF_SUPPORTED_COLOR_MODES, CONF_SUPPORTED_FEATURES as CONF_SUPPORTED_FEATURES, CONF_SUPPORT_DURATION as CONF_SUPPORT_DURATION, CONF_SUPPORT_VOLUME_SET as CONF_SUPPORT_VOLUME_SET, CONF_SWING_HORIZONTAL_MODE_COMMAND_TEMPLATE as CONF_SWING_HORIZONTAL_MODE_COMMAND_TEMPLATE, CONF_SWING_HORIZONTAL_MODE_COMMAND_TOPIC as CONF_SWING_HORIZONTAL_MODE_COMMAND_TOPIC, CONF_SWING_HORIZONTAL_MODE_LIST as CONF_SWING_HORIZONTAL_MODE_LIST, CONF_SWING_HORIZONTAL_MODE_STATE_TEMPLATE as CONF_SWING_HORIZONTAL_MODE_STATE_TEMPLATE, CONF_SWING_HORIZONTAL_MODE_STATE_TOPIC as CONF_SWING_HORIZONTAL_MODE_STATE_TOPIC, CONF_SWING_MODE_COMMAND_TEMPLATE as CONF_SWING_MODE_COMMAND_TEMPLATE, CONF_SWING_MODE_COMMAND_TOPIC as CONF_SWING_MODE_COMMAND_TOPIC, CONF_SWING_MODE_LIST as CONF_SWING_MODE_LIST, CONF_SWING_MODE_STATE_TEMPLATE as CONF_SWING_MODE_STATE_TEMPLATE, CONF_SWING_MODE_STATE_TOPIC as CONF_SWING_MODE_STATE_TOPIC, CONF_TEMP_COMMAND_TEMPLATE as CONF_TEMP_COMMAND_TEMPLATE, CONF_TEMP_COMMAND_TOPIC as CONF_TEMP_COMMAND_TOPIC, CONF_TEMP_HIGH_COMMAND_TEMPLATE as CONF_TEMP_HIGH_COMMAND_TEMPLATE, CONF_TEMP_HIGH_COMMAND_TOPIC as CONF_TEMP_HIGH_COMMAND_TOPIC, CONF_TEMP_HIGH_STATE_TEMPLATE as CONF_TEMP_HIGH_STATE_TEMPLATE, CONF_TEMP_HIGH_STATE_TOPIC as CONF_TEMP_HIGH_STATE_TOPIC, CONF_TEMP_INITIAL as CONF_TEMP_INITIAL, CONF_TEMP_LOW_COMMAND_TEMPLATE as CONF_TEMP_LOW_COMMAND_TEMPLATE, CONF_TEMP_LOW_COMMAND_TOPIC as CONF_TEMP_LOW_COMMAND_TOPIC, CONF_TEMP_LOW_STATE_TEMPLATE as CONF_TEMP_LOW_STATE_TEMPLATE, CONF_TEMP_LOW_STATE_TOPIC as CONF_TEMP_LOW_STATE_TOPIC, CONF_TEMP_MAX as CONF_TEMP_MAX, CONF_TEMP_MIN as CONF_TEMP_MIN, CONF_TEMP_STATE_TEMPLATE as CONF_TEMP_STATE_TEMPLATE, CONF_TEMP_STATE_TOPIC as CONF_TEMP_STATE_TOPIC, CONF_TEMP_STEP as CONF_TEMP_STEP, CONF_TILT_CLOSED_POSITION as CONF_TILT_CLOSED_POSITION, CONF_TILT_COMMAND_TEMPLATE as CONF_TILT_COMMAND_TEMPLATE, CONF_TILT_COMMAND_TOPIC as CONF_TILT_COMMAND_TOPIC, CONF_TILT_MAX as CONF_TILT_MAX, CONF_TILT_MIN as CONF_TILT_MIN, CONF_TILT_OPEN_POSITION as CONF_TILT_OPEN_POSITION, CONF_TILT_STATE_OPTIMISTIC as CONF_TILT_STATE_OPTIMISTIC, CONF_TILT_STATUS_TEMPLATE as CONF_TILT_STATUS_TEMPLATE, CONF_TILT_STATUS_TOPIC as CONF_TILT_STATUS_TOPIC, CONF_TLS_INSECURE as CONF_TLS_INSECURE, CONF_TRANSITION as CONF_TRANSITION, CONF_TRANSPORT as CONF_TRANSPORT, CONF_URL_TEMPLATE as CONF_URL_TEMPLATE, CONF_URL_TOPIC as CONF_URL_TOPIC, CONF_WHITE_COMMAND_TOPIC as CONF_WHITE_COMMAND_TOPIC, CONF_WHITE_SCALE as CONF_WHITE_SCALE, CONF_WILL_MESSAGE as CONF_WILL_MESSAGE, CONF_WS_HEADERS as CONF_WS_HEADERS, CONF_WS_PATH as CONF_WS_PATH, CONF_XY_COMMAND_TEMPLATE as CONF_XY_COMMAND_TEMPLATE, CONF_XY_COMMAND_TOPIC as CONF_XY_COMMAND_TOPIC, CONF_XY_STATE_TOPIC as CONF_XY_STATE_TOPIC, CONF_XY_VALUE_TEMPLATE as CONF_XY_VALUE_TEMPLATE, DEFAULT_ALARM_CONTROL_PANEL_COMMAND_TEMPLATE as DEFAULT_ALARM_CONTROL_PANEL_COMMAND_TEMPLATE, DEFAULT_BIRTH as DEFAULT_BIRTH, DEFAULT_CLIMATE_INITIAL_TEMPERATURE as DEFAULT_CLIMATE_INITIAL_TEMPERATURE, DEFAULT_DISCOVERY as DEFAULT_DISCOVERY, DEFAULT_ENCODING as DEFAULT_ENCODING, DEFAULT_KEEPALIVE as DEFAULT_KEEPALIVE, DEFAULT_ON_COMMAND_TYPE as DEFAULT_ON_COMMAND_TYPE, DEFAULT_PAYLOAD_ARM_AWAY as DEFAULT_PAYLOAD_ARM_AWAY, DEFAULT_PAYLOAD_ARM_CUSTOM_BYPASS as DEFAULT_PAYLOAD_ARM_CUSTOM_BYPASS, DEFAULT_PAYLOAD_ARM_HOME as DEFAULT_PAYLOAD_ARM_HOME, DEFAULT_PAYLOAD_ARM_NIGHT as DEFAULT_PAYLOAD_ARM_NIGHT, DEFAULT_PAYLOAD_ARM_VACATION as DEFAULT_PAYLOAD_ARM_VACATION, DEFAULT_PAYLOAD_AVAILABLE as DEFAULT_PAYLOAD_AVAILABLE, DEFAULT_PAYLOAD_CLOSE as DEFAULT_PAYLOAD_CLOSE, DEFAULT_PAYLOAD_LOCK as DEFAULT_PAYLOAD_LOCK, DEFAULT_PAYLOAD_NOT_AVAILABLE as DEFAULT_PAYLOAD_NOT_AVAILABLE, DEFAULT_PAYLOAD_OFF as DEFAULT_PAYLOAD_OFF, DEFAULT_PAYLOAD_ON as DEFAULT_PAYLOAD_ON, DEFAULT_PAYLOAD_OPEN as DEFAULT_PAYLOAD_OPEN, DEFAULT_PAYLOAD_OSCILLATE_OFF as DEFAULT_PAYLOAD_OSCILLATE_OFF, DEFAULT_PAYLOAD_OSCILLATE_ON as DEFAULT_PAYLOAD_OSCILLATE_ON, DEFAULT_PAYLOAD_PRESS as DEFAULT_PAYLOAD_PRESS, DEFAULT_PAYLOAD_RESET as DEFAULT_PAYLOAD_RESET, DEFAULT_PAYLOAD_STOP as DEFAULT_PAYLOAD_STOP, DEFAULT_PAYLOAD_TRIGGER as DEFAULT_PAYLOAD_TRIGGER, DEFAULT_PAYLOAD_UNLOCK as DEFAULT_PAYLOAD_UNLOCK, DEFAULT_PORT as DEFAULT_PORT, DEFAULT_POSITION_CLOSED as DEFAULT_POSITION_CLOSED, DEFAULT_POSITION_OPEN as DEFAULT_POSITION_OPEN, DEFAULT_PREFIX as DEFAULT_PREFIX, DEFAULT_PROTOCOL as DEFAULT_PROTOCOL, DEFAULT_QOS as DEFAULT_QOS, DEFAULT_SPEED_RANGE_MAX as DEFAULT_SPEED_RANGE_MAX, DEFAULT_SPEED_RANGE_MIN as DEFAULT_SPEED_RANGE_MIN, DEFAULT_STATE_JAMMED as DEFAULT_STATE_JAMMED, DEFAULT_STATE_LOCKED as DEFAULT_STATE_LOCKED, DEFAULT_STATE_LOCKING as DEFAULT_STATE_LOCKING, DEFAULT_STATE_STOPPED as DEFAULT_STATE_STOPPED, DEFAULT_STATE_UNLOCKED as DEFAULT_STATE_UNLOCKED, DEFAULT_STATE_UNLOCKING as DEFAULT_STATE_UNLOCKING, DEFAULT_TILT_CLOSED_POSITION as DEFAULT_TILT_CLOSED_POSITION, DEFAULT_TILT_MAX as DEFAULT_TILT_MAX, DEFAULT_TILT_MIN as DEFAULT_TILT_MIN, DEFAULT_TILT_OPEN_POSITION as DEFAULT_TILT_OPEN_POSITION, DEFAULT_TRANSPORT as DEFAULT_TRANSPORT, DEFAULT_WILL as DEFAULT_WILL, DEFAULT_WS_PATH as DEFAULT_WS_PATH, DOMAIN as DOMAIN, REMOTE_CODE as REMOTE_CODE, REMOTE_CODE_TEXT as REMOTE_CODE_TEXT, SUPPORTED_PROTOCOLS as SUPPORTED_PROTOCOLS, TRANSPORT_TCP as TRANSPORT_TCP, TRANSPORT_WEBSOCKETS as TRANSPORT_WEBSOCKETS, VALUES_ON_COMMAND_TYPE as VALUES_ON_COMMAND_TYPE
from .models import MqttAvailabilityData as MqttAvailabilityData, MqttDeviceData as MqttDeviceData, MqttSubentryData as MqttSubentryData
from .util import async_create_certificate_temp_files as async_create_certificate_temp_files, get_file_path as get_file_path, learn_more_url as learn_more_url, valid_birth_will as valid_birth_will, valid_publish_topic as valid_publish_topic, valid_subscribe_topic as valid_subscribe_topic, valid_subscribe_topic_template as valid_subscribe_topic_template
from _typeshed import Incomplete
from collections import OrderedDict
from collections.abc import Callable as Callable, Mapping
from dataclasses import dataclass
from enum import IntEnum
from homeassistant.components.binary_sensor import BinarySensorDeviceClass as BinarySensorDeviceClass
from homeassistant.components.button import ButtonDeviceClass as ButtonDeviceClass
from homeassistant.components.climate import DEFAULT_MAX_HUMIDITY as DEFAULT_MAX_HUMIDITY, DEFAULT_MAX_TEMP as DEFAULT_MAX_TEMP, DEFAULT_MIN_HUMIDITY as DEFAULT_MIN_HUMIDITY, DEFAULT_MIN_TEMP as DEFAULT_MIN_TEMP, PRESET_NONE as PRESET_NONE
from homeassistant.components.cover import CoverDeviceClass as CoverDeviceClass
from homeassistant.components.file_upload import process_uploaded_file as process_uploaded_file
from homeassistant.components.hassio import AddonError as AddonError, AddonManager as AddonManager, AddonState as AddonState
from homeassistant.components.image import DEFAULT_CONTENT_TYPE as DEFAULT_CONTENT_TYPE
from homeassistant.components.light import DEFAULT_MAX_KELVIN as DEFAULT_MAX_KELVIN, DEFAULT_MIN_KELVIN as DEFAULT_MIN_KELVIN, VALID_COLOR_MODES as VALID_COLOR_MODES, valid_supported_color_modes as valid_supported_color_modes
from homeassistant.components.number import DEFAULT_MAX_VALUE as DEFAULT_MAX_VALUE, DEFAULT_MIN_VALUE as DEFAULT_MIN_VALUE, DEFAULT_STEP as DEFAULT_STEP, NumberDeviceClass as NumberDeviceClass, NumberMode as NumberMode
from homeassistant.components.sensor import CONF_STATE_CLASS as CONF_STATE_CLASS, DEVICE_CLASS_UNITS as DEVICE_CLASS_UNITS, STATE_CLASS_UNITS as STATE_CLASS_UNITS, SensorDeviceClass as SensorDeviceClass, SensorStateClass as SensorStateClass
from homeassistant.components.switch import SwitchDeviceClass as SwitchDeviceClass
from homeassistant.components.valve import ValveDeviceClass as ValveDeviceClass, ValveState as ValveState
from homeassistant.config_entries import ConfigEntry as ConfigEntry, ConfigFlow as ConfigFlow, ConfigFlowResult as ConfigFlowResult, ConfigSubentryFlow as ConfigSubentryFlow, OptionsFlow as OptionsFlow, SOURCE_RECONFIGURE as SOURCE_RECONFIGURE, SubentryFlowResult as SubentryFlowResult
from homeassistant.const import ATTR_CONFIGURATION_URL as ATTR_CONFIGURATION_URL, ATTR_HW_VERSION as ATTR_HW_VERSION, ATTR_MANUFACTURER as ATTR_MANUFACTURER, ATTR_MODEL as ATTR_MODEL, ATTR_MODEL_ID as ATTR_MODEL_ID, ATTR_NAME as ATTR_NAME, ATTR_SW_VERSION as ATTR_SW_VERSION, CONF_BRIGHTNESS as CONF_BRIGHTNESS, CONF_CLIENT_ID as CONF_CLIENT_ID, CONF_CODE as CONF_CODE, CONF_DEVICE as CONF_DEVICE, CONF_DEVICE_CLASS as CONF_DEVICE_CLASS, CONF_DISCOVERY as CONF_DISCOVERY, CONF_EFFECT as CONF_EFFECT, CONF_ENTITY_CATEGORY as CONF_ENTITY_CATEGORY, CONF_HOST as CONF_HOST, CONF_MODE as CONF_MODE, CONF_NAME as CONF_NAME, CONF_OPTIMISTIC as CONF_OPTIMISTIC, CONF_PASSWORD as CONF_PASSWORD, CONF_PAYLOAD as CONF_PAYLOAD, CONF_PAYLOAD_OFF as CONF_PAYLOAD_OFF, CONF_PAYLOAD_ON as CONF_PAYLOAD_ON, CONF_PLATFORM as CONF_PLATFORM, CONF_PORT as CONF_PORT, CONF_PROTOCOL as CONF_PROTOCOL, CONF_STATE_TEMPLATE as CONF_STATE_TEMPLATE, CONF_TEMPERATURE_UNIT as CONF_TEMPERATURE_UNIT, CONF_UNIQUE_ID as CONF_UNIQUE_ID, CONF_UNIT_OF_MEASUREMENT as CONF_UNIT_OF_MEASUREMENT, CONF_USERNAME as CONF_USERNAME, CONF_VALUE_TEMPLATE as CONF_VALUE_TEMPLATE, EntityCategory as EntityCategory, Platform as Platform, STATE_CLOSED as STATE_CLOSED, STATE_CLOSING as STATE_CLOSING, STATE_OPEN as STATE_OPEN, STATE_OPENING as STATE_OPENING, UnitOfTemperature as UnitOfTemperature
from homeassistant.core import HomeAssistant as HomeAssistant, async_get_hass as async_get_hass, callback as callback
from homeassistant.data_entry_flow import AbortFlow as AbortFlow, SectionConfig as SectionConfig, section as section
from homeassistant.helpers.hassio import is_hassio as is_hassio
from homeassistant.helpers.json import json_dumps as json_dumps
from homeassistant.helpers.selector import BooleanSelector as BooleanSelector, FileSelector as FileSelector, FileSelectorConfig as FileSelectorConfig, NumberSelector as NumberSelector, NumberSelectorConfig as NumberSelectorConfig, NumberSelectorMode as NumberSelectorMode, SelectOptionDict as SelectOptionDict, SelectSelector as SelectSelector, SelectSelectorConfig as SelectSelectorConfig, SelectSelectorMode as SelectSelectorMode, Selector as Selector, TemplateSelector as TemplateSelector, TemplateSelectorConfig as TemplateSelectorConfig, TextSelector as TextSelector, TextSelectorConfig as TextSelectorConfig, TextSelectorType as TextSelectorType
from homeassistant.helpers.service_info.hassio import HassioServiceInfo as HassioServiceInfo
from homeassistant.util.json import JSON_DECODE_EXCEPTIONS as JSON_DECODE_EXCEPTIONS, json_loads as json_loads
from homeassistant.util.unit_conversion import TemperatureConverter as TemperatureConverter
from types import MappingProxyType
from typing import Any

_LOGGER: Incomplete
ADDON_SETUP_TIMEOUT: int
ADDON_SETUP_TIMEOUT_ROUNDS: int
CONF_CLIENT_KEY_PASSWORD: str
MQTT_TIMEOUT: int
ADVANCED_OPTIONS: str
SET_CA_CERT: str
SET_CLIENT_CERT: str
CA_VERIFICATION_MODES: Incomplete
SUBENTRY_PLATFORMS: Incomplete
_CODE_VALIDATION_MODE: Incomplete
EXCLUDE_FROM_CONFIG_IF_NONE: Incomplete
PWD_NOT_CHANGED: str
DEVELOPER_DOCUMENTATION_URL: str
USER_DOCUMENTATION_URL: str
INTEGRATION_URL: Incomplete
TEMPLATING_URL: Incomplete
COMMAND_TEMPLATING_URL: Incomplete
VALUE_TEMPLATING_URL: Incomplete
AVAILABLE_STATE_CLASSES_URL: Incomplete
NAMING_ENTITIES_URL: Incomplete
REGISTRY_PROPERTIES_URL: Incomplete
TRANSLATION_DESCRIPTION_PLACEHOLDERS: Incomplete
BOOLEAN_SELECTOR: Incomplete
TEMPLATE_SELECTOR: Incomplete
TEMPLATE_SELECTOR_READ_ONLY: Incomplete
TEXT_SELECTOR: Incomplete
TEXT_SELECTOR_READ_ONLY: Incomplete
OPTIONS_SELECTOR: Incomplete
PASSWORD_SELECTOR: Incomplete
QOS_SELECTOR: Incomplete
URL_SELECTOR: Incomplete
BROKER_VERIFICATION_SELECTOR: Incomplete
CA_CERT_UPLOAD_SELECTOR: Incomplete
CERT_KEY_UPLOAD_SELECTOR: Incomplete
CERT_UPLOAD_SELECTOR: Incomplete
KEEPALIVE_SELECTOR: Incomplete
PORT_SELECTOR: Incomplete
PROTOCOL_SELECTOR: Incomplete
PUBLISH_TOPIC_SELECTOR: Incomplete
SUPPORTED_TRANSPORTS: Incomplete
TRANSPORT_SELECTOR: Incomplete
WS_HEADERS_SELECTOR: Incomplete
ENTITY_CATEGORY_SELECTOR: Incomplete
SUBENTRY_AVAILABILITY_SCHEMA: Incomplete
SUBENTRY_PLATFORM_SELECTOR: Incomplete
SUGGESTED_DISPLAY_PRECISION_SELECTOR: Incomplete
TIMEOUT_SELECTOR: Incomplete
ALARM_CONTROL_PANEL_FEATURES_SELECTOR: Incomplete
ALARM_CONTROL_PANEL_CODE_MODE: Incomplete
BINARY_SENSOR_DEVICE_CLASS_SELECTOR: Incomplete
BUTTON_DEVICE_CLASS_SELECTOR: Incomplete
CLIMATE_MODE_SELECTOR: Incomplete
COVER_DEVICE_CLASS_SELECTOR: Incomplete
FAN_SPEED_RANGE_MIN_SELECTOR: Incomplete
FAN_SPEED_RANGE_MAX_SELECTOR: Incomplete
FLASH_TIME_SELECTOR: Incomplete
HUMIDITY_SELECTOR: Incomplete
IMAGE_CONTENT_TYPE_SELECTOR: Incomplete
IMAGE_ENCODING_SELECTOR: Incomplete
IMAGE_PROCESSING_MODE_SELECTOR: Incomplete
KELVIN_SELECTOR: Incomplete
LIGHT_SCHEMA_SELECTOR: Incomplete
MIN_MAX_SELECTOR: Incomplete
NUMBER_DEVICE_CLASS_SELECTOR: Incomplete
NUMBER_MODE_SELECTOR: Incomplete
ON_COMMAND_TYPE_SELECTOR: Incomplete
POSITION_SELECTOR: Incomplete
PRECISION_SELECTOR: Incomplete
PRESET_MODES_SELECTOR = OPTIONS_SELECTOR
SCALE_SELECTOR: Incomplete
SENSOR_DEVICE_CLASS_SELECTOR: Incomplete
SENSOR_ENTITY_CATEGORY_SELECTOR: Incomplete
SENSOR_STATE_CLASS_SELECTOR: Incomplete
STEP_SELECTOR: Incomplete
SUPPORTED_COLOR_MODES_SELECTOR: Incomplete
SWITCH_DEVICE_CLASS_SELECTOR: Incomplete
TARGET_TEMPERATURE_FEATURE_SELECTOR: Incomplete
TEMPERATURE_UNIT_SELECTOR: Incomplete
TEXT_MODE_SELECTOR: Incomplete
TEXT_SIZE_SELECTOR: Incomplete
VALVE_DEVICE_CLASS_SELECTOR: Incomplete
VALVE_POSITION_SELECTOR: Incomplete
WATER_HEATER_MODE_SELECTOR: Incomplete

@callback
def configured_target_temperature_feature(config: dict[str, Any]) -> str: ...
@callback
def default_alarm_control_panel_code(config: dict[str, Any]) -> str: ...
@callback
def default_precision(config: dict[str, Any]) -> str: ...
@callback
def no_empty_list(value: list[Any]) -> list[Any]: ...
@callback
def temperature_default_from_celsius_to_system_default(value: float) -> Callable[[dict[str, Any]], int]: ...
@callback
def temperature_selector(config: dict[str, Any]) -> Selector: ...
@callback
def temperature_step_selector(config: dict[str, Any]) -> Selector: ...
@callback
def unit_of_measurement_selector(user_data: dict[str, Any | None]) -> Selector: ...
@callback
def number_unit_of_measurement_selector(user_data: dict[str, Any | None]) -> Selector: ...
@callback
def validate(validator: Callable[[Any], Any]) -> Callable[[Any], Any]: ...
@callback
def validate_field(field: str, validator: Callable[..., Any], user_input: dict[str, Any] | None, errors: dict[str, str], error: str) -> None: ...
@callback
def validate_climate_platform_config(config: dict[str, Any]) -> dict[str, str]: ...
@callback
def validate_cover_platform_config(config: dict[str, Any]) -> dict[str, str]: ...
@callback
def validate_fan_platform_config(config: dict[str, Any]) -> dict[str, str]: ...
@callback
def validate_light_platform_config(user_data: dict[str, Any]) -> dict[str, str]: ...
@callback
def validate_number_platform_config(config: dict[str, Any]) -> dict[str, str]: ...
@callback
def validate_sensor_platform_config(config: dict[str, Any]) -> dict[str, str]: ...
@callback
def validate_text_platform_config(config: dict[str, Any]) -> dict[str, str]: ...
@callback
def validate_water_heater_platform_config(config: dict[str, Any]) -> dict[str, str]: ...

ENTITY_CONFIG_VALIDATOR: dict[str, Callable[[dict[str, Any]], dict[str, str]] | None]

@dataclass(frozen=True, kw_only=True)
class PlatformField:
    selector: Selector[Any] | Callable[[dict[str, Any]], Selector[Any]]
    required: bool
    validator: Callable[[Any], Any] | None = ...
    error: str | None = ...
    default: Any | None | Callable[[dict[str, Any]], Any] | vol.Undefined = ...
    is_schema_default: bool = ...
    include_in_config: bool = ...
    exclude_from_reconfig: bool = ...
    exclude_from_config: bool = ...
    conditions: tuple[dict[str, Any], ...] | None = ...
    custom_filtering: bool = ...
    section: str | None = ...

COMMON_ENTITY_FIELDS: dict[str, PlatformField]
SHARED_PLATFORM_ENTITY_FIELDS: dict[str, PlatformField]
PLATFORM_ENTITY_FIELDS: dict[Platform, dict[str, PlatformField]]
PLATFORM_MQTT_FIELDS: dict[Platform, dict[str, PlatformField]]
MQTT_DEVICE_PLATFORM_FIELDS: Incomplete

@callback
def _check_conditions(platform_field: PlatformField, component_data: dict[str, Any] | None = None) -> bool: ...
@callback
def calculate_merged_config(merged_user_input: dict[str, Any], data_schema_fields: dict[str, PlatformField], component_data: dict[str, Any]) -> dict[str, Any]: ...
@callback
def data_schema_from_fields(data_schema_fields: dict[str, PlatformField], reconfig: bool, component_data: dict[str, Any] | None = None, user_input: dict[str, Any] | None = None, device_data: MqttDeviceData | None = None) -> vol.Schema: ...
@callback
def validate_user_input(user_input: dict[str, Any], data_schema_fields: dict[str, PlatformField], *, component_data: dict[str, Any] | None = None, config_validator: Callable[[dict[str, Any]], dict[str, str]] | None = None) -> tuple[dict[str, Any], dict[str, str]]: ...
@callback
def subentry_schema_default_data_from_fields(data_schema_fields: dict[str, PlatformField], component_data: dict[str, Any]) -> dict[str, Any]: ...
@callback
def update_password_from_user_input(entry_password: str | None, user_input: dict[str, Any]) -> dict[str, Any]: ...

REAUTH_SCHEMA: Incomplete

class FlowHandler(ConfigFlow, domain=DOMAIN):
    VERSION = CONFIG_ENTRY_VERSION
    MINOR_VERSION = CONFIG_ENTRY_MINOR_VERSION
    _hassio_discovery: dict[str, Any] | None
    _addon_manager: AddonManager
    install_task: asyncio.Task | None
    start_task: asyncio.Task | None
    def __init__(self) -> None: ...
    @classmethod
    @callback
    def async_get_supported_subentry_types(cls, config_entry: ConfigEntry) -> dict[str, type[ConfigSubentryFlow]]: ...
    @staticmethod
    @callback
    def async_get_options_flow(config_entry: ConfigEntry) -> MQTTOptionsFlowHandler: ...
    async def _async_install_addon(self) -> None: ...
    async def async_step_install_failed(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_install_addon(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_start_failed(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_start_addon(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def _async_get_config_and_try(self) -> dict[str, Any] | None: ...
    async def _async_start_addon(self) -> None: ...
    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_setup_entry_from_discovery(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_addon(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_reauth(self, entry_data: Mapping[str, Any]) -> ConfigFlowResult: ...
    async def async_step_reauth_confirm(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_broker(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_reconfigure(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_hassio(self, discovery_info: HassioServiceInfo) -> ConfigFlowResult: ...
    async def async_step_hassio_confirm(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...

class MQTTOptionsFlowHandler(OptionsFlow):
    async def async_step_init(self, user_input: None = None) -> ConfigFlowResult: ...
    async def async_step_options(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...

class MQTTSubentryFlowHandler(ConfigSubentryFlow):
    _subentry_data: MqttSubentryData
    _component_id: str | None
    @callback
    def update_component_fields(self, data_schema_fields: dict[str, PlatformField], merged_user_input: dict[str, Any]) -> None: ...
    @callback
    def generate_names(self) -> tuple[str, str]: ...
    @callback
    def get_suggested_values_from_component(self, data_schema: vol.Schema) -> dict[str, Any]: ...
    @callback
    def get_suggested_values_from_device_data(self, data_schema: vol.Schema) -> dict[str, Any]: ...
    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_reconfigure(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_device(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_entity(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    def _show_update_or_delete_form(self, step_id: str) -> SubentryFlowResult: ...
    async def async_step_update_entity(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_delete_entity(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_entity_platform_config(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_mqtt_platform_config(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    @callback
    def _async_update_component_data_defaults(self) -> None: ...
    @callback
    def _async_create_subentry(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_availability(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_summary_menu(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_save_changes(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_export(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_export_yaml(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...
    async def async_step_export_discovery(self, user_input: dict[str, Any] | None = None) -> SubentryFlowResult: ...

@callback
def async_is_pem_data(data: bytes) -> bool: ...

class PEMType(IntEnum):
    CERTIFICATE = 1
    PRIVATE_KEY = 2

@callback
def async_convert_to_pem(data: bytes, pem_type: PEMType, password: str | None = None) -> str | None: ...
async def _get_uploaded_file(hass: HomeAssistant, id: str) -> bytes: ...
def _validate_pki_file(file_id: str | None, pem_data: str | None, errors: dict[str, str], error: str) -> bool: ...
async def async_get_broker_settings(flow: ConfigFlow | OptionsFlow, fields: OrderedDict[Any, Any], entry_config: MappingProxyType[str, Any] | None, user_input: dict[str, Any] | None, validated_user_input: dict[str, Any], errors: dict[str, str]) -> bool: ...
def try_connection(user_input: dict[str, Any]) -> bool: ...
def check_certicate_chain() -> str | None: ...
