from homeassistant.components.homeassistant_hardware.silabs_multiprotocol_addon import is_multiprotocol_url as is_multiprotocol_url
from homeassistant.core import HomeAssistant as HomeAssistant

def _get_zha_url(hass: HomeAssistant) -> str | None: ...
async def _get_zha_channel(hass: HomeAssistant) -> int | None: ...
async def get_allowed_channel(hass: HomeAssistant, otbr_url: str) -> int | None: ...
