from _typeshed import Incomplete

DOMAIN: str
LOGGER: Incomplete
STREAM_MAGIC_EXCEPTIONS: Incomplete
CONNECT_TIMEOUT: int
CAMBRIDGE_MEDIA_TYPE_PRESET: str
CAMBRIDGE_MEDIA_TYPE_AIRABLE: str
CAMBRIDGE_MEDIA_TYPE_INTERNET_RADIO: str
