from . import LeafDataStore as LeafDataStore, LeafEntity as LeafEntity
from .const import DATA_CLIMATE as DATA_CLIMATE, DATA_LEAF as DATA_LEAF
from _typeshed import Incomplete
from homeassistant.components.switch import SwitchEntity as SwitchEntity
from homeassistant.core import HomeAssistant as HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback as AddEntitiesCallback
from homeassistant.helpers.typing import ConfigType as ConfigType, DiscoveryInfoType as DiscoveryInfoType
from typing import Any

_LOGGER: Incomplete

def setup_platform(hass: HomeAssistant, config: ConfigType, add_entities: AddEntitiesCallback, discovery_info: Union[DiscoveryInfoType, None] = ...) -> None: ...

class LeafClimateSwitch(LeafEntity, SwitchEntity):
    _attr_unique_id: Incomplete
    def __init__(self, car: LeafDataStore) -> None: ...
    @property
    def name(self) -> str: ...
    def log_registration(self) -> None: ...
    @property
    def extra_state_attributes(self) -> dict[str, Any]: ...
    @property
    def is_on(self) -> bool: ...
    async def async_turn_on(self, **kwargs: Any) -> None: ...
    async def async_turn_off(self, **kwargs: Any) -> None: ...
