from _typeshed import Incomplete

DOMAIN: str
PRODUCT: str
SERIAL_NUMBER: str
TITLE: str
FIRMWARE_UPDATE_INTERVAL: Incomplete
LONG_UPDATE_INTERVAL: Incomplete
SHORT_UPDATE_INTERVAL: Incomplete
CONNECTED_PLC_DEVICES: str
CONNECTED_TO_ROUTER: str
CONNECTED_WIFI_CLIENTS: str
IDENTIFY: str
IMAGE_GUEST_WIFI: str
NEIGHBORING_WIFI_NETWORKS: str
PAIRING: str
REGULAR_FIRMWARE: str
RESTART: str
START_WPS: str
SWITCH_GUEST_WIFI: str
SWITCH_LEDS: str
WIFI_APTYPE: Incomplete
WIFI_BANDS: Incomplete
