from homeassistant.const import LENGTH_KILOMETERS as LENGTH_KILOMETERS, LENGTH_MILES as LENGTH_MILES, VOLUME_GALLONS as VOLUME_GALLONS, VOLUME_LITERS as VOLUME_LITERS
from typing import Any

ATTRIBUTION: str
CONF_ALLOWED_REGIONS: Any
CONF_READ_ONLY: str
CONF_USE_LOCATION: str
CONF_ACCOUNT: str
DATA_HASS_CONFIG: str
DATA_ENTRIES: str
UNIT_MAP: Any
