from homeassistant.const import LENGTH_KILOMETERS as LENGTH_KILOMETERS, LENGTH_MILES as LENGTH_MILES, VOLUME_GALLONS as VOLUME_GALLONS, VOLUME_LITERS as VOLUME_LITERS
from typing import Any

DOMAIN: str
ATTRIBUTION: str
ATTR_DIRECTION: str
ATTR_VIN: str
CONF_ALLOWED_REGIONS: Any
CONF_READ_ONLY: str
CONF_ACCOUNT: str
DATA_HASS_CONFIG: str
UNIT_MAP: Any
