from .const import CONF_KEY as CONF_KEY, CONF_SN as CONF_SN, CONF_SUBTYPE as CONF_SUBTYPE, DOMAIN as DOMAIN, LOGGER as LOGGER
from .entity import MideaConfigEntry as MideaConfigEntry
from collections.abc import Mapping
from homeassistant.const import CONF_DEVICE_ID as CONF_DEVICE_ID, CONF_IP_ADDRESS as CONF_IP_ADDRESS, CONF_MAC as CONF_MAC, CONF_MODEL as CONF_MODEL, CONF_NAME as CONF_NAME, CONF_PORT as CONF_PORT, CONF_PROTOCOL as CONF_PROTOCOL, CONF_TOKEN as CONF_TOKEN, CONF_TYPE as CONF_TYPE, Platform as Platform
from homeassistant.core import HomeAssistant as HomeAssistant
from homeassistant.exceptions import ConfigEntryError as ConfigEntryError, ConfigEntryNotReady as ConfigEntryNotReady
from midealocal.device import MideaDevice as MideaDevice
from typing import Any

_PLATFORMS: list[Platform]

def _create_device(data: Mapping[str, Any], ip_address: str) -> MideaDevice | None: ...
def _connect(device: MideaDevice) -> bool: ...
def _discover_current_ip(device_id: int) -> str | None: ...
async def async_setup_entry(hass: HomeAssistant, entry: MideaConfigEntry) -> bool: ...
async def async_migrate_entry(hass: HomeAssistant, entry: MideaConfigEntry) -> bool: ...
async def async_unload_entry(hass: HomeAssistant, entry: MideaConfigEntry) -> bool: ...
