from _typeshed import Incomplete

DOMAIN: str
DATA_CONFIG: Incomplete
DATA_MIGRATIONS: Incomplete
DEFAULT_PIPELINE_TIMEOUT: Incomplete
DEFAULT_WAKE_WORD_TIMEOUT: int
CONF_DEBUG_RECORDING_DIR: str
DATA_LAST_WAKE_UP: Incomplete
WAKE_WORD_COOLDOWN: int
EVENT_RECORDING: Incomplete
SAMPLE_RATE: int
SAMPLE_WIDTH: int
SAMPLE_CHANNELS: int
MS_PER_CHUNK: int
SAMPLES_PER_CHUNK: Incomplete
BYTES_PER_CHUNK: Incomplete
OPTION_PREFERRED: str
