from .audio_enhancer import AudioEnhancer as AudioEnhancer, EnhancedAudioChunk as EnhancedAudioChunk, MicroVadSpeexEnhancer as MicroVadSpeexEnhancer
from .const import ACKNOWLEDGE_PATH as ACKNOWLEDGE_PATH, BYTES_PER_CHUNK as BYTES_PER_CHUNK, MS_PER_CHUNK as MS_PER_CHUNK, SAMPLES_PER_CHUNK as SAMPLES_PER_CHUNK, SAMPLE_CHANNELS as SAMPLE_CHANNELS, SAMPLE_RATE as SAMPLE_RATE, SAMPLE_WIDTH as SAMPLE_WIDTH
from .error import IntentRecognitionError as IntentRecognitionError, PipelineRunValidationError as PipelineRunValidationError, SpeechToTextError as SpeechToTextError, TextToSpeechError as TextToSpeechError, WakeWordDetectionAborted as WakeWordDetectionAborted, WakeWordDetectionError as WakeWordDetectionError, WakeWordTimeoutError as WakeWordTimeoutError
from .models import AudioSettings as AudioSettings, PIPELINE_STAGE_ORDER as PIPELINE_STAGE_ORDER, Pipeline as Pipeline, PipelineEvent as PipelineEvent, PipelineEventType as PipelineEventType, PipelineStage as PipelineStage, WakeWordSettings as WakeWordSettings
from .run import _PipelineProcessorRequest as _PipelineProcessorRequest
from .vad import AudioBuffer as AudioBuffer, VoiceActivityTimeout as VoiceActivityTimeout, VoiceCommandSegmenter as VoiceCommandSegmenter, chunk_samples as chunk_samples
from _typeshed import Incomplete
from collections import deque
from collections.abc import AsyncGenerator, AsyncIterable, Callable as Callable
from dataclasses import dataclass, field
from hassil.recognize import RecognizeResult as RecognizeResult
from homeassistant.components import conversation as conversation, media_player as media_player, stt as stt, tts as tts, wake_word as wake_word
from homeassistant.const import EntityStateAttribute as EntityStateAttribute, MATCH_ALL as MATCH_ALL
from homeassistant.core import Context as Context, HomeAssistant as HomeAssistant, callback as callback
from homeassistant.exceptions import HomeAssistantError as HomeAssistantError
from homeassistant.helpers import chat_session as chat_session, intent as intent
from homeassistant.util.hass_dict import HassKey as HassKey
from pathlib import Path
from typing import Any, Protocol

_LOGGER: Incomplete
KEY_PIPELINE_CONVERSATION_DATA: HassKey[dict[str, PipelineConversationData]]
STREAM_RESPONSE_CHARS: int

@callback
def _async_local_fallback_intent_filter(result: RecognizeResult) -> bool: ...

class _PipelineController(Protocol):
    @property
    def hass(self) -> HomeAssistant: ...
    @property
    def context(self) -> Context: ...
    @property
    def pipeline(self) -> Pipeline: ...
    @property
    def start_stage(self) -> PipelineStage: ...
    @property
    def end_stage(self) -> PipelineStage: ...
    @property
    def language(self) -> str: ...
    @property
    def tts_audio_output(self) -> str | dict[str, Any] | None: ...
    @property
    def wake_word_settings(self) -> WakeWordSettings | None: ...
    @property
    def audio_settings(self) -> AudioSettings: ...
    @property
    def device_id(self) -> str | None: ...
    @property
    def satellite_id(self) -> str | None: ...
    @callback
    def process_event(self, event: PipelineEvent) -> None: ...
    @callback
    def capture_audio(self, audio_bytes: bytes | None) -> None: ...
    @callback
    def start_debug_recording(self, name: str) -> None: ...
    @callback
    def accept_wake_word(self, wake_word_phrase: str) -> None: ...

@dataclass
class _DefaultPipelineProcessor:
    host: _PipelineController
    stt_provider: stt.SpeechToTextEntity | stt.Provider = field(init=False, repr=False)
    tts_stream: tts.ResultStream | None = field(init=False, default=None)
    wake_word_entity_id: str | None = field(init=False, default=None, repr=False)
    wake_word_entity: wake_word.WakeWordDetectionEntity = field(init=False, repr=False)
    audio_enhancer: AudioEnhancer | None = field(init=False, default=None)
    audio_chunking_buffer: AudioBuffer = field(init=False, default_factory=Incomplete)
    _conversation_data: PipelineConversationData | None = field(init=False, default=None)
    _intent_agent_only: bool = field(init=False, default=False)
    _streamed_response_text: bool = field(init=False, default=False)
    _invalidated: bool = field(init=False, default=False)
    intent_agent: conversation.AgentInfo | None = field(init=False, default=None)
    def __post_init__(self) -> None: ...
    @property
    def response_audio(self) -> tts.ResultStream | None: ...
    @property
    def supports_streaming_response(self) -> bool | None: ...
    @callback
    def invalidate(self) -> None: ...
    @callback
    def cleanup(self) -> None: ...
    async def prepare_wake_word_detection(self) -> None: ...
    async def wake_word_detection(self, stream: AsyncIterable[EnhancedAudioChunk], audio_chunks_for_stt: list[EnhancedAudioChunk]) -> wake_word.DetectionResult | None: ...
    async def _wake_word_audio_stream(self, audio_stream: AsyncIterable[EnhancedAudioChunk], stt_audio_buffer: deque[EnhancedAudioChunk] | None, wake_word_vad: VoiceActivityTimeout | None, sample_rate: int = ..., sample_width: int = ...) -> AsyncIterable[tuple[bytes, int]]: ...
    async def prepare_speech_to_text(self, metadata: stt.SpeechMetadata) -> None: ...
    async def speech_to_text(self, metadata: stt.SpeechMetadata, stream: AsyncIterable[EnhancedAudioChunk]) -> str: ...
    async def _speech_to_text_stream(self, audio_stream: AsyncIterable[EnhancedAudioChunk], stt_vad: VoiceCommandSegmenter | None, sample_rate: int = ..., sample_width: int = ...) -> AsyncGenerator[bytes]: ...
    async def prepare_recognize_intent(self, session: chat_session.ChatSession) -> None: ...
    async def recognize_intent(self, intent_input: str, conversation_id: str, conversation_extra_system_prompt: str | None) -> tuple[str, bool]: ...
    def _get_all_targets_in_satellite_area(self, intent_response: intent.IntentResponse, satellite_id: str | None, device_id: str | None) -> bool: ...
    async def prepare_text_to_speech(self) -> None: ...
    async def text_to_speech(self, tts_input: str, override_media_path: Path | None = None) -> None: ...
    async def process_volume_only(self, audio_stream: AsyncIterable[bytes]) -> AsyncGenerator[EnhancedAudioChunk]: ...
    async def process_enhance_audio(self, audio_stream: AsyncIterable[bytes]) -> AsyncGenerator[EnhancedAudioChunk]: ...
    async def async_execute(self, request: _PipelineProcessorRequest) -> None: ...
    async def async_validate(self, request: _PipelineProcessorRequest) -> None: ...

def _multiply_volume(chunk: bytes, volume_multiplier: float) -> bytes: ...

@dataclass
class PipelineConversationData:
    continue_conversation_agent: str | None = ...

@callback
def async_get_pipeline_conversation_data(hass: HomeAssistant, session: chat_session.ChatSession) -> PipelineConversationData: ...
