from _typeshed import Incomplete
from homeassistant.exceptions import HomeAssistantError as HomeAssistantError

class PipelineError(HomeAssistantError):
    code: Incomplete
    message: Incomplete
    def __init__(self, code: str, message: str) -> None: ...

class PipelineNotFound(PipelineError): ...
class SpeechToTextError(PipelineError): ...
class IntentRecognitionError(PipelineError): ...
class TextToSpeechError(PipelineError): ...
