from _typeshed import Incomplete

class RingBuffer:
    _buffer: Incomplete
    _pos: int
    _length: int
    _maxlen: Incomplete
    def __init__(self, maxlen: int) -> None: ...
    @property
    def maxlen(self) -> int: ...
    @property
    def pos(self) -> int: ...
    def __len__(self) -> int: ...
    def put(self, data: bytes) -> None: ...
    def getvalue(self) -> bytes: ...
