from _typeshed import Incomplete
from homeassistant.const import Platform as Platform

DOMAIN: str
PLATFORMS: Incomplete
INVALID_AUTH_ERRORS: Incomplete
ACB_SLEEP_SOC_STEP: int
ACB_SLEEP_SOC_BANDS: Incomplete
DEFAULT_ACB_SLEEP_SOC_BAND: str
ACCESS_TOKEN_LOGIN_URL: str
CONF_MANUAL_TOKEN: str
SETUP_RETRY_TIMEOUT: int
OPERATIONAL_RETRY_TIMEOUT: int
OPTION_DIAGNOSTICS_INCLUDE_FIXTURES: str
OPTION_DIAGNOSTICS_INCLUDE_FIXTURES_DEFAULT_VALUE: bool
OPTION_DISABLE_KEEP_ALIVE: str
OPTION_DISABLE_KEEP_ALIVE_DEFAULT_VALUE: bool
