import datetime
from .const import DOMAIN as DOMAIN
from .coordinator import ShellyConfigEntry as ShellyConfigEntry, ShellyRpcCoordinator as ShellyRpcCoordinator
from .entity import RpcEntityDescription as RpcEntityDescription, ShellyRpcAttributeEntity as ShellyRpcAttributeEntity, async_setup_entry_rpc as async_setup_entry_rpc, rpc_call as rpc_call
from .utils import get_device_entry_gen as get_device_entry_gen
from _typeshed import Incomplete
from dataclasses import dataclass
from homeassistant.components.media_player import BrowseMedia as BrowseMedia, MediaClass as MediaClass, MediaPlayerDeviceClass as MediaPlayerDeviceClass, MediaPlayerEntity as MediaPlayerEntity, MediaPlayerEntityDescription as MediaPlayerEntityDescription, MediaPlayerEntityFeature as MediaPlayerEntityFeature, MediaPlayerState as MediaPlayerState, MediaType as MediaType
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.exceptions import HomeAssistantError as HomeAssistantError
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback as AddConfigEntryEntitiesCallback
from typing import Any, Final

CONTENT_TYPE_AUDIO: str
CONTENT_TYPE_RADIO: str
PARALLEL_UPDATES: int

@dataclass(frozen=True, kw_only=True)
class RpcMediaPlayerDescription(RpcEntityDescription, MediaPlayerEntityDescription): ...

RPC_MEDIA_PLAYER_ENTITIES: Final[Incomplete]

async def async_setup_entry(hass: HomeAssistant, config_entry: ShellyConfigEntry, async_add_entities: AddConfigEntryEntitiesCallback) -> None: ...
@callback
def _async_setup_rpc_entry(hass: HomeAssistant, config_entry: ShellyConfigEntry, async_add_entities: AddConfigEntryEntitiesCallback) -> None: ...

class ShellyRpcMediaPlayer(ShellyRpcAttributeEntity, MediaPlayerEntity):
    _attr_name: Incomplete
    _attr_supported_features: Incomplete
    _attr_media_content_type: Incomplete
    entity_description: RpcMediaPlayerDescription
    _last_media_position: int | None
    _last_media_position_updated_at: datetime.datetime | None
    def __init__(self, coordinator: ShellyRpcCoordinator, key: str, attribute: str, description: RpcMediaPlayerDescription) -> None: ...
    @property
    def _media_meta(self) -> dict[str, Any]: ...
    @property
    def state(self) -> MediaPlayerState: ...
    @property
    def volume_level(self) -> float | None: ...
    @property
    def media_title(self) -> str | None: ...
    @property
    def media_artist(self) -> str | None: ...
    @property
    def media_album_name(self) -> str | None: ...
    @property
    def media_duration(self) -> int | None: ...
    @property
    def media_position(self) -> int | None: ...
    @property
    def media_position_updated_at(self) -> datetime.datetime | None: ...
    @property
    def media_image_url(self) -> str | None: ...
    @property
    def media_image_remotely_accessible(self) -> bool: ...
    @property
    def media_image_hash(self) -> str | None: ...
    def _get_updated_media_position(self) -> int | None: ...
    async def async_get_media_image(self) -> tuple[bytes | None, str | None]: ...
    @rpc_call
    async def async_media_play(self) -> None: ...
    @rpc_call
    async def async_media_pause(self) -> None: ...
    @rpc_call
    async def async_media_stop(self) -> None: ...
    @rpc_call
    async def async_media_next_track(self) -> None: ...
    @rpc_call
    async def async_media_previous_track(self) -> None: ...
    @rpc_call
    async def async_set_volume_level(self, volume: float) -> None: ...
    async def async_browse_media(self, media_content_type: MediaType | str | None = None, media_content_id: str | None = None) -> BrowseMedia: ...
    async def _async_browse_media_root(self) -> BrowseMedia: ...
    async def _async_browse_audio_files(self, expanded: bool = False) -> BrowseMedia: ...
    async def _async_browse_radio_stations(self, expanded: bool = False) -> BrowseMedia: ...
    @rpc_call
    async def async_play_media(self, media_type: MediaType | str, media_id: str, **kwargs: Any) -> None: ...
