from typing import Final

ATTR_BLOCKS: str
ATTR_BLOCKS_TEMPLATE: str
ATTR_FILE: str
ATTR_PASSWORD: str
ATTR_PATH: str
ATTR_URL: str
ATTR_USERNAME: str
CONF_DEFAULT_CHANNEL: str
DATA_CLIENT: str
DEFAULT_TIMEOUT_SECONDS: int
DOMAIN: Final[str]
