from _typeshed import Incomplete
from typing import Final

LOGGER: Incomplete
DOMAIN: Final[str]
CONF_BASE_URL: Final[str]
DATA_HASS_CONFIG: str
DEFAULT_URL: Final[str]
DEFAULT_NAME: Final[str]
ATTR_ACCOUNT_NAME: str
ATTR_STATUS: str
ATTR_VISIBILITY: str
ATTR_QUOTE_APPROVAL_POLICY: str
ATTR_IDEMPOTENCY_KEY: str
ATTR_CONTENT_WARNING: str
ATTR_MEDIA_WARNING: str
ATTR_MEDIA: str
ATTR_MEDIA_DESCRIPTION: str
ATTR_LANGUAGE: str
ATTR_DURATION: str
ATTR_HIDE_NOTIFICATIONS: str
ATTR_DISPLAY_NAME: str
ATTR_NOTE: str
ATTR_AVATAR: str
ATTR_AVATAR_MIME_TYPE: str
ATTR_HEADER: str
ATTR_HEADER_MIME_TYPE: str
ATTR_LOCKED: str
ATTR_BOT: str
ATTR_DISCOVERABLE: str
ATTR_FIELDS: str
ATTR_ATTRIBUTION_DOMAINS: str
ATTR_VALUE: str
