from .const import DEFAULT_NAME as DEFAULT_NAME
from mastodon import Mastodon
from mastodon.Mastodon import Account as Account, Instance as Instance, InstanceV2
from typing import Any

def create_mastodon_client(base_url: str, client_id: str, client_secret: str, access_token: str) -> Mastodon: ...
def construct_mastodon_username(instance: InstanceV2 | Instance | None, account: Account | None) -> str: ...
def get_media_type(media_path: Any = None) -> Any: ...
