import asyncio
from .const import DEFAULT_SSL as DEFAULT_SSL, DEFAULT_USERNAME as DEFAULT_USERNAME, DEFAULT_VERIFY_SSL as DEFAULT_VERIFY_SSL, DEVICE_NAME as DEVICE_NAME, DOMAIN as DOMAIN, HOSTNAME as HOSTNAME, IP_ADDRESS as IP_ADDRESS, MAC_ADDRESS as MAC_ADDRESS, SECTION_ADVANCED_SETTINGS as SECTION_ADVANCED_SETTINGS
from _typeshed import Incomplete
from airos.airos6 import AirOS6
from airos.airos8 import AirOS8
from airos.helpers import DetectDeviceData as DetectDeviceData
from collections.abc import Mapping
from homeassistant.config_entries import ConfigFlow as ConfigFlow, ConfigFlowResult as ConfigFlowResult, SOURCE_REAUTH as SOURCE_REAUTH, SOURCE_RECONFIGURE as SOURCE_RECONFIGURE
from homeassistant.const import CONF_HOST as CONF_HOST, CONF_PASSWORD as CONF_PASSWORD, CONF_SSL as CONF_SSL, CONF_USERNAME as CONF_USERNAME, CONF_VERIFY_SSL as CONF_VERIFY_SSL
from homeassistant.data_entry_flow import section as section
from homeassistant.helpers.aiohttp_client import async_get_clientsession as async_get_clientsession
from homeassistant.helpers.device_registry import format_mac as format_mac
from homeassistant.helpers.selector import TextSelector as TextSelector, TextSelectorConfig as TextSelectorConfig, TextSelectorType as TextSelectorType
from homeassistant.helpers.service_info.dhcp import DhcpServiceInfo as DhcpServiceInfo
from typing import Any

_LOGGER: Incomplete
AirOSDeviceDetect = AirOS8 | AirOS6
DISCOVER_INTERVAL: int
STEP_DISCOVERY_DATA_SCHEMA: Incomplete
STEP_MANUAL_DATA_SCHEMA: Incomplete

class AirOSConfigFlow(ConfigFlow, domain=DOMAIN):
    VERSION: int
    MINOR_VERSION: int
    _discovery_task: asyncio.Task | None
    airos_device: AirOSDeviceDetect
    errors: dict[str, str]
    discovered_devices: dict[str, dict[str, Any]]
    discovery_abort_reason: str | None
    selected_device_info: dict[str, Any]
    def __init__(self) -> None: ...
    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_manual(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def _validate_and_get_device_info(self, config_data: dict[str, Any]) -> dict[str, Any] | None: ...
    async def async_step_reauth(self, user_input: Mapping[str, Any]) -> ConfigFlowResult: ...
    async def async_step_reauth_confirm(self, user_input: Mapping[str, Any]) -> ConfigFlowResult: ...
    async def async_step_reconfigure(self, user_input: Mapping[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_discovery(self, discovery_info: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_select_device(self, discovery_info: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_configure_device(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def _async_run_discovery_with_progress(self) -> None: ...
    async def _async_update_progress_bar(self) -> None: ...
    async def async_step_dhcp(self, discovery_info: DhcpServiceInfo) -> ConfigFlowResult: ...
    async def async_step_discovery_no_devices(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_discovery_listen_error(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_discovery_detect_error(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
    async def async_step_discovery_failed(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult: ...
