import asyncio
from .client import CloudClient as CloudClient
from .helpers import FixedSizeQueueLogHandler as FixedSizeQueueLogHandler
from _typeshed import Incomplete
from hass_nabucasa import Cloud as Cloud
from homeassistant.util.hass_dict import HassKey as HassKey
from homeassistant.util.signal_type import SignalType as SignalType
from typing import Any

DOMAIN: str
DATA_CLOUD: HassKey[Cloud[CloudClient]]
DATA_PLATFORMS_SETUP: HassKey[dict[str, asyncio.Event]]
DATA_CLOUD_LOG_HANDLER: HassKey[FixedSizeQueueLogHandler]
EVENT_CLOUD_EVENT: str
REQUEST_TIMEOUT: int
PREF_ENABLE_ALEXA: str
PREF_ENABLE_GOOGLE: str
PREF_ENABLE_REMOTE: str
PREF_GOOGLE_SECURE_DEVICES_PIN: str
PREF_CLOUDHOOKS: str
PREF_CLOUD_USER: str
PREF_GOOGLE_ENTITY_CONFIGS: str
PREF_GOOGLE_REPORT_STATE: str
PREF_ALEXA_ENTITY_CONFIGS: str
PREF_ALEXA_REPORT_STATE: str
PREF_DISABLE_2FA: str
PREF_INSTANCE_ID: str
PREF_SHOULD_EXPOSE: str
PREF_GOOGLE_LOCAL_WEBHOOK_ID: str
PREF_USERNAME: str
PREF_REMOTE_DOMAIN: str
PREF_ALEXA_DEFAULT_EXPOSE: str
PREF_GOOGLE_DEFAULT_EXPOSE: str
PREF_ALEXA_SETTINGS_VERSION: str
PREF_GOOGLE_SETTINGS_VERSION: str
PREF_TTS_DEFAULT_VOICE: str
PREF_GOOGLE_CONNECTED: str
PREF_REMOTE_ALLOW_REMOTE_ENABLE: str
PREF_ENABLE_CLOUD_ICE_SERVERS: str
DEFAULT_TTS_DEFAULT_VOICE: Incomplete
DEFAULT_DISABLE_2FA: bool
DEFAULT_ALEXA_REPORT_STATE: bool
DEFAULT_GOOGLE_REPORT_STATE: bool
DEFAULT_EXPOSED_DOMAINS: Incomplete
CONF_ALEXA: str
CONF_ALIASES: str
CONF_COGNITO_CLIENT_ID: str
CONF_ENTITY_CONFIG: str
CONF_FILTER: str
CONF_GOOGLE_ACTIONS: str
CONF_USER_POOL_ID: str
CONF_ACCOUNT_LINK_SERVER: str
CONF_ACCOUNTS_SERVER: str
CONF_ACME_SERVER: str
CONF_CLOUDHOOK_SERVER: str
CONF_RELAYER_SERVER: str
CONF_REMOTESTATE_SERVER: str
CONF_THINGTALK_SERVER: str
CONF_SERVICEHANDLERS_SERVER: str
MODE_DEV: str
MODE_PROD: str
DISPATCHER_REMOTE_UPDATE: SignalType[Any]
STT_ENTITY_UNIQUE_ID: str
TTS_ENTITY_UNIQUE_ID: str
LOGIN_MFA_TIMEOUT: int
VOICE_STYLE_SEPERATOR: str
