from .const import LOGGER as LOGGER, PLATFORMS as PLATFORMS
from .coordinator import RomyConfigEntry as RomyConfigEntry, RomyVacuumCoordinator as RomyVacuumCoordinator
from homeassistant.const import CONF_HOST as CONF_HOST, CONF_PASSWORD as CONF_PASSWORD
from homeassistant.core import HomeAssistant as HomeAssistant

async def async_setup_entry(hass: HomeAssistant, config_entry: RomyConfigEntry) -> bool: ...
async def async_unload_entry(hass: HomeAssistant, entry: RomyConfigEntry) -> bool: ...
async def update_listener(hass: HomeAssistant, config_entry: RomyConfigEntry) -> None: ...
