from .const import FLUX_COLOR_MODE_TO_HASS as FLUX_COLOR_MODE_TO_HASS, MIN_RGB_BRIGHTNESS as MIN_RGB_BRIGHTNESS
from flux_led.aio import AIOWifiLedBulb as AIOWifiLedBulb
from flux_led.const import MultiColorEffects
from homeassistant.components.light import ColorMode as ColorMode
from homeassistant.util.color import color_RGB_to_hsv as color_RGB_to_hsv, color_hsv_to_RGB as color_hsv_to_RGB

def _hass_color_modes(device: AIOWifiLedBulb) -> set[str]: ...
def format_as_flux_mac(mac: str | None) -> str | None: ...
def _human_readable_option(const_option: str) -> str: ...
def mac_matches_by_one(formatted_mac_1: str, formatted_mac_2: str) -> bool: ...
def _flux_color_mode_to_hass(flux_color_mode: str | None, flux_color_modes: set[str]) -> ColorMode: ...
def _effect_brightness(brightness: int) -> int: ...
def _str_to_multi_color_effect(effect_str: str) -> MultiColorEffects: ...
def _is_zero_rgb_brightness(rgb: tuple[int, int, int]) -> bool: ...
def _min_rgb_brightness(rgb: tuple[int, int, int]) -> tuple[int, int, int]: ...
def _min_scaled_rgb_brightness(rgb: tuple[int, int, int]) -> tuple[int, int, int]: ...
def _min_rgbw_brightness(rgbw: tuple[int, int, int, int], current_rgbw: tuple[int, int, int, int]) -> tuple[int, int, int, int]: ...
def _min_rgbwc_brightness(rgbwc: tuple[int, int, int, int, int], current_rgbwc: tuple[int, int, int, int, int]) -> tuple[int, int, int, int, int]: ...
