from .const import FLUX_COLOR_MODE_TO_HASS as FLUX_COLOR_MODE_TO_HASS
from flux_led.aio import AIOWifiLedBulb as AIOWifiLedBulb
from homeassistant.components.light import COLOR_MODE_BRIGHTNESS as COLOR_MODE_BRIGHTNESS, COLOR_MODE_ONOFF as COLOR_MODE_ONOFF, COLOR_MODE_WHITE as COLOR_MODE_WHITE

def _hass_color_modes(device: AIOWifiLedBulb) -> set[str]: ...
def _flux_color_mode_to_hass(flux_color_mode: Union[str, None], flux_color_modes: set[str]) -> str: ...
def _effect_brightness(brightness: int) -> int: ...
