from .const import MEDIA_PLAYER_PREFIX as MEDIA_PLAYER_PREFIX
from spotifyaio import Image as Image

def is_spotify_media_type(media_content_type: str) -> bool: ...
def resolve_spotify_media_type(media_content_type: str) -> str: ...
def fetch_image_url(images: list[Image]) -> str | None: ...
def spotify_uri_from_media_browser_url(media_content_id: str) -> str: ...
