from .const import CONF_LISTEN_CREDENTIALS as CONF_LISTEN_CREDENTIALS, DOMAIN as DOMAIN, PLATFORMS as PLATFORMS
from .coordinator import RingConfigEntry as RingConfigEntry, RingData as RingData, RingDataCoordinator as RingDataCoordinator, RingListenCoordinator as RingListenCoordinator
from _typeshed import Incomplete
from homeassistant.const import APPLICATION_NAME as APPLICATION_NAME, CONF_DEVICE_ID as CONF_DEVICE_ID, CONF_TOKEN as CONF_TOKEN
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.helpers import device_registry as dr
from homeassistant.helpers.aiohttp_client import async_get_clientsession as async_get_clientsession

_LOGGER: Incomplete

def get_auth_user_agent() -> str: ...
async def async_setup_entry(hass: HomeAssistant, entry: RingConfigEntry) -> bool: ...
async def async_unload_entry(hass: HomeAssistant, entry: RingConfigEntry) -> bool: ...
async def async_remove_config_entry_device(hass: HomeAssistant, entry: RingConfigEntry, device_entry: dr.DeviceEntry) -> bool: ...
async def async_migrate_entry(hass: HomeAssistant, entry: RingConfigEntry) -> bool: ...
