from .atlantic_pass_apc_dhw import AtlanticPassAPCDHW as AtlanticPassAPCDHW
from .domestic_hot_water_production import DomesticHotWaterProduction as DomesticHotWaterProduction
from .hitachi_dhw import HitachiDHW as HitachiDHW
from _typeshed import Incomplete

WIDGET_TO_WATER_HEATER_ENTITY: Incomplete
