from typing import Final

DOMAIN: Final[str]
DEFAULT_HYSTERESIS: Final[float]
ATTR_HYSTERESIS: Final[str]
ATTR_LOWER: Final[str]
ATTR_POSITION: Final[str]
ATTR_SENSOR_VALUE: Final[str]
ATTR_TYPE: Final[str]
ATTR_UPPER: Final[str]
CONF_HYSTERESIS: Final[str]
CONF_LOWER: Final[str]
CONF_UPPER: Final[str]
POSITION_ABOVE: Final[str]
POSITION_BELOW: Final[str]
POSITION_IN_RANGE: Final[str]
POSITION_UNKNOWN: Final[str]
TYPE_LOWER: Final[str]
TYPE_RANGE: Final[str]
TYPE_UPPER: Final[str]
