from .coordinator import IntelliClimaConfigEntry as IntelliClimaConfigEntry, IntelliClimaCoordinator as IntelliClimaCoordinator
from .entity import IntelliClimaECOEntity as IntelliClimaECOEntity
from _typeshed import Incomplete
from homeassistant.components.fan import FanEntity as FanEntity, FanEntityFeature as FanEntityFeature
from homeassistant.core import HomeAssistant as HomeAssistant
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback as AddConfigEntryEntitiesCallback
from homeassistant.util.percentage import percentage_to_ranged_value as percentage_to_ranged_value, ranged_value_to_percentage as ranged_value_to_percentage
from homeassistant.util.scaling import int_states_in_range as int_states_in_range
from pyintelliclima.intelliclima_types import IntelliClimaECO as IntelliClimaECO
from typing import Any

PARALLEL_UPDATES: int

async def async_setup_entry(hass: HomeAssistant, entry: IntelliClimaConfigEntry, async_add_entities: AddConfigEntryEntitiesCallback) -> None: ...

class IntelliClimaVMCFan(IntelliClimaECOEntity, FanEntity):
    _attr_name: Incomplete
    _attr_supported_features: Incomplete
    _attr_preset_modes: Incomplete
    _speed_range: Incomplete
    _attr_unique_id: Incomplete
    def __init__(self, coordinator: IntelliClimaCoordinator, device: IntelliClimaECO) -> None: ...
    @property
    def is_on(self) -> bool: ...
    @property
    def percentage(self) -> int | None: ...
    @property
    def speed_count(self) -> int: ...
    @property
    def preset_mode(self) -> str | None: ...
    async def async_turn_on(self, percentage: int | None = None, preset_mode: str | None = None, **kwargs: Any) -> None: ...
    async def async_turn_off(self, **kwargs: Any) -> None: ...
    async def async_set_percentage(self, percentage: int) -> None: ...
    async def async_set_preset_mode(self, preset_mode: str) -> None: ...
    async def async_set_mode_speed(self, preset_mode: str | None = None, percentage: int | None = None) -> None: ...
