DOMAIN: str
STORAGE_VER: int
STORAGE_KEY = DOMAIN
EVO_RESET: str
EVO_AUTO: str
EVO_AUTOECO: str
EVO_AWAY: str
EVO_DAYOFF: str
EVO_CUSTOM: str
EVO_HEATOFF: str
EVO_FOLLOW: str
EVO_TEMPOVER: str
EVO_PERMOVER: str
GWS: str
TCS: str
UTC_OFFSET: str
