import evohomeasync2 as evo
from _typeshed import Incomplete
from datetime import datetime
from homeassistant.const import CONF_SCAN_INTERVAL as CONF_SCAN_INTERVAL
from typing import Any

_LOGGER: Incomplete

def dt_local_to_aware(dt_naive: datetime) -> datetime: ...
def dt_aware_to_naive(dt_aware: datetime) -> datetime: ...
def convert_until(status_dict: dict, until_key: str) -> None: ...
def convert_dict(dictionary: dict[str, Any]) -> dict[str, Any]: ...
def handle_evo_exception(err: evo.RequestFailed) -> None: ...
