import asyncio
from .const import DOMAIN as DOMAIN, LOGGER as LOGGER
from _typeshed import Incomplete
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.exceptions import TemplateError as TemplateError
from homeassistant.helpers.entity_platform import async_create_platform_config_not_supported_issue as async_create_platform_config_not_supported_issue
from homeassistant.helpers.template import Template as Template
from homeassistant.util import slugify as slugify
from typing import Literal, overload

_EXEC_FAILED_CODE: int
_SHELL_FEATURE_CHARS: Incomplete
_DEPRECATION_ISSUE_BREAKS_IN: str
_LEARN_MORE_URL: str
_ISSUE_ID_PREFIX: str
_ASSIGNMENT_PREFIX: Incomplete

def _has_shell_features(command: str) -> bool: ...
@callback
def _update_issue(hass: HomeAssistant, issue_id: str, prog: str, platform: str, name: str, *, create: bool) -> None: ...
def build_shell_template_issue_id(platform: str, name: str) -> str: ...
@callback
def async_prune_shell_template_issues(hass: HomeAssistant, valid_issue_ids: set[str]) -> None: ...
@overload
async def async_run_shell_command(command: str | list[str], timeout: int, *, stdin: bytes | None = ..., capture_stdout: Literal[False] = ...) -> tuple[asyncio.subprocess.Process, None]: ...
@overload
async def async_run_shell_command(command: str | list[str], timeout: int, *, stdin: bytes | None = ..., capture_stdout: Literal[True]) -> tuple[asyncio.subprocess.Process, bytes]: ...
async def async_call_shell_with_timeout(command: str | list[str], timeout: int, *, log_return_code: bool = True) -> int: ...
async def async_check_output_or_log(command: str | list[str], timeout: int) -> str | None: ...
@callback
def render_template_args(hass: HomeAssistant, command: str, platform: str, name: str) -> str | list[str] | None: ...
def create_platform_yaml_not_supported_issue(hass: HomeAssistant, platform_domain: str) -> None: ...
