from _typeshed import Incomplete
from typing import Final

DOMAIN: Final[str]
DEFAULT_NAME: Final[str]
DEFAULT_API_PORT: Final[int]
DEFAULT_DETECTION_TIME: Final[int]
ATTR_MANUFACTURER: Final[str]
ATTR_SERIAL_NUMBER: Final[str]
ATTR_FIRMWARE: Final[str]
ATTR_MODEL: Final[str]
CONF_ARP_PING: Final[str]
CONF_FORCE_DHCP: Final[str]
CONF_DETECTION_TIME: Final[str]
NAME: Final[str]
INFO: Final[str]
IDENTITY: Final[str]
ARP: Final[str]
CAPSMAN: Final[str]
DHCP: Final[str]
WIRELESS: Final[str]
WIFIWAVE2: Final[str]
IS_WIRELESS: Final[str]
IS_CAPSMAN: Final[str]
IS_WIFIWAVE2: Final[str]
MIKROTIK_SERVICES: Final[Incomplete]
ATTR_DEVICE_TRACKER: Final[Incomplete]
