import librouteros
from .const import ARP as ARP, ATTR_ROUTERBOARD_FIRMWARE as ATTR_ROUTERBOARD_FIRMWARE, ATTR_SERIAL_NUMBER as ATTR_SERIAL_NUMBER, CAPSMAN as CAPSMAN, CONF_ARP_PING as CONF_ARP_PING, CONF_DETECTION_TIME as CONF_DETECTION_TIME, CONF_FORCE_DHCP as CONF_FORCE_DHCP, DEFAULT_DETECTION_TIME as DEFAULT_DETECTION_TIME, DHCP as DHCP, DOMAIN as DOMAIN, HEALTH as HEALTH, IDENTITY as IDENTITY, IS_CAPSMAN as IS_CAPSMAN, IS_WIFI as IS_WIFI, IS_WIFIWAVE2 as IS_WIFIWAVE2, IS_WIRELESS as IS_WIRELESS, LOGGER as LOGGER, MIKROTIK_SERVICES as MIKROTIK_SERVICES, NAME as NAME, RESOURCE as RESOURCE, ROUTERBOARD as ROUTERBOARD, UPDATE as UPDATE, WIFI as WIFI, WIFIWAVE2 as WIFIWAVE2, WIRELESS as WIRELESS
from .device import Device as Device
from .errors import CannotConnect as CannotConnect, LoginError as LoginError
from .utils import calculate_uptime as calculate_uptime, mikrotik_config_entry_errors as mikrotik_config_entry_errors, percentage as percentage
from _typeshed import Incomplete
from datetime import timedelta
from homeassistant.config_entries import ConfigEntry as ConfigEntry
from homeassistant.const import ATTR_MODEL as ATTR_MODEL, CONF_HOST as CONF_HOST, CONF_PASSWORD as CONF_PASSWORD, CONF_USERNAME as CONF_USERNAME, CONF_VERIFY_SSL as CONF_VERIFY_SSL
from homeassistant.core import HomeAssistant as HomeAssistant
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator as DataUpdateCoordinator
from typing import Any, override

type MikrotikConfigEntry = ConfigEntry[MikrotikDataUpdateCoordinator]
class MikrotikData:
    hass: Incomplete
    config_entry: Incomplete
    api: Incomplete
    _host: str
    all_devices: dict[str, dict[str, Any]]
    devices: dict[str, Device]
    support_capsman: bool
    support_wireless: bool
    support_wifiwave2: bool
    support_wifi: bool
    hostname: str
    model: str
    firmware: str
    serial_number: str
    sensors: dict[str, Any]
    system: dict[str, Any]
    def __init__(self, hass: HomeAssistant, config_entry: ConfigEntry, api: librouteros.Api) -> None: ...
    def _get_system_details(self, during_setup: bool = False) -> None: ...
    def _get_health_details(self) -> None: ...
    def _get_resource_details(self) -> None: ...
    @staticmethod
    def load_mac(devices: list[dict[str, Any]]) -> dict[str, dict[str, Any]]: ...
    @property
    def arp_enabled(self) -> bool: ...
    @property
    def force_dhcp(self) -> bool: ...
    def get_hub_details(self) -> None: ...
    def get_list_from_interface(self, interface: str) -> dict[str, dict[str, Any]]: ...
    def restore_device(self, mac: str) -> None: ...
    def update_devices(self) -> None: ...
    def do_arp_ping(self, ip_address: str, interface: str) -> bool: ...
    def command(self, cmd: str, params: dict[str, Any] | None = None, suppress_errors: bool = False, during_setup: bool = False) -> list[dict[str, Any]]: ...

class MikrotikDataUpdateCoordinator(DataUpdateCoordinator[None]):
    config_entry: MikrotikConfigEntry
    _mk_data: Incomplete
    def __init__(self, hass: HomeAssistant, config_entry: MikrotikConfigEntry, api: librouteros.Api) -> None: ...
    @property
    def host(self) -> str: ...
    @property
    def hostname(self) -> str: ...
    @property
    def model(self) -> str: ...
    @property
    def firmware(self) -> str: ...
    @property
    def serial_num(self) -> str: ...
    @property
    def option_detection_time(self) -> timedelta: ...
    @property
    def api(self) -> MikrotikData: ...
    @override
    async def _async_update_data(self) -> None: ...

def get_api(entry: dict[str, Any]) -> librouteros.Api: ...
