name: Publish new packages

concurrency: release

on:
  schedule:
    - cron: "20 0,12 * * *"
  workflow_dispatch:

jobs:
  publish:
    name: Generate and publish
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Prepare and install deps
        uses: ./.github/actions/install-deps

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate and publish new packages
        run: UV_BIN_PATH=$(which uv) uv run python update_stubs.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
