name: Publish new packages

on:
  schedule:
    - cron: "20 0,12 * * *"
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  publish:
    name: Generate and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Use local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/cache@v4
        id: cache-poetry-deps
        name: Cache Poetry dependencies
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-

      - name: Install dependencies with Poetry
        if: steps.cache-poetry-deps.outputs.cache-hit != 'true'
        run: poetry install

      - name: Generate and publish new packages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          poetry run python update_stubs.py
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
