name: Publish new packages

concurrency: release
environment: release

on:
  schedule:
    - cron: "20 0,12 * * *"
  workflow_dispatch:

jobs:
  publish:
    name: Generate and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Prepare and install deps
        uses: ./.github/actions/install-deps

      - name: Generate and publish new packages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          uv run python update_stubs.py
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
