from _typeshed import Incomplete

DOMAIN: str
DATA_AMCREST = DOMAIN
CAMERAS: str
DEVICES: str
BINARY_SENSOR_SCAN_INTERVAL_SECS: int
CAMERA_WEB_SESSION_TIMEOUT: int
COMM_RETRIES: int
COMM_TIMEOUT: float
SENSOR_SCAN_INTERVAL_SECS: int
SNAPSHOT_TIMEOUT: int
SERVICE_EVENT: str
SERVICE_UPDATE: str
RESOLUTION_LIST: Incomplete
RESOLUTION_TO_STREAM: Incomplete
