from .const import DOMAIN as DOMAIN, INFRARED_LEVELS as INFRARED_LEVELS, LIFX_IDENTIFY_DELAY as LIFX_IDENTIFY_DELAY, LOGGER as LOGGER
from .util import device_error as device_error
from _typeshed import Incomplete
from collections.abc import Callable as Callable
from homeassistant.config_entries import ConfigEntry as ConfigEntry
from homeassistant.const import Platform as Platform, SIGNAL_STRENGTH_DECIBELS_MILLIWATT as SIGNAL_STRENGTH_DECIBELS_MILLIWATT
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.helpers.debounce import Debouncer as Debouncer
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator as DataUpdateCoordinator, UpdateFailed as UpdateFailed
from lifx import CeilingLightState, Device as Device, HevLightState, InfraredLightState, LightState, MatrixLightState, MultiZoneLightState
from typing import override

type LIFXState = LightState | MultiZoneLightState | MatrixLightState | CeilingLightState | HevLightState | InfraredLightState
type LIFXConfigEntry = ConfigEntry[LIFXUpdateCoordinator]
class LIFXUpdateCoordinator(DataUpdateCoordinator[LIFXState]):
    device: Incomplete
    last_used_theme: str | None
    def __init__(self, hass: HomeAssistant, entry: LIFXConfigEntry, device: Device) -> None: ...
    @override
    async def _async_update_data(self) -> LIFXState: ...
    @property
    def serial_number(self) -> str: ...
    @property
    def current_infrared_brightness(self) -> str | None: ...
    @property
    def rssi(self) -> int | None: ...
    @property
    def rssi_uom(self) -> str | None: ...
    def async_get_entity_id(self, platform: Platform, key: str) -> str | None: ...
    async def async_restart(self) -> None: ...
    async def _async_flash_bulb(self) -> None: ...
    async def async_identify_bulb(self) -> None: ...
    def async_enable_rssi_updates(self) -> Callable[[], None]: ...
    async def async_set_infrared_brightness(self, option: str) -> None: ...
    async def async_set_hev_cycle_state(self, enable: bool, duration: int = 0) -> None: ...
    async def async_apply_theme(self, theme_name: str) -> None: ...
