from .const import ATTR_REMAINING as ATTR_REMAINING, IDENTIFY_WAVEFORM as IDENTIFY_WAVEFORM, MESSAGE_RETRIES as MESSAGE_RETRIES, MESSAGE_TIMEOUT as MESSAGE_TIMEOUT, TARGET_ANY as TARGET_ANY, UNAVAILABLE_GRACE as UNAVAILABLE_GRACE, _LOGGER as _LOGGER
from .util import async_execute_lifx as async_execute_lifx, get_real_mac_addr as get_real_mac_addr, lifx_features as lifx_features
from _typeshed import Incomplete
from aiolifx.aiolifx import Light as Light
from aiolifx.connection import LIFXConnection as LIFXConnection
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.helpers.debounce import Debouncer as Debouncer
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator as DataUpdateCoordinator, UpdateFailed as UpdateFailed
from typing import Any

REQUEST_REFRESH_DELAY: float
LIFX_IDENTIFY_DELAY: float

class LIFXUpdateCoordinator(DataUpdateCoordinator):
    connection: Incomplete
    device: Incomplete
    lock: Incomplete
    def __init__(self, hass: HomeAssistant, connection: LIFXConnection, title: str) -> None: ...
    def async_setup(self) -> None: ...
    @property
    def serial_number(self) -> str: ...
    @property
    def mac_address(self) -> str: ...
    @property
    def label(self) -> str: ...
    async def async_identify_bulb(self) -> None: ...
    async def _async_update_data(self) -> None: ...
    async def async_update_color_zones(self) -> None: ...
    def async_get_hev_cycle_state(self) -> Union[bool, None]: ...
    async def async_get_hev_cycle(self) -> None: ...
    async def async_set_waveform_optional(self, value: dict[str, Any], rapid: bool = ...) -> None: ...
    async def async_get_color(self) -> None: ...
    async def async_set_power(self, state: bool, duration: Union[int, None]) -> None: ...
    async def async_set_color(self, hsbk: list[Union[float, int, None]], duration: Union[int, None]) -> None: ...
    async def async_set_color_zones(self, start_index: int, end_index: int, hsbk: list[Union[float, int, None]], duration: Union[int, None], apply: int) -> None: ...
