from .const import CONF_SERIAL as CONF_SERIAL, DOMAIN as DOMAIN, LOGGER as LOGGER
from .coordinator import LIFXConfigEntry as LIFXConfigEntry
from _typeshed import Incomplete
from homeassistant.components.light import ATTR_BRIGHTNESS as ATTR_BRIGHTNESS, ATTR_BRIGHTNESS_PCT as ATTR_BRIGHTNESS_PCT, ATTR_COLOR_NAME as ATTR_COLOR_NAME, ATTR_COLOR_TEMP_KELVIN as ATTR_COLOR_TEMP_KELVIN, ATTR_HS_COLOR as ATTR_HS_COLOR, ATTR_RGB_COLOR as ATTR_RGB_COLOR, ATTR_XY_COLOR as ATTR_XY_COLOR
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from homeassistant.exceptions import HomeAssistantError as HomeAssistantError, ServiceValidationError as ServiceValidationError
from lifx import HSBK as HSBK, LifxError as LifxError
from typing import Any, TypedDict

_SERIAL_PATTERN: Incomplete

def normalize_serial(value: str) -> str: ...
async def async_resolve_host(hass: HomeAssistant, host: str) -> str: ...
@callback
def async_entry_serial(entry: LIFXConfigEntry) -> str | None: ...

class HSBKChanges(TypedDict):
    hue: float | None
    saturation: float | None
    brightness: float | None
    kelvin: int | None

def parse_hsbk_changes(**kwargs: Any) -> HSBKChanges: ...
def device_error(err: LifxError) -> HomeAssistantError: ...
def replace_hsbk(base: HSBK, changes: HSBKChanges) -> HSBK: ...
def overwrites_existing_color(changes: HSBKChanges) -> bool: ...
def find_hsbk(base: HSBK, **kwargs: Any) -> HSBK | None: ...
def palette_fraction(value: float) -> float: ...
