from .const import DOMAIN as DOMAIN, OVERALL_TIMEOUT as OVERALL_TIMEOUT, _LOGGER as _LOGGER
from _typeshed import Incomplete
from aiolifx.aiolifx import Light as Light
from aiolifx.message import Message as Message
from collections.abc import Callable as Callable
from homeassistant.components.light import ATTR_BRIGHTNESS as ATTR_BRIGHTNESS, ATTR_COLOR_TEMP as ATTR_COLOR_TEMP, ATTR_HS_COLOR as ATTR_HS_COLOR, ATTR_RGB_COLOR as ATTR_RGB_COLOR, ATTR_XY_COLOR as ATTR_XY_COLOR, preprocess_turn_on_alternatives as preprocess_turn_on_alternatives
from homeassistant.config_entries import ConfigEntry as ConfigEntry
from homeassistant.core import HomeAssistant as HomeAssistant, callback as callback
from typing import Any

FIX_MAC_FW: Incomplete

def async_entry_is_legacy(entry: ConfigEntry) -> bool: ...
def async_get_legacy_entry(hass: HomeAssistant) -> Union[ConfigEntry, None]: ...
def convert_8_to_16(value: int) -> int: ...
def convert_16_to_8(value: int) -> int: ...
def lifx_features(bulb: Light) -> dict[str, Any]: ...
def find_hsbk(hass: HomeAssistant, **kwargs: Any) -> Union[list[Union[float, int, None]], None]: ...
def merge_hsbk(base: list[Union[float, int, None]], change: list[Union[float, int, None]]) -> list[Union[float, int, None]]: ...
def _get_mac_offset(mac_addr: str, offset: int) -> str: ...
def _off_by_one_mac(firmware: str) -> bool: ...
def get_real_mac_addr(mac_addr: str, firmware: str) -> str: ...
def formatted_serial(serial_number: str) -> str: ...
def mac_matches_serial_number(mac_addr: str, serial_number: str) -> bool: ...
async def async_execute_lifx(method: Callable) -> Message: ...
